// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Wide Screen' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * subHeading?: string // Sub Heading
 * privacyNote?: string // Privacy Note
}} Props

 */
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-XSBYVWOY.js";
import {
	className as className6,
	css as css6,
	fonts as fonts6,
} from "./chunks/chunk-LVJPX2QD.js";
import {
	className as className7,
	css as css7,
	fonts as fonts7,
} from "./chunks/chunk-NMIDWPYK.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-42HXHAFZ.js";
import { ZipText } from "./chunks/chunk-NCI35YOA.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-YC4JS6HC.js";
import { className, css, fonts } from "./chunks/chunk-PNSODGZQ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SZHLSPRP.js";
import { Starsfield } from "./chunks/chunk-LQOJXZ4V.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:cta-contact-section
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/r5WDP1Ms7JExVZcp9FLG/IaKdRj8Td6b81vPgf2ir/uAD9AVGHQ.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider3,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts3,
	getFontsFromSharedStyle as getFontsFromSharedStyle3,
	RichText as RichText3,
	SmartComponentScopedContainer as SmartComponentScopedContainer3,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/eLDziRUSsPZ2o3sXGS6c/grQOmOoI94n5jYCkt9D9/j56o8MIl6.js
import {
	jsx as _jsx2,
	jsxs as _jsxs2,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	FormContainer,
	FormPlainTextInput,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/18fKoA4LpOSxJWbvGJQg/WYiSEEmUoJDngsGQrNpZ/xBO6RVeqy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var StarsfieldFonts = getFonts(Starsfield);
var cycleOrder = [
	"Mr9AJ_Tw9",
	"BLpbQRiPV",
	"nAuo8vBzQ",
	"D8QHjRNvR",
	"kPTQUtUv2",
	"iUviNC0GG",
	"IZDhILsNJ",
	"WE1m0xxox",
];
var serializationHash = "framer-zRCWO";
var variantClassNames = {
	BLpbQRiPV: "framer-v-ovrw9d",
	D8QHjRNvR: "framer-v-1o34bdq",
	iUviNC0GG: "framer-v-1wifl4d",
	IZDhILsNJ: "framer-v-vu46yg",
	kPTQUtUv2: "framer-v-2zxozf",
	Mr9AJ_Tw9: "framer-v-1wi233y",
	nAuo8vBzQ: "framer-v-1l4ncgw",
	WE1m0xxox: "framer-v-uht8qw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.5,
	ease: [0.61, 0.29, 0, 1.01],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Tablet & Phone": "D8QHjRNvR",
	Error: "IZDhILsNJ",
	FX: "BLpbQRiPV",
	Hover: "nAuo8vBzQ",
	Incomplete: "WE1m0xxox",
	Loading: "kPTQUtUv2",
	Normal: "Mr9AJ_Tw9",
	Success: "iUviNC0GG",
};
var getProps = ({ height, id, textInLink, width, ...props }) => {
	return {
		...props,
		PW51ip198: textInLink ?? props.PW51ip198 ?? "Join the Waitlist",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "Mr9AJ_Tw9",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		PW51ip198: PW51ip1982,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Mr9AJ_Tw9",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEntero6vmd5 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		await delay(() => setVariant("BLpbQRiPV"), 200);
	});
	const onAppearziso74 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("nAuo8vBzQ", true), 300);
	});
	const onMouseLeave1mq19mv = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		await delay(() => setVariant("Mr9AJ_Tw9"), 200);
	});
	useOnVariantChange(baseVariant, {
		BLpbQRiPV: onAppearziso74,
	});
	const sharedStyleClassNames = [className, className6];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			[
				"BLpbQRiPV",
				"nAuo8vBzQ",
				"D8QHjRNvR",
				"kPTQUtUv2",
				"iUviNC0GG",
				"IZDhILsNJ",
			].includes(baseVariant)
		)
			return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1wi233y",
							className8,
							classNames,
						)}
						data-framer-name={"Normal"}
						data-highlight={true}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"Mr9AJ_Tw9"}
						onMouseEnter={onMouseEntero6vmd5}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color": "rgba(0, 0, 0, 0)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							opacity: 1,
							...style,
						}}
						variants={{
							BLpbQRiPV: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
							},
							D8QHjRNvR: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
							iUviNC0GG: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
							},
							IZDhILsNJ: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
							},
							kPTQUtUv2: {
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
							},
							nAuo8vBzQ: {
								"--border-bottom-width": "50px",
								"--border-color":
									"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								"--border-left-width": "50px",
								"--border-right-width": "50px",
								"--border-style": "solid",
								"--border-top-width": "50px",
							},
							WE1m0xxox: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								opacity: 0.5,
							},
						}}
						{...addPropertyOverrides(
							{
								BLpbQRiPV: {
									"data-border": true,
									"data-framer-name": "FX",
									onMouseEnter: void 0,
								},
								D8QHjRNvR: {
									"data-framer-name": "Tablet & Phone",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
								iUviNC0GG: {
									"data-border": true,
									"data-framer-name": "Success",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
								IZDhILsNJ: {
									"data-border": true,
									"data-framer-name": "Error",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
								kPTQUtUv2: {
									"data-border": true,
									"data-framer-name": "Loading",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
								nAuo8vBzQ: {
									"data-border": true,
									"data-framer-name": "Hover",
									onMouseEnter: void 0,
									onMouseLeave: onMouseLeave1mq19mv,
								},
								WE1m0xxox: {
									"data-framer-name": "Incomplete",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-g4qqq9"}
							data-framer-name={"Tech Lines Left"}
							layoutDependency={layoutDependency}
							layoutId={"BeqKsFX4L"}
							style={{
								opacity: 1,
							}}
							variants={{
								D8QHjRNvR: {
									opacity: 1,
								},
								iUviNC0GG: {
									opacity: 1,
								},
								IZDhILsNJ: {
									opacity: 1,
								},
								kPTQUtUv2: {
									opacity: 1,
								},
								nAuo8vBzQ: {
									opacity: 0,
								},
								WE1m0xxox: {
									opacity: 1,
								},
							}}
						>
							<SVG
								className={"framer-vm2pr6"}
								data-framer-name={"tech_lines"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"j7d5m5LRy"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 1 20 L 1 6.842 L 2.316 5.526" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 20 1 L 6.842 1 L 5.526 2.315" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={11214153100}
								withExternalLayout={true}
							/>
						</motion.div>
						<motion.div
							className={"framer-o7xci5"}
							data-framer-name={"Tech Lines Left"}
							layoutDependency={layoutDependency}
							layoutId={"FdtR0I_xX"}
							style={{
								opacity: 1,
								rotate: 180,
							}}
							variants={{
								D8QHjRNvR: {
									opacity: 1,
								},
								iUviNC0GG: {
									opacity: 1,
								},
								IZDhILsNJ: {
									opacity: 1,
								},
								kPTQUtUv2: {
									opacity: 1,
								},
								nAuo8vBzQ: {
									opacity: 0,
								},
								WE1m0xxox: {
									opacity: 1,
								},
							}}
						>
							<SVG
								className={"framer-8hir60"}
								data-framer-name={"tech_lines"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"fh1TVBC5O"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 1 20 L 1 6.842 L 2.316 5.526" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 20 1 L 6.842 1 L 5.526 2.315" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={11214153100}
								withExternalLayout={true}
							/>
						</motion.div>
						<motion.div
							className={"framer-1f6tnhq"}
							data-border={true}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"kKl5yYVVT"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgba(0, 0, 0, 0)",
							}}
							variants={{
								BLpbQRiPV: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
								},
								D8QHjRNvR: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor:
										"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
								},
								iUviNC0GG: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
								IZDhILsNJ: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
								kPTQUtUv2: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
								WE1m0xxox: {
									backgroundColor: "rgba(0, 0, 0, 0)",
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-10lt0l4"}
								data-framer-name={"Contact now"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"I1OjkWJqS"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={PW51ip1982}
								variants={{
									iUviNC0GG: {
										"--extracted-1vqrutl":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										"--extracted-1w1cjl5":
											"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
									},
									IZDhILsNJ: {
										"--extracted-1w1cjl5":
											"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
									},
									kPTQUtUv2: {
										"--extracted-1vqrutl":
											"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
									},
								}}
								verticalAlignment={"center"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										D8QHjRNvR: {
											children: (
												<React.Fragment>
													<motion.h6
														className={"framer-styles-preset-92mpg9"}
														data-styles-preset={"pLAsvwM58"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"Contact now"}
													</motion.h6>
												</React.Fragment>
											),
										},
										iUviNC0GG: {
											children: (
												<React.Fragment>
													<motion.h6
														className={"framer-styles-preset-4995rr"}
														data-styles-preset={"eGWmhLuo2"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
														}}
													>
														<motion.span
															style={{
																"--framer-text-color":
																	"var(--extracted-1vqrutl, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
															}}
														>
															{"Thank you! "}
														</motion.span>
														{"We will contact."}
													</motion.h6>
												</React.Fragment>
											),
											text: void 0,
										},
										IZDhILsNJ: {
											children: (
												<React.Fragment>
													<motion.h6
														className={"framer-styles-preset-4995rr"}
														data-styles-preset={"eGWmhLuo2"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
														}}
													>
														{"Can't Sent..."}
													</motion.h6>
												</React.Fragment>
											),
											text: void 0,
										},
										kPTQUtUv2: {
											children: (
												<React.Fragment>
													<motion.h6
														className={"framer-styles-preset-4995rr"}
														data-styles-preset={"eGWmhLuo2"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"In Progress"}
														<motion.span
															style={{
																"--framer-text-color":
																	"var(--extracted-1vqrutl, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
															}}
														>
															{"..."}
														</motion.span>
													</motion.h6>
												</React.Fragment>
											),
											text: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-4995rr"}
										data-styles-preset={"eGWmhLuo2"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
										}}
									>
										{"Contact now"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-m4moxl-container"}
										isAuthoredByUser={true}
										layoutDependency={layoutDependency}
										layoutId={"s6eZGuQV2-container"}
										nodeId={"s6eZGuQV2"}
										rendersWithMotion={true}
										scopeId={"xBO6RVeqy"}
										style={{
											opacity: 1,
										}}
										variants={{
											BLpbQRiPV: {
												opacity: 0,
											},
											D8QHjRNvR: {
												opacity: 1,
											},
											iUviNC0GG: {
												opacity: 0,
											},
											IZDhILsNJ: {
												opacity: 0,
											},
											kPTQUtUv2: {
												opacity: 0,
											},
											nAuo8vBzQ: {
												opacity: 1,
											},
										}}
									>
										<Starsfield
											bgColor={
												"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))"
											}
											fadeInRange={0.3}
											focal={0.6}
											height={"100%"}
											id={"s6eZGuQV2"}
											layoutId={"s6eZGuQV2"}
											reverseFly={false}
											speed={0.23}
											spread={2}
											starColor={"rgb(255, 255, 255)"}
											starCount={300}
											starSize={0.5}
											stopMotionInEditor={false}
											style={{
												height: "100%",
												width: "100%",
											}}
											trail={0.51}
											twinkle={0}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion.div>
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zRCWO.framer-17on3b1, .framer-zRCWO .framer-17on3b1 { display: block; }",
	".framer-zRCWO.framer-1wi233y { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 85px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 25px 0px 25px; position: relative; width: 400px; }",
	".framer-zRCWO .framer-g4qqq9 { flex: none; height: 21px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 1px; width: 20px; z-index: 1; }",
	".framer-zRCWO .framer-vm2pr6, .framer-zRCWO .framer-8hir60 { flex: none; height: 20px; left: calc(50.00000000000002% - 20px / 2); position: absolute; top: calc(47.61904761904764% - 20px / 2); width: 20px; }",
	".framer-zRCWO .framer-o7xci5 { bottom: 0px; flex: none; height: 21px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; width: 20px; z-index: 1; }",
	".framer-zRCWO .framer-1f6tnhq { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: 44px; justify-content: center; overflow: visible; padding: 5px; position: relative; user-select: none; width: 1px; }",
	".framer-zRCWO .framer-10lt0l4 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 2; }",
	".framer-zRCWO .framer-m4moxl-container { flex: none; height: 103%; left: calc(50.00000000000002% - 101% / 2); mix-blend-mode: lighten; position: absolute; top: calc(50.00000000000002% - 103% / 2); width: 101%; z-index: 1; }",
	".framer-zRCWO.framer-v-ovrw9d.framer-1wi233y, .framer-zRCWO.framer-v-1l4ncgw.framer-1wi233y, .framer-zRCWO.framer-v-2zxozf.framer-1wi233y, .framer-zRCWO.framer-v-1wifl4d.framer-1wi233y, .framer-zRCWO.framer-v-vu46yg.framer-1wi233y { padding: 0px; }",
	".framer-zRCWO.framer-v-ovrw9d .framer-g4qqq9, .framer-zRCWO.framer-v-2zxozf .framer-g4qqq9, .framer-zRCWO.framer-v-1wifl4d .framer-g4qqq9, .framer-zRCWO.framer-v-vu46yg .framer-g4qqq9 { left: -5px; top: -4px; }",
	".framer-zRCWO.framer-v-ovrw9d .framer-o7xci5, .framer-zRCWO.framer-v-2zxozf .framer-o7xci5, .framer-zRCWO.framer-v-1wifl4d .framer-o7xci5, .framer-zRCWO.framer-v-vu46yg .framer-o7xci5 { bottom: -5px; right: -5px; }",
	".framer-zRCWO.framer-v-ovrw9d .framer-1f6tnhq, .framer-zRCWO.framer-v-2zxozf .framer-1f6tnhq, .framer-zRCWO.framer-v-1wifl4d .framer-1f6tnhq, .framer-zRCWO.framer-v-vu46yg .framer-1f6tnhq { height: 84px; }",
	".framer-zRCWO.framer-v-1l4ncgw .framer-g4qqq9 { left: -15px; top: -14px; }",
	".framer-zRCWO.framer-v-1l4ncgw .framer-o7xci5 { bottom: -15px; right: -15px; }",
	".framer-zRCWO.framer-v-1l4ncgw .framer-1f6tnhq { height: 84px; overflow: var(--overflow-clip-fallback, clip); z-index: 2; }",
	".framer-zRCWO.framer-v-1l4ncgw .framer-10lt0l4 { order: 1; }",
	".framer-zRCWO.framer-v-1l4ncgw .framer-m4moxl-container { order: 0; }",
	".framer-zRCWO.framer-v-1o34bdq.framer-1wi233y { height: 90px; padding: 0px 15px 0px 15px; width: 320px; }",
	".framer-zRCWO.framer-v-1o34bdq .framer-1f6tnhq { height: 55px; overflow: var(--overflow-clip-fallback, clip); padding: 20px; }",
	".framer-zRCWO.framer-v-1o34bdq .framer-m4moxl-container { height: 106%; top: calc(50.00000000000002% - 106% / 2); }",
	...css,
	...css6,
	'.framer-zRCWO[data-border="true"]::after, .framer-zRCWO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerxBO6RVeqy = withCSS(Component, css8, "framer-zRCWO");
var stdin_default = FramerxBO6RVeqy;
FramerxBO6RVeqy.displayName = "Button for Forms";
FramerxBO6RVeqy.defaultProps = {
	height: 85,
	width: 400,
};
addPropertyControls(FramerxBO6RVeqy, {
	variant: {
		options: [
			"Mr9AJ_Tw9",
			"BLpbQRiPV",
			"nAuo8vBzQ",
			"D8QHjRNvR",
			"kPTQUtUv2",
			"iUviNC0GG",
			"IZDhILsNJ",
			"WE1m0xxox",
		],
		optionTitles: [
			"Normal",
			"FX",
			"Hover",
			"Tablet & Phone",
			"Loading",
			"Success",
			"Error",
			"Incomplete",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	PW51ip198: {
		defaultValue: "Join the Waitlist",
		displayTextArea: false,
		title: "Text in Link",
		type: ControlType.String,
	},
});
addFonts(
	FramerxBO6RVeqy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...StarsfieldFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/eLDziRUSsPZ2o3sXGS6c/grQOmOoI94n5jYCkt9D9/j56o8MIl6.js
var ButtonForFormsFonts = getFonts2(stdin_default);
var cycleOrder2 = ["dl3N03XXx", "zl3wiBlhn", "NqlxNo9sU", "hlklQp1CF"];
var serializationHash2 = "framer-BZUDS";
var variantClassNames2 = {
	dl3N03XXx: "framer-v-bulrf",
	hlklQp1CF: "framer-v-1qz2vzl",
	NqlxNo9sU: "framer-v-1x0nnis",
	zl3wiBlhn: "framer-v-1xnjq7s",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
		default:
			return currentVariant;
	}
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Wide Screen": "dl3N03XXx",
	Laptop: "zl3wiBlhn",
	Phone: "hlklQp1CF",
	Tablet: "NqlxNo9sU",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "dl3N03XXx",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "dl3N03XXx",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className6];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-bulrf",
							className8,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"dl3N03XXx"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								hlklQp1CF: {
									"data-framer-name": "Phone",
								},
								NqlxNo9sU: {
									"data-framer-name": "Tablet",
								},
								zl3wiBlhn: {
									"data-framer-name": "Laptop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<FormContainer
							action={
								"https://api.framer.com/forms/v1/forms/fc8c2061-2e6b-4232-9cfa-4f09e790c6a2/submit"
							}
							className={"framer-9h5j1h"}
							layoutDependency={layoutDependency}
							layoutId={"B9AXh9aKi"}
							nodeId={"B9AXh9aKi"}
						>
							{(formState) => (
								<_Fragment>
									<motion2.div
										className={"framer-181v4s0"}
										data-framer-name={"Fields"}
										layoutDependency={layoutDependency}
										layoutId={"FU8FGRRvl"}
									>
										<motion2.div
											className={"framer-t8ltdr"}
											data-framer-name={"1"}
											layoutDependency={layoutDependency}
											layoutId={"y0CXbSqDE"}
										>
											<motion2.label
												className={"framer-1de8513"}
												data-framer-name={"Name"}
												layoutDependency={layoutDependency}
												layoutId={"MqJvEKCNT"}
											>
												<RichText2
													__fromCanvasComponent={true}
													className={"framer-uz2ljr"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"hQKtbmRPe"}
													style={{
														"--extracted-1w1cjl5":
															"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"center"}
													withExternalLayout={true}
												>
													<React2.Fragment>
														<motion2.h6
															className={"framer-styles-preset-92mpg9"}
															data-styles-preset={"pLAsvwM58"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
															}}
														>
															{"Name"}
														</motion2.h6>
													</React2.Fragment>
												</RichText2>
												<FormPlainTextInput
													className={"framer-1rucr3h"}
													inputName={"Name"}
													layoutDependency={layoutDependency}
													layoutId={"JuaZNPlvH"}
													placeholder={"Jane Smith"}
													required={true}
													style={{
														"--framer-input-border-bottom-width": "1px",
														"--framer-input-border-color":
															"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
														"--framer-input-border-left-width": "0px",
														"--framer-input-border-right-width": "0px",
														"--framer-input-border-style": "solid",
														"--framer-input-border-top-width": "0px",
														"--framer-input-font-color":
															"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
														"--framer-input-icon-color": "rgb(153, 153, 153)",
														"--framer-input-placeholder-color":
															"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
													}}
													type={"text"}
												/>
											</motion2.label>
										</motion2.div>
										<motion2.div
											className={"framer-1fvzk8k"}
											data-framer-name={"2"}
											layoutDependency={layoutDependency}
											layoutId={"fZq8fhz93"}
										>
											<motion2.label
												className={"framer-5nc9y5"}
												data-framer-name={"Email"}
												layoutDependency={layoutDependency}
												layoutId={"cA5ULC2VB"}
											>
												<RichText2
													__fromCanvasComponent={true}
													className={"framer-4ckb6u"}
													data-framer-name={"Email"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"ARf2jmrL0"}
													style={{
														"--extracted-1w1cjl5":
															"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"center"}
													withExternalLayout={true}
												>
													<React2.Fragment>
														<motion2.h6
															className={"framer-styles-preset-92mpg9"}
															data-styles-preset={"pLAsvwM58"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
															}}
														>
															{"Email"}
														</motion2.h6>
													</React2.Fragment>
												</RichText2>
												<FormPlainTextInput
													className={"framer-175lyq8"}
													inputName={"Email"}
													layoutDependency={layoutDependency}
													layoutId={"c1srQXHgR"}
													placeholder={"your@email.com"}
													required={true}
													style={{
														"--framer-input-border-bottom-width": "1px",
														"--framer-input-border-color":
															"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
														"--framer-input-border-left-width": "0px",
														"--framer-input-border-right-width": "0px",
														"--framer-input-border-style": "solid",
														"--framer-input-border-top-width": "0px",
														"--framer-input-font-color":
															"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
														"--framer-input-icon-color": "rgb(153, 153, 153)",
														"--framer-input-placeholder-color":
															"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
													}}
													type={"email"}
												/>
											</motion2.label>
										</motion2.div>
										<motion2.div
											className={"framer-19pbcux"}
											data-framer-name={"3"}
											layoutDependency={layoutDependency}
											layoutId={"o8U_2qbsL"}
										>
											<motion2.label
												className={"framer-ibo0lx"}
												data-framer-name={"Mesage"}
												layoutDependency={layoutDependency}
												layoutId={"NsH_KGmM_"}
											>
												<RichText2
													__fromCanvasComponent={true}
													className={"framer-zbvgnb"}
													data-framer-name={"Mesage"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"BrJ950FRv"}
													style={{
														"--extracted-1w1cjl5":
															"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"center"}
													withExternalLayout={true}
												>
													<React2.Fragment>
														<motion2.h6
															className={"framer-styles-preset-92mpg9"}
															data-styles-preset={"pLAsvwM58"}
															style={{
																"--framer-text-color":
																	"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
															}}
														>
															{"Mesage"}
														</motion2.h6>
													</React2.Fragment>
												</RichText2>
												<motion2.div
													className={"framer-gfb40w"}
													layoutDependency={layoutDependency}
													layoutId={"hFVtjDw8d"}
												>
													<FormPlainTextInput
														className={"framer-1ihpgm7"}
														data-framer-name={"Mesage"}
														inputName={"Mesage"}
														layoutDependency={layoutDependency}
														layoutId={"M3HvyIqsu"}
														maxLength={500}
														placeholder={""}
														required={false}
														style={{
															"--framer-input-border-bottom-width": "1px",
															"--framer-input-border-color":
																"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
															"--framer-input-border-left-width": "0px",
															"--framer-input-border-right-width": "0px",
															"--framer-input-border-style": "solid",
															"--framer-input-border-top-width": "0px",
															"--framer-input-font-color":
																"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
															"--framer-input-icon-color": "rgb(153, 153, 153)",
															"--framer-input-placeholder-color":
																"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
														}}
														type={"textarea"}
													/>
													<motion2.div
														className={"framer-1w2rd5o"}
														data-framer-name={"Line"}
														layoutDependency={layoutDependency}
														layoutId={"aDkW66nTV"}
														style={{
															backgroundColor:
																"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
														}}
													/>
													<motion2.div
														className={"framer-h36n55"}
														data-framer-name={"Line"}
														layoutDependency={layoutDependency}
														layoutId={"blvrxSSD_"}
														style={{
															backgroundColor:
																"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
														}}
													/>
													<motion2.div
														className={"framer-1rzdmtd"}
														data-framer-name={"Line"}
														layoutDependency={layoutDependency}
														layoutId={"yIbHmrmdW"}
														style={{
															backgroundColor:
																"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
														}}
													/>
												</motion2.div>
											</motion2.label>
										</motion2.div>
									</motion2.div>
									<ComponentViewportProvider2
										height={85}
										width={componentViewport?.width || "100vw"}
									>
										<SmartComponentScopedContainer2
											className={"framer-1482eyo-container"}
											layoutDependency={layoutDependency}
											layoutId={"B4JvM7c7J-container"}
											nodeId={"B4JvM7c7J"}
											rendersWithMotion={true}
											scopeId={"j56o8MIl6"}
										>
											{_jsx2(stdin_default, {
												height: "100%",
												id: "B4JvM7c7J",
												layoutId: "B4JvM7c7J",
												PW51ip198: "Contact now",
												style: {
													height: "100%",
													width: "100%",
												},
												type: "submit",
												variant: formVariants(
													formState,
													{
														error: "IZDhILsNJ",
														incomplete: "WE1m0xxox",
														pending: "kPTQUtUv2",
														success: "iUviNC0GG",
													},
													"Mr9AJ_Tw9",
												),
												width: "100%",
												...addPropertyOverrides2(
													{
														hlklQp1CF: {
															PW51ip198: "Contact Now",
															variant: formVariants(
																formState,
																{
																	error: "IZDhILsNJ",
																	incomplete: "WE1m0xxox",
																	pending: "kPTQUtUv2",
																	success: "iUviNC0GG",
																},
																"D8QHjRNvR",
															),
														},
														NqlxNo9sU: {
															PW51ip198: "Contact Now",
															variant: formVariants(
																formState,
																{
																	error: "IZDhILsNJ",
																	incomplete: "WE1m0xxox",
																	pending: "kPTQUtUv2",
																	success: "iUviNC0GG",
																},
																"D8QHjRNvR",
															),
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								</_Fragment>
							)}
						</FormContainer>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css9 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BZUDS.framer-1fhuwke, .framer-BZUDS .framer-1fhuwke { display: block; }",
	".framer-BZUDS.framer-bulrf { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1600px; }",
	".framer-BZUDS .framer-9h5j1h { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-BZUDS .framer-181v4s0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 75px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 80px 0px 80px 0px; position: relative; width: 100%; }",
	".framer-BZUDS .framer-t8ltdr, .framer-BZUDS .framer-1fvzk8k { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 75px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }",
	".framer-BZUDS .framer-1de8513, .framer-BZUDS .framer-5nc9y5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-BZUDS .framer-uz2ljr, .framer-BZUDS .framer-4ckb6u, .framer-BZUDS .framer-zbvgnb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	'.framer-BZUDS .framer-1rucr3h, .framer-BZUDS .framer-175lyq8 { --framer-input-focused-border-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 0px 0px 1px 0px; --framer-input-focused-transition: all 0.3s cubic-bezier(0.44,0,0.56,1) 0s; --framer-input-font-family: "Inter Display"; --framer-input-font-letter-spacing: 0.85px; --framer-input-font-line-height: 20px; --framer-input-font-size: 18px; --framer-input-font-weight: 300; --framer-input-padding: 20px 0px 20px 0px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
	".framer-BZUDS .framer-19pbcux { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 75px; height: 250px; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }",
	".framer-BZUDS .framer-ibo0lx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-BZUDS .framer-gfb40w { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-start; min-height: 100px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	'.framer-BZUDS .framer-1ihpgm7 { --framer-input-focused-border-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 0px 0px 1px 0px; --framer-input-focused-transition: all 0.3s cubic-bezier(0.44,0,0.56,1) 0s; --framer-input-font-family: "Inter Display"; --framer-input-font-letter-spacing: 0.85px; --framer-input-font-line-height: 55px; --framer-input-font-size: 18px; --framer-input-font-weight: 300; --framer-input-padding: 1px 0px 20px 0px; --framer-input-wrapper-height: auto; flex: none; height: auto; min-height: 222px; position: relative; width: 100%; }',
	".framer-BZUDS .framer-1w2rd5o { flex: none; height: 1px; left: 1px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 58px; width: 100%; z-index: 1; }",
	".framer-BZUDS .framer-h36n55 { flex: none; height: 1px; left: 1px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 113px; width: 100%; z-index: 1; }",
	".framer-BZUDS .framer-1rzdmtd { flex: none; height: 1px; left: 1px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 168px; width: 100%; z-index: 1; }",
	".framer-BZUDS .framer-1482eyo-container { flex: none; height: 85px; position: relative; width: 100%; }",
	".framer-BZUDS.framer-v-1xnjq7s.framer-bulrf { width: 1200px; }",
	".framer-BZUDS.framer-v-1xnjq7s .framer-181v4s0 { padding: 80px 0px 60px 0px; }",
	".framer-BZUDS.framer-v-1x0nnis.framer-bulrf { width: 810px; }",
	".framer-BZUDS.framer-v-1x0nnis .framer-181v4s0 { align-content: unset; align-items: unset; display: grid; gap: 45px 40px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, minmax(0, 1fr)); justify-content: center; padding: 60px 0px 30px 0px; }",
	".framer-BZUDS.framer-v-1x0nnis .framer-t8ltdr, .framer-BZUDS.framer-v-1x0nnis .framer-1fvzk8k { align-self: start; flex: none; gap: 60px; justify-self: start; width: 100%; }",
	".framer-BZUDS.framer-v-1x0nnis .framer-19pbcux { align-self: start; flex: none; grid-column: span 2; justify-self: start; width: 100%; }",
	".framer-BZUDS.framer-v-1qz2vzl.framer-bulrf { width: 390px; }",
	".framer-BZUDS.framer-v-1qz2vzl .framer-181v4s0 { flex-direction: column; gap: 30px; padding: 40px 0px 15px 0px; }",
	".framer-BZUDS.framer-v-1qz2vzl .framer-t8ltdr, .framer-BZUDS.framer-v-1qz2vzl .framer-1fvzk8k, .framer-BZUDS.framer-v-1qz2vzl .framer-19pbcux { flex: none; gap: 30px; width: 100%; }",
	...css6,
];
var Framerj56o8MIl6 = withCSS2(Component2, css9, "framer-BZUDS");
var stdin_default2 = Framerj56o8MIl6;
Framerj56o8MIl6.displayName = "Form CTA";
Framerj56o8MIl6.defaultProps = {
	height: 515,
	width: 1600,
};
addPropertyControls2(Framerj56o8MIl6, {
	variant: {
		options: ["dl3N03XXx", "zl3wiBlhn", "NqlxNo9sU", "hlklQp1CF"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	Framerj56o8MIl6,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/MaMAn5Jp5gJg1z3VaLH65QwWPLc.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/fEqgEChcTaneQFxeugexHq7Bk.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nL7d8Ph0ViwUQorApF89PoAagQI.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/YOHXUQlY1iC2t7qT4HeLSoBDtn4.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/TfzHIi6ZmZDuhnIFGcgM6Ipuim4.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/CnMzVKZxLPB68RITfNGUfLe65m4.woff2",
					weight: "300",
				},
				{
					cssFamilyName: "Inter Display",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter Display",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/ub5XwqqEAMrXQz31ej6fNqbxnBc.woff2",
					weight: "300",
				},
			],
		},
		...ButtonForFormsFonts,
		...getFontsFromSharedStyle2(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/r5WDP1Ms7JExVZcp9FLG/IaKdRj8Td6b81vPgf2ir/uAD9AVGHQ.js
var ZipTextFonts = getFonts3(ZipText);
var FormCTAFonts = getFonts3(stdin_default2);
var cycleOrder3 = ["WCjKlnhlK", "gPVB4fQVM", "A86XK4_YX", "nQQlO7EtW"];
var serializationHash3 = "framer-QqObk";
var variantClassNames3 = {
	A86XK4_YX: "framer-v-vizu0x",
	gPVB4fQVM: "framer-v-1ni5zqh",
	nQQlO7EtW: "framer-v-hcr2cc",
	WCjKlnhlK: "framer-v-2vmqob",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3.create(React3.Fragment);
var humanReadableVariantMap3 = {
	"Wide Screen": "WCjKlnhlK",
	Laptop: "gPVB4fQVM",
	Phone: "nQQlO7EtW",
	Tablet: "A86XK4_YX",
};
var getProps3 = ({ height, id, privacyNote, subHeading, width, ...props }) => {
	return {
		...props,
		edSDmpCCE:
			privacyNote ??
			props.edSDmpCCE ??
			"Privacy note: Your data stays yours. We don\u2019t train models on client assets.",
		gW494G635: subHeading ?? props.gW494G635 ?? "Be the first",
		variant:
			humanReadableVariantMap3[props.variant] ?? props.variant ?? "WCjKlnhlK",
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		gW494G635: gW494G6352,
		edSDmpCCE: edSDmpCCE2,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "WCjKlnhlK",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [
		className3,
		className7,
		className5,
		className2,
		className4,
	];
	const scopingClassNames = cx3(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.section
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-2vmqob",
							className8,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"WCjKlnhlK"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides3(
							{
								A86XK4_YX: {
									"data-framer-name": "Tablet",
								},
								gPVB4fQVM: {
									"data-framer-name": "Laptop",
								},
								nQQlO7EtW: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion3.div
							className={"framer-1qbytu"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"q96FIpUtC"}
						>
							<motion3.div
								className={"framer-1v97ihe"}
								data-framer-name={"Heading"}
								layoutDependency={layoutDependency}
								layoutId={"b8aDa9PkL"}
							>
								<ComponentViewportProvider3>
									<SmartComponentScopedContainer3
										className={"framer-1h7m4cz-container"}
										isAuthoredByUser={true}
										layoutDependency={layoutDependency}
										layoutId={"mcYNoK1TB-container"}
										nodeId={"mcYNoK1TB"}
										rendersWithMotion={true}
										scopeId={"uAD9AVGHQ"}
									>
										<ZipText
											fitSize={0.983}
											font={{
												fontFamily:
													'"Mozilla Text", "Mozilla Text Placeholder", sans-serif',
												fontStyle: "normal",
												fontWeight: 600,
											}}
											height={"100%"}
											id={"mcYNoK1TB"}
											lastSymbolColor={
												"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))"
											}
											layoutId={"mcYNoK1TB"}
											letterSpacing={-0.054}
											offsetPx={400}
											repeatOnVisible={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											text={"Start building fairly."}
											textColor={"rgb(255, 255, 255)"}
											timeAnimation={2}
											width={"100%"}
										/>
									</SmartComponentScopedContainer3>
								</ComponentViewportProvider3>
								<motion3.div
									className={"framer-ors7uw"}
									data-framer-name={"Sub Heading"}
									layoutDependency={layoutDependency}
									layoutId={"REf7pvZ5z"}
								>
									<RichText3
										__fromCanvasComponent={true}
										className={"framer-sdipnx"}
										data-framer-name={"We reply within a day."}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"JU9SzcTE1"}
										style={{
											"--extracted-1eung3n":
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={gW494G6352}
										variants={{
											A86XK4_YX: {
												"--extracted-1w1cjl5":
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											},
											nQQlO7EtW: {
												"--extracted-1w1cjl5":
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											},
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides3(
											{
												A86XK4_YX: {
													children: (
														<React3.Fragment>
															<motion3.h6
																className={"framer-styles-preset-is1lxc"}
																data-styles-preset={"oTiNdRaJm"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																}}
															>
																{"We reply within a day"}
															</motion3.h6>
														</React3.Fragment>
													),
												},
												nQQlO7EtW: {
													children: (
														<React3.Fragment>
															<motion3.h6
																className={"framer-styles-preset-753q9u"}
																data-styles-preset={"DPlrwsrr0"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																}}
															>
																{"We reply within a day"}
															</motion3.h6>
														</React3.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React3.Fragment>
											<motion3.h4
												className={"framer-styles-preset-19084qk"}
												data-styles-preset={"D2Nj2b5ip"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"We reply within a day"}
											</motion3.h4>
										</React3.Fragment>
									</RichText3>
									<RichText3
										__fromCanvasComponent={true}
										className={"framer-atcfib"}
										data-framer-name={"Dot"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"w5C2prSZt"}
										style={{
											"--extracted-1eung3n":
												"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
											"--framer-paragraph-spacing": "0px",
										}}
										variants={{
											A86XK4_YX: {
												"--extracted-1w1cjl5":
													"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
											},
											nQQlO7EtW: {
												"--extracted-1w1cjl5":
													"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
											},
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides3(
											{
												A86XK4_YX: {
													children: (
														<React3.Fragment>
															<motion3.h6
																className={"framer-styles-preset-is1lxc"}
																data-styles-preset={"oTiNdRaJm"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1w1cjl5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																}}
															>
																{"."}
															</motion3.h6>
														</React3.Fragment>
													),
												},
												nQQlO7EtW: {
													children: (
														<React3.Fragment>
															<motion3.h6
																className={"framer-styles-preset-753q9u"}
																data-styles-preset={"DPlrwsrr0"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1w1cjl5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																}}
															>
																{"."}
															</motion3.h6>
														</React3.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React3.Fragment>
											<motion3.h4
												className={"framer-styles-preset-19084qk"}
												data-styles-preset={"D2Nj2b5ip"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
												}}
											>
												{"."}
											</motion3.h4>
										</React3.Fragment>
									</RichText3>
								</motion3.div>
							</motion3.div>
							<ComponentViewportProvider3
								height={515}
								width={`calc(min(${componentViewport?.width || "100vw"}, 1600px) - 200px)`}
								y={(componentViewport?.y || 0) + 0 + 0 + 150 + 357}
								{...addPropertyOverrides3(
									{
										A86XK4_YX: {
											width: `calc(min(${componentViewport?.width || "100vw"}, 1600px) - 60px)`,
											y: (componentViewport?.y || 0) + 0 + 0 + 100 + 241,
										},
										gPVB4fQVM: {
											y: (componentViewport?.y || 0) + 0 + 0 + 150 + 305,
										},
										nQQlO7EtW: {
											width: `calc(min(${componentViewport?.width || "100vw"}, 1600px) - 40px)`,
											y: (componentViewport?.y || 0) + 0 + 0 + 80 + 170,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer3
									className={"framer-1qadj75-container"}
									layoutDependency={layoutDependency}
									layoutId={"wAjk5XVr9-container"}
									nodeId={"wAjk5XVr9"}
									rendersWithMotion={true}
									scopeId={"uAD9AVGHQ"}
								>
									{_jsx3(stdin_default2, {
										height: "100%",
										id: "wAjk5XVr9",
										layoutId: "wAjk5XVr9",
										style: {
											width: "100%",
										},
										variant: "dl3N03XXx",
										width: "100%",
										...addPropertyOverrides3(
											{
												A86XK4_YX: {
													variant: "NqlxNo9sU",
												},
												gPVB4fQVM: {
													variant: "zl3wiBlhn",
												},
												nQQlO7EtW: {
													variant: "hlklQp1CF",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer3>
							</ComponentViewportProvider3>
							<motion3.div
								className={"framer-1kc8bmb"}
								data-framer-name={"Email"}
								layoutDependency={layoutDependency}
								layoutId={"uxQTtJeQv"}
							>
								<motion3.div
									className={"framer-18gmaoe"}
									layoutDependency={layoutDependency}
									layoutId={"ZsQ52fGNs"}
								>
									<RichText3
										__fromCanvasComponent={true}
										className={"framer-1jc73ay"}
										data-framer-name={
											"Privacy note: Your data stays yours. \u2028We don\u2019t train models on client assets."
										}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"zx0VCCvzt"}
										style={{
											"--extracted-1w3ko1f":
												"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
											"--extracted-c9yw3e":
												"var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={edSDmpCCE2}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides3(
											{
												A86XK4_YX: {
													children: (
														<React3.Fragment>
															<motion3.p
																className={"framer-styles-preset-2q46y2"}
																data-styles-preset={"TUHGD6dmV"}
																style={{
																	"--framer-text-alignment": "right",
																}}
															>
																<motion3.span
																	style={{
																		"--framer-text-color":
																			"var(--extracted-1w3ko1f, var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4)))",
																	}}
																>
																	{"Privacy note: Your data stays yours. "}
																</motion3.span>
																<motion3.br />
																<motion3.span
																	style={{
																		"--framer-text-color":
																			"var(--extracted-c9yw3e, var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4)))",
																	}}
																>
																	{
																		"We don\u2019t train models on client assets."
																	}
																</motion3.span>
															</motion3.p>
														</React3.Fragment>
													),
												},
												nQQlO7EtW: {
													children: (
														<React3.Fragment>
															<motion3.p
																className={"framer-styles-preset-2q46y2"}
																data-styles-preset={"TUHGD6dmV"}
																style={{
																	"--framer-text-alignment": "left",
																}}
															>
																<motion3.span
																	style={{
																		"--framer-text-color":
																			"var(--extracted-1w3ko1f, var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4)))",
																	}}
																>
																	{"Privacy note: Your data stays yours. "}
																</motion3.span>
																<motion3.br />
																<motion3.span
																	style={{
																		"--framer-text-color":
																			"var(--extracted-c9yw3e, var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4)))",
																	}}
																>
																	{
																		"We don\u2019t train models on client assets."
																	}
																</motion3.span>
															</motion3.p>
														</React3.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-1ud6gfb"}
												data-styles-preset={"LFTrb0jZU"}
												style={{
													"--framer-text-alignment": "right",
												}}
											>
												<motion3.span
													style={{
														"--framer-text-color":
															"var(--extracted-1w3ko1f, var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4)))",
													}}
												>
													{"Privacy note: Your data stays yours. "}
												</motion3.span>
												<motion3.br />
												<motion3.span
													style={{
														"--framer-text-color":
															"var(--extracted-c9yw3e, var(--token-44fe5c6a-e01c-44b7-9812-682da634d2bc, rgba(255, 255, 255, 0.4)))",
													}}
												>
													{"We don\u2019t train models on client assets."}
												</motion3.span>
											</motion3.p>
										</React3.Fragment>
									</RichText3>
								</motion3.div>
							</motion3.div>
						</motion3.div>
					</motion3.section>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QqObk.framer-5tmeh, .framer-QqObk .framer-5tmeh { display: block; }",
	".framer-QqObk.framer-2vmqob { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1600px; }",
	".framer-QqObk .framer-1qbytu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; max-width: 1600px; overflow: visible; padding: 150px 100px 250px 100px; position: relative; width: 100%; z-index: 3; }",
	".framer-QqObk .framer-1v97ihe { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-QqObk .framer-1h7m4cz-container { flex: none; height: 217px; position: relative; width: 100%; }",
	".framer-QqObk .framer-ors7uw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-QqObk .framer-sdipnx, .framer-QqObk .framer-atcfib { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-QqObk .framer-1qadj75-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-QqObk .framer-1kc8bmb { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 112px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-QqObk .framer-18gmaoe { align-content: flex-end; align-items: flex-end; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 1px; }",
	".framer-QqObk .framer-1jc73ay { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-QqObk.framer-v-1ni5zqh.framer-2vmqob { width: 1200px; }",
	".framer-QqObk.framer-v-1ni5zqh .framer-1qbytu { padding: 150px 100px 150px 100px; }",
	".framer-QqObk.framer-v-1ni5zqh .framer-1h7m4cz-container { height: 165px; }",
	".framer-QqObk.framer-v-vizu0x.framer-2vmqob { width: 810px; }",
	".framer-QqObk.framer-v-vizu0x .framer-1qbytu { gap: 40px; padding: 100px 30px 100px 30px; }",
	".framer-QqObk.framer-v-vizu0x .framer-1h7m4cz-container { height: 130px; }",
	".framer-QqObk.framer-v-vizu0x .framer-1kc8bmb { height: min-content; }",
	".framer-QqObk.framer-v-vizu0x .framer-18gmaoe { padding: 0px 0px 4px 0px; }",
	".framer-QqObk.framer-v-hcr2cc.framer-2vmqob { width: 390px; }",
	".framer-QqObk.framer-v-hcr2cc .framer-1qbytu { gap: 40px; padding: 80px 20px 80px 20px; }",
	".framer-QqObk.framer-v-hcr2cc .framer-1h7m4cz-container { height: 67px; }",
	".framer-QqObk.framer-v-hcr2cc .framer-1kc8bmb { flex-direction: column; gap: 20px; height: min-content; }",
	".framer-QqObk.framer-v-hcr2cc .framer-18gmaoe { flex: none; padding: 0px 0px 4px 0px; width: 100%; }",
	...css3,
	...css7,
	...css5,
	...css2,
	...css4,
];
var FrameruAD9AVGHQ = withCSS3(Component3, css10, "framer-QqObk");
var stdin_default3 = FrameruAD9AVGHQ;
FrameruAD9AVGHQ.displayName = "CTA Contact \u2013 Section";
FrameruAD9AVGHQ.defaultProps = {
	height: 1444,
	width: 1600,
};
addPropertyControls3(FrameruAD9AVGHQ, {
	variant: {
		options: ["WCjKlnhlK", "gPVB4fQVM", "A86XK4_YX", "nQQlO7EtW"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	gW494G635: {
		defaultValue: "Be the first",
		description: "For editing Big Heading please enter to Component.",
		displayTextArea: true,
		title: "Sub Heading",
		type: ControlType3.String,
	},
	edSDmpCCE: {
		defaultValue:
			"Privacy note: Your data stays yours. We don\u2019t train models on client assets.",
		displayTextArea: true,
		title: "Privacy Note",
		type: ControlType3.String,
	},
});
addFonts3(
	FrameruAD9AVGHQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Mozilla Text",
					source: "google",
					style: "normal",
					uiFamilyName: "Mozilla Text",
					url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB1sbPNVRVYmoOXo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ZipTextFonts,
		...FormCTAFonts,
		...getFontsFromSharedStyle3(fonts3),
		...getFontsFromSharedStyle3(fonts7),
		...getFontsFromSharedStyle3(fonts5),
		...getFontsFromSharedStyle3(fonts2),
		...getFontsFromSharedStyle3(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta-contact-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "nQQlO7EtW",
	md: "A86XK4_YX",
	xl: "gPVB4fQVM",
	"2xl": "WCjKlnhlK",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaContactSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var cta_contact_section_default = ComponentWithRoot;
export { cta_contact_section_default as default };
