// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Wide Screen' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * headingLine1?: string // Heading - Line 1
 * headingLine2?: string // Heading - Line 2
 * subHeading?: string // Sub Heading
 * showTip?: boolean // Show Tip
 * textOnTip?: string // Text on Tip
}} Props

 */
import {
	className as className4,
	className2 as className6,
	css as css4,
	css2 as css6,
	fonts as fonts4,
	fonts2 as fonts6,
} from "./chunks/chunk-LAYWTKXK.js";
import {
	className,
	className2,
	className3,
	css,
	css2,
	css3,
	fonts,
	fonts2,
	fonts3,
} from "./chunks/chunk-OIAVMIA7.js";
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-A5VIV4BG.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:generations-images-section
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/egt1PlFRCvsXw2zQxkoq/8VOlnAgVoC306oa2FlX7/SzRnwX2wF.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	SmartComponentScopedContainer,
	SVG as SVG2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/fNfLf66xDJHwBCuXuBaz/QdDdiq0UBZG0Fk4NvaWz/BookFlip.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import { addPropertyControls, ControlType } from "unframer";
function BookFlip(props) {
	const {
		images = [],
		pageWidth = 400,
		pageHeight = 650,
		radius = 14,
		perspective = 1300,
		maxRotDeg = 180,
		follow = 0.25,
		snapBias = 0.5,
		pxPerPage = 300,
		initialPeek = 0.12,
		tiltDeg = -3,
	} = props;
	const pairs = React.useMemo(() => {
		const out = [];
		for (let i = 0; i < images.length; i += 2) {
			const front = images[i];
			const back = images[i + 1] ?? images[i];
			if (front)
				out.push({
					front,
					back,
				});
		}
		return out;
	}, [images]);
	const [isLoading, setIsLoading] = React.useState(true);
	const stageRef = React.useRef(null);
	const bookRef = React.useRef(null);
	const pageRefs = React.useRef([]);
	const setPageRef = React.useCallback(
		(index) => (el) => {
			pageRefs.current[index] = el;
		},
		[],
	);
	const cssVars = React.useMemo(
		() => ({
			["--w"]: `${pageWidth}px`,
			["--h"]: `${pageHeight}px`,
			["--radius"]: `${radius}px`,
			["--persp"]: `${perspective}px`,
			["--tilt"]: `${tiltDeg}deg`,
		}),
		[pageWidth, pageHeight, radius, perspective, tiltDeg],
	);
	React.useEffect(() => {
		if (pairs.length === 0) {
			setIsLoading(false);
			return;
		}
		const jobs = [];
		for (const p of pairs) {
			for (const src of [p.front, p.back]) {
				const img = new Image();
				img.src = src;
				jobs.push(
					new Promise((r) => {
						img.onload = () => r();
						img.onerror = () => r();
					}),
				);
			}
		}
		Promise.all(jobs).then(() => setIsLoading(false));
	}, [pairs]);
	React.useEffect(() => {
		if (isLoading) return;
		const stage = stageRef.current;
		if (!stage) return;
		let t = 0;
		let T = initialPeek;
		const N = pairs.length;
		const MAX = (maxRotDeg * Math.PI) / 180;
		let isDown = false;
		let lastX = 0;
		let lastTime = 0;
		let velocity = 0;
		const EPSZ = 0.1;
		const LEFT_EPSZ = 2;
		const SPINE_SHIFT = -0.75;
		const H = pageHeight;
		const clamp = (x, a, b) => (x < a ? a : x > b ? b : x);
		const easeInOutCubic = (u) =>
			u < 0.5 ? 4 * u * u * u : 1 - Math.pow(-2 * u + 2, 3) / 2;
		const onDown = (e) => {
			isDown = true;
			stage.classList.add("dragging");
			lastX = e.clientX;
			lastTime = performance.now();
			velocity = 0;
			stage.setPointerCapture(e.pointerId);
			e.preventDefault();
		};
		const onMove = (e) => {
			if (!isDown) return;
			const now = performance.now();
			const dx = e.clientX - lastX;
			lastX = e.clientX;
			const dt = now - lastTime || 16;
			lastTime = now;
			velocity = dx / dt;
			T = clamp(T - dx / pxPerPage, 0, N);
			e.preventDefault();
		};
		const onUp = (e) => {
			if (!isDown) return;
			isDown = false;
			stage.classList.remove("dragging");
			try {
				stage.releasePointerCapture(e.pointerId);
			} catch {}
			const base = Math.round(T);
			let snap = base;
			const FLICK_V_TH = 9;
			if (Math.abs(velocity) > FLICK_V_TH)
				snap = clamp(base + (velocity < 0 ? 1 : -1), 0, N);
			else {
				const frac = T - Math.floor(T);
				if (frac > 1 - snapBias) snap = Math.ceil(T);
				else if (frac < snapBias) snap = Math.floor(T);
			}
			T = clamp(snap, 0, N);
		};
		stage.addEventListener("pointerdown", onDown, {
			passive: false,
		});
		stage.addEventListener("pointermove", onMove, {
			passive: false,
		});
		stage.addEventListener("pointerup", onUp, {
			passive: true,
		});
		stage.addEventListener("pointercancel", onUp, {
			passive: true,
		});
		stage.addEventListener("lostpointercapture", onUp, {
			passive: true,
		});
		let raf = 0;
		const loop = () => {
			t += (T - t) * follow;
			const lastIndex = N - 1;
			const opened = Math.min(Math.floor(t + 1e-6), lastIndex);
			const lastFully = t >= N - 1e-4;
			for (let i = 0; i < N; i++) {
				const el = pageRefs.current[i];
				if (!el) continue;
				const front = el.firstElementChild;
				const back = el.lastElementChild;
				const u = clamp(t - i, 0, 1);
				const ue = easeInOutCubic(u);
				const deg = (-ue * MAX * 180) / Math.PI;
				const inLeftStack = i < opened || (i === lastIndex && lastFully);
				let z = -EPSZ * i;
				if (inLeftStack) {
					const rank =
						i === lastIndex && lastFully ? 0 : Math.max(1, opened - i);
					z -= LEFT_EPSZ * rank;
				}
				el.style.transformOrigin = "left center";
				el.style.transform = `translate3d(${SPINE_SHIFT}px, ${-H / 2}px, ${z}px) rotateY(${deg}deg)`;
				const showBack = u >= 0.5;
				if (front) front.style.opacity = showBack ? "0" : "1";
				if (back) back.style.opacity = showBack ? "1" : "0";
				let zIndex;
				const isActive = i === opened && !lastFully;
				if (lastFully && i === lastIndex) zIndex = 4e4;
				else if (isActive) zIndex = 3e4;
				else if (inLeftStack) zIndex = 2e4 + i;
				else zIndex = 1e4 - i;
				el.style.zIndex = String(zIndex);
			}
			raf = requestAnimationFrame(loop);
		};
		raf = requestAnimationFrame(loop);
		return () => {
			cancelAnimationFrame(raf);
			stage.removeEventListener("pointerdown", onDown);
			stage.removeEventListener("pointermove", onMove);
			stage.removeEventListener("pointerup", onUp);
			stage.removeEventListener("pointercancel", onUp);
			stage.removeEventListener("lostpointercapture", onUp);
		};
	}, [
		pairs.length,
		pageHeight,
		maxRotDeg,
		follow,
		snapBias,
		pxPerPage,
		initialPeek,
		isLoading,
	]);
	return (
		<div className={"root"} style={cssVars}>
			{isLoading && (
				<div className={"preloader"}>
					<div className={"loading-text"}>{"Loading..."}</div>
				</div>
			)}
			<div
				ref={stageRef}
				className={"stage"}
				style={{
					perspective: `${perspective}px`,
					WebkitPerspective: `${perspective}px`,
					perspectiveOrigin: "50% 66%",
					WebkitPerspectiveOrigin: "50% 66%",
					opacity: isLoading ? 0 : 1,
					transition: "opacity 0.3s ease-in",
				}}
			>
				<div
					ref={bookRef}
					className={"book"}
					style={{
						height: `var(--h)`,
						transform: `rotate(${tiltDeg}deg)`,
					}}
				>
					{pairs.map((p, i) => (
						<figure key={i} className={"panel"} ref={setPageRef(i)}>
							<div className={"face front"}>
								<img
									src={p.front}
									alt={""}
									decoding={"async"}
									loading={"lazy"}
									draggable={false}
								/>
							</div>
							<div className={"face back"}>
								<img
									src={p.back}
									alt={""}
									decoding={"async"}
									loading={"lazy"}
									draggable={false}
								/>
							</div>
						</figure>
					))}
				</div>
			</div>
			<style>{`
    .root{position:relative;width:100%;height:100%;background:transparent;overflow:visible;-webkit-tap-highlight-color:transparent}
    .preloader{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:transparent;z-index:50000}
    .loading-text{font-size:1.2em;font-weight:500;color:white;letter-spacing:0.5px}

    .stage{position:absolute;inset:0;display:grid;place-items:center;user-select:none;touch-action:none;cursor:grab}
    .stage.dragging{cursor:grabbing}

    .book{
        position:relative;width:1px;
        transform-style:preserve-3d;
        -webkit-transform-style:preserve-3d;        /* \u0446\u0435\u043F\u043E\u0447\u043A\u0430 3D \u0434\u043B\u044F WebKit */
    }

    .panel{
        position:absolute;top:50%;left:50%;
        width:var(--w);height:var(--h);
        transform-style:preserve-3d;
        -webkit-transform-style:preserve-3d;
        border-radius:var(--radius);
        overflow:hidden;
        will-change:transform;
    }

    .face{position:absolute;inset:0;border-radius:var(--radius);pointer-events:none}
    .face img{display:block;width:100%;height:100%;object-fit:cover;-webkit-user-drag:none;user-select:none;pointer-events:none}
    .back{transform:rotateY(180deg) translateZ(0.02px)}

    /* --- Mobile fix: \u0440\u0435\u0430\u043B\u044C\u043D\u0430\u044F \u043F\u0435\u0440\u0441\u043F\u0435\u043A\u0442\u0438\u0432\u0430 \u0447\u0435\u0440\u0435\u0437 transform \u043D\u0430 \u043A\u043D\u0438\u0433\u0435 --- */
    @media (max-width:809px){
      /* \u0433\u0430\u0441\u0438\u043C \u043F\u0435\u0440\u0441\u043F\u0435\u043A\u0442\u0438\u0432\u0443 \u0440\u043E\u0434\u0438\u0442\u0435\u043B\u044F (inline) \u0438 \u0437\u0430\u0434\u0430\u0451\u043C \u0435\u0451 \u043D\u0430 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u0435-\u043A\u043D\u0438\u0433\u0435 */
      .stage{
        perspective:none !important;
        -webkit-perspective:none !important;
      }
      .book{
        /* \u043F\u0435\u0440\u0435\u043E\u043F\u0440\u0435\u0434\u0435\u043B\u044F\u0435\u043C \u0438\u043D\u043B\u0430\u0439\u043D-rotate: \u0434\u043E\u0431\u0430\u0432\u043B\u044F\u0435\u043C perspective(...) \u043F\u0435\u0440\u0435\u0434 rotate(...) */
        transform: perspective(var(--persp)) rotate(var(--tilt)) !important;
        -webkit-transform: perspective(var(--persp)) rotate(var(--tilt)) !important;
        transform-origin: 50% 66% !important;
        -webkit-transform-style:preserve-3d;
      }
    }
`}</style>
		</div>
	);
}
addPropertyControls(BookFlip, {
	images: {
		type: ControlType.Array,
		title: "Images",
		control: {
			type: ControlType.Image,
		},
		defaultValue: [],
	},
	pageWidth: {
		type: ControlType.Number,
		title: "Page W",
		min: 120,
		max: 1200,
		unit: "px",
		defaultValue: 400,
	},
	pageHeight: {
		type: ControlType.Number,
		title: "Page H",
		min: 160,
		max: 1600,
		unit: "px",
		defaultValue: 650,
	},
	radius: {
		type: ControlType.Number,
		title: "Radius",
		min: 0,
		max: 48,
		unit: "px",
		defaultValue: 14,
	},
	perspective: {
		type: ControlType.Number,
		title: "Perspective",
		min: 300,
		max: 3e3,
		unit: "px",
		defaultValue: 1300,
	},
	maxRotDeg: {
		type: ControlType.Number,
		title: "Max Rot",
		min: 60,
		max: 200,
		unit: "\xB0",
		defaultValue: 180,
	},
	follow: {
		type: ControlType.Number,
		title: "Follow",
		min: 0.05,
		max: 0.6,
		step: 0.01,
		defaultValue: 0.25,
	},
	snapBias: {
		type: ControlType.Number,
		title: "Snap Bias",
		min: 0.1,
		max: 0.9,
		step: 0.05,
		defaultValue: 0.5,
	},
	pxPerPage: {
		type: ControlType.Number,
		title: "Drag PX/Page",
		min: 80,
		max: 800,
		step: 10,
		defaultValue: 300,
	},
	initialPeek: {
		type: ControlType.Number,
		title: "Initial Peek",
		min: 0,
		max: 0.5,
		step: 0.01,
		defaultValue: 0.12,
	},
	tiltDeg: {
		type: ControlType.Number,
		title: "Tilt",
		min: -15,
		max: 15,
		step: 0.1,
		unit: "\xB0",
		defaultValue: -3,
	},
});

// /:https://framerusercontent.com/modules/wzj7zfo8QwtI9y6g4FRz/83hWgN1KpuDUWeB0c89T/TUHGD6dmV.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FR;InterDisplay",
	"FR;InterDisplay-Bold",
	"FR;InterDisplay-BoldItalic",
	"FR;InterDisplay-Italic",
]);
var fonts7 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/2uIBiALfCHVpWbHqRMZutfT7giU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Zwfz6xbVe5pmcWRJRgBDHnMkOkI.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/U9LaDDmbRhzX3sB8g8glTy5feTE.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tVew2LzXJ1t7QfxP1gdTIdj2o0g.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DF7bjCRmStYPqSb945lAlMfCCVQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/bHYNJqzTyl2lqvmMiRRS6Y16Es.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/vebZUMjGyKkYsfcY73iwWTzLNag.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/I11LrmuBDQZweplJ62KkVsklU5Y.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/UjFZPDy3qGuDktQM4q9CxhKfIa8.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/8exwVHJy2DhJ4N5prYlVMrEKmQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/UTeedEK21hO5jDxEUldzdScUqpg.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/Ig8B8nzy11hzIWEIYnkg91sofjo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/qITWJ2WdG0wrgQPDb8lvnYnTXDg.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/qctQFoJqJ9aIbRSIp0AhCQpFxn8.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/fXvVh2JeZlehNcEhKHpHH0frSl0.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/7pScaNeb6M7n2HF2jKemDqzCIr4.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/qS4UjQYyATcVV9rODk0Zx9KhkY8.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/VfD2n20yM7v0hrUEBHEyafsmMBY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/4oIO9fB59bn3cKFWz7piCj28z9s.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/MzumQQZJQBC6KM1omtmwOtsogtI.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/F5Lmfd3fCAu7TwiYbI4DLWw4ks.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/THWAFHoAcmqLMy81E8hCSdziVKA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/sQxGYWDlRkDr0eOKqiNRl6g5rs.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NNTAT1XAm8ZRkr824inYPkjNeL4.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/P2qr9PAWBt905929rHfxmneMUG0.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/2BmSa4TZZvFKAZg2DydxTbvKlTU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/P0JCAnd2N1Q6qwTQohre3XmQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/KMFW46iYsEZaUBwXbwPc9nQm71o.woff2",
				weight: "400",
			},
		],
	},
];
var css7 = [
	'.framer-qYUgB .framer-styles-preset-2q46y2:not(.rich-text-wrapper), .framer-qYUgB .framer-styles-preset-2q46y2.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0.5px; --framer-line-height: 18px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className7 = "framer-qYUgB";

// /:https://framerusercontent.com/modules/9mIWzeb4RXSS8p3NdROH/N3NjrWHxtId4FDIvz2To/S8c33SYvF.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/qsY8tJXvEEUOYhGVHKyk/vrLgh0VgkO6JK6uq92gW/eHmylL7z6.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts(["GF;Mozilla Text-500", "GF;Mozilla Text-700"]);
var fonts8 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Mozilla Text",
				source: "google",
				style: "normal",
				uiFamilyName: "Mozilla Text",
				url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB7ccPNVRVYmoOXo.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Mozilla Text",
				source: "google",
				style: "normal",
				uiFamilyName: "Mozilla Text",
				url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB2IbPNVRVYmoOXo.woff2",
				weight: "700",
			},
		],
	},
];
var css8 = [
	'.framer-N8mI2 .framer-styles-preset-wc63h7:not(.rich-text-wrapper), .framer-N8mI2 .framer-styles-preset-wc63h7.rich-text-wrapper h5 { --framer-font-family: "Mozilla Text", "Mozilla Text Placeholder", sans-serif; --framer-font-family-bold: "Mozilla Text", "Mozilla Text Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 34px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.5px; --framer-line-height: 40px; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className8 = "framer-N8mI2";

// /:https://framerusercontent.com/modules/9mIWzeb4RXSS8p3NdROH/N3NjrWHxtId4FDIvz2To/S8c33SYvF.js
var cycleOrder = [
	"xXrD9u5iR",
	"Cbjf6HBG2",
	"TjckuJE3n",
	"d3bH04UyF",
	"LCJjm_9gq",
	"W8N8T6INQ",
	"OT8QvgaED",
	"fXMLZeGEE",
	"Ea6DjCLYg",
	"Yw_oqMS57",
	"R4jDgdVzn",
	"X5SEuS0Kb",
];
var serializationHash = "framer-2qiEq";
var variantClassNames = {
	Cbjf6HBG2: "framer-v-1u6uxsr",
	d3bH04UyF: "framer-v-1cbfk61",
	Ea6DjCLYg: "framer-v-st5d5u",
	fXMLZeGEE: "framer-v-rdgoou",
	LCJjm_9gq: "framer-v-16clkn3",
	OT8QvgaED: "framer-v-9rd5bv",
	R4jDgdVzn: "framer-v-1kww9kr",
	TjckuJE3n: "framer-v-1nm5mx5",
	W8N8T6INQ: "framer-v-1hbjhm2",
	X5SEuS0Kb: "framer-v-yux534",
	xXrD9u5iR: "framer-v-1wituvv",
	Yw_oqMS57: "framer-v-1x4cznz",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React2.Fragment);
var humanReadableVariantMap = {
	"Left - Desktop": "xXrD9u5iR",
	"Left - Phone": "TjckuJE3n",
	"Left - Tablet": "Cbjf6HBG2",
	"Right - Desktop": "d3bH04UyF",
	"Right - Phone": "W8N8T6INQ",
	"Right - Tablet": "LCJjm_9gq",
	"White  Left  - Phone": "Ea6DjCLYg",
	"White  Left - Tablet": "fXMLZeGEE",
	"White Left - Desktop ": "OT8QvgaED",
	"White Right - Desktop": "Yw_oqMS57",
	"White Right - Phone": "X5SEuS0Kb",
	"White Right - Tablet": "R4jDgdVzn",
};
var getProps = ({ heading, height, id, showText, width, ...props }) => {
	return {
		...props,
		B4pJURn2f: showText ?? props.B4pJURn2f ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "xXrD9u5iR",
		zWunlxr_x: heading ?? props.zWunlxr_x ?? "OUR STACK",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className9,
		layoutId,
		variant,
		zWunlxr_x,
		B4pJURn2f,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "xXrD9u5iR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className5, className8, className6];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1wituvv",
							className9,
							classNames,
						)}
						data-framer-name={"Left - Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"xXrD9u5iR"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								Cbjf6HBG2: {
									"data-framer-name": "Left - Tablet",
								},
								d3bH04UyF: {
									"data-framer-name": "Right - Desktop",
								},
								Ea6DjCLYg: {
									"data-framer-name": "White  Left  - Phone",
								},
								fXMLZeGEE: {
									"data-framer-name": "White  Left - Tablet",
								},
								LCJjm_9gq: {
									"data-framer-name": "Right - Tablet",
								},
								OT8QvgaED: {
									"data-framer-name": "White Left - Desktop ",
								},
								R4jDgdVzn: {
									"data-framer-name": "White Right - Tablet",
								},
								TjckuJE3n: {
									"data-framer-name": "Left - Phone",
								},
								W8N8T6INQ: {
									"data-framer-name": "Right - Phone",
								},
								X5SEuS0Kb: {
									"data-framer-name": "White Right - Phone",
								},
								Yw_oqMS57: {
									"data-framer-name": "White Right - Desktop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1uly6uu"}
							data-framer-name={"Tech Lines - Left"}
							layoutDependency={layoutDependency}
							layoutId={"YdzwiIFR0"}
							style={{
								rotateY: 0,
							}}
							variants={{
								d3bH04UyF: {
									rotateY: 180,
								},
								Ea6DjCLYg: {
									rotateY: 0,
								},
								fXMLZeGEE: {
									rotateY: 0,
								},
								LCJjm_9gq: {
									rotateY: 180,
								},
								OT8QvgaED: {
									rotateY: 0,
								},
								R4jDgdVzn: {
									rotateY: 180,
								},
								W8N8T6INQ: {
									rotateY: 180,
								},
								X5SEuS0Kb: {
									rotateY: 180,
								},
								Yw_oqMS57: {
									rotateY: 180,
								},
							}}
						>
							<SVG
								className={"framer-pjlx8x"}
								data-framer-name={"Group"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"mJPPD3cuj"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 78 78"><path d="M 1 77 L 1 27 L 6 22" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 77 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={9390419873}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										Ea6DjCLYg: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 70 70"><path d="M 1 69 L 1 27 L 6 22" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 69 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 11357625836,
										},
										fXMLZeGEE: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 78 78"><path d="M 1 77 L 1 27 L 6 22" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 77 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 9528976854,
										},
										OT8QvgaED: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 78 78"><path d="M 1 77 L 1 27 L 6 22" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 77 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 9528976854,
										},
										R4jDgdVzn: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 78 78"><path d="M 1 77 L 1 27 L 6 22" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 77 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 9528976854,
										},
										TjckuJE3n: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 71 98"><path d="M 1 69 L 1 27 L 6 22" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 69 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 10728961068,
										},
										W8N8T6INQ: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 71 98"><path d="M 1 69 L 1 27 L 6 22" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 69 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 10728961068,
										},
										X5SEuS0Kb: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 70 70"><path d="M 1 69 L 1 27 L 6 22" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 69 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 11357625836,
										},
										Yw_oqMS57: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 78 78"><path d="M 1 77 L 1 27 L 6 22" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 77 1 L 27 1 L 22 6" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>',
											svgContentId: 9528976854,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</motion.div>
						{B4pJURn2f && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-4pw35j"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Y3vWCPU3a"}
								style={{
									"--extracted-1eung3n":
										"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={zWunlxr_x}
								variants={{
									Cbjf6HBG2: {
										"--extracted-1lwpl3i":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									Ea6DjCLYg: {
										"--extracted-1w1cjl5":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									fXMLZeGEE: {
										"--extracted-1lwpl3i":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									LCJjm_9gq: {
										"--extracted-1lwpl3i":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									R4jDgdVzn: {
										"--extracted-1lwpl3i":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									TjckuJE3n: {
										"--extracted-1w1cjl5":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									W8N8T6INQ: {
										"--extracted-1w1cjl5":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
									X5SEuS0Kb: {
										"--extracted-1w1cjl5":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										Cbjf6HBG2: {
											children: (
												<React2.Fragment>
													<motion.h5
														className={"framer-styles-preset-wc63h7"}
														data-styles-preset={"eHmylL7z6"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h5>
												</React2.Fragment>
											),
										},
										d3bH04UyF: {
											children: (
												<React2.Fragment>
													<motion.h4
														className={"framer-styles-preset-19084qk"}
														data-styles-preset={"D2Nj2b5ip"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-1eung3n, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h4>
												</React2.Fragment>
											),
										},
										Ea6DjCLYg: {
											children: (
												<React2.Fragment>
													<motion.h6
														className={"framer-styles-preset-is1lxc"}
														data-styles-preset={"oTiNdRaJm"}
														style={{
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h6>
												</React2.Fragment>
											),
										},
										fXMLZeGEE: {
											children: (
												<React2.Fragment>
													<motion.h5
														className={"framer-styles-preset-wc63h7"}
														data-styles-preset={"eHmylL7z6"}
														style={{
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h5>
												</React2.Fragment>
											),
										},
										LCJjm_9gq: {
											children: (
												<React2.Fragment>
													<motion.h5
														className={"framer-styles-preset-wc63h7"}
														data-styles-preset={"eHmylL7z6"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h5>
												</React2.Fragment>
											),
										},
										R4jDgdVzn: {
											children: (
												<React2.Fragment>
													<motion.h5
														className={"framer-styles-preset-wc63h7"}
														data-styles-preset={"eHmylL7z6"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-1lwpl3i, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h5>
												</React2.Fragment>
											),
										},
										TjckuJE3n: {
											children: (
												<React2.Fragment>
													<motion.h6
														className={"framer-styles-preset-is1lxc"}
														data-styles-preset={"oTiNdRaJm"}
														style={{
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h6>
												</React2.Fragment>
											),
										},
										W8N8T6INQ: {
											children: (
												<React2.Fragment>
													<motion.h6
														className={"framer-styles-preset-is1lxc"}
														data-styles-preset={"oTiNdRaJm"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h6>
												</React2.Fragment>
											),
										},
										X5SEuS0Kb: {
											children: (
												<React2.Fragment>
													<motion.h6
														className={"framer-styles-preset-is1lxc"}
														data-styles-preset={"oTiNdRaJm"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h6>
												</React2.Fragment>
											),
										},
										Yw_oqMS57: {
											children: (
												<React2.Fragment>
													<motion.h4
														className={"framer-styles-preset-19084qk"}
														data-styles-preset={"D2Nj2b5ip"}
														style={{
															"--framer-text-alignment": "right",
															"--framer-text-color":
																"var(--extracted-1eung3n, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
														}}
													>
														{"OUR STACK"}
													</motion.h4>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion.h4
										className={"framer-styles-preset-19084qk"}
										data-styles-preset={"D2Nj2b5ip"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
										}}
									>
										{"OUR STACK"}
									</motion.h4>
								</React2.Fragment>
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css9 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-2qiEq.framer-1c46q6s, .framer-2qiEq .framer-1c46q6s { display: block; }",
	".framer-2qiEq.framer-1wituvv { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 65px; height: min-content; justify-content: center; overflow: visible; padding: 42px 0px 0px 42px; position: relative; width: 500px; }",
	".framer-2qiEq .framer-1uly6uu { flex: none; height: 78px; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: 0px; width: 78px; z-index: 1; }",
	".framer-2qiEq .framer-pjlx8x { flex: none; height: 78px; left: calc(50.00000000000002% - 78px / 2); position: absolute; top: calc(50.00000000000002% - 78px / 2); width: 78px; }",
	".framer-2qiEq .framer-4pw35j { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-2qiEq.framer-v-1nm5mx5.framer-1wituvv, .framer-2qiEq.framer-v-st5d5u.framer-1wituvv { padding: 42px 0px 0px 37px; }",
	".framer-2qiEq.framer-v-1nm5mx5 .framer-1uly6uu, .framer-2qiEq.framer-v-st5d5u .framer-1uly6uu { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 78px); }",
	".framer-2qiEq.framer-v-1nm5mx5 .framer-pjlx8x { height: 98px; left: calc(44.8717948717949% - 71px / 2); top: calc(62.82051282051284% - 98px / 2); width: 71px; }",
	".framer-2qiEq.framer-v-1cbfk61.framer-1wituvv, .framer-2qiEq.framer-v-16clkn3.framer-1wituvv, .framer-2qiEq.framer-v-1hbjhm2.framer-1wituvv, .framer-2qiEq.framer-v-1x4cznz.framer-1wituvv, .framer-2qiEq.framer-v-1kww9kr.framer-1wituvv, .framer-2qiEq.framer-v-yux534.framer-1wituvv { padding: 42px 45px 0px 0px; }",
	".framer-2qiEq.framer-v-1cbfk61 .framer-1uly6uu, .framer-2qiEq.framer-v-16clkn3 .framer-1uly6uu, .framer-2qiEq.framer-v-1hbjhm2 .framer-1uly6uu, .framer-2qiEq.framer-v-1x4cznz .framer-1uly6uu, .framer-2qiEq.framer-v-1kww9kr .framer-1uly6uu, .framer-2qiEq.framer-v-yux534 .framer-1uly6uu { left: unset; right: 0px; }",
	".framer-2qiEq.framer-v-1hbjhm2 .framer-pjlx8x { height: 71px; left: calc(44.8717948717949% - 70px / 2); top: calc(44.8717948717949% - 71px / 2); width: 70px; }",
	".framer-2qiEq.framer-v-st5d5u .framer-pjlx8x, .framer-2qiEq.framer-v-yux534 .framer-pjlx8x { height: 70px; left: calc(44.8717948717949% - 70px / 2); top: calc(44.8717948717949% - 70px / 2); width: 70px; }",
	...css5,
	...css8,
	...css6,
];
var FramerS8c33SYvF = withCSS(Component, css9, "framer-2qiEq");
var stdin_default = FramerS8c33SYvF;
FramerS8c33SYvF.displayName = "Small Heading with Lines";
FramerS8c33SYvF.defaultProps = {
	height: 82,
	width: 500,
};
addPropertyControls2(FramerS8c33SYvF, {
	variant: {
		options: [
			"xXrD9u5iR",
			"Cbjf6HBG2",
			"TjckuJE3n",
			"d3bH04UyF",
			"LCJjm_9gq",
			"W8N8T6INQ",
			"OT8QvgaED",
			"fXMLZeGEE",
			"Ea6DjCLYg",
			"Yw_oqMS57",
			"R4jDgdVzn",
			"X5SEuS0Kb",
		],
		optionTitles: [
			"Left - Desktop",
			"Left - Tablet",
			"Left - Phone",
			"Right - Desktop",
			"Right - Tablet",
			"Right - Phone",
			"White Left - Desktop ",
			"White  Left - Tablet",
			"White  Left  - Phone",
			"White Right - Desktop",
			"White Right - Tablet",
			"White Right - Phone",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	zWunlxr_x: {
		defaultValue: "OUR STACK",
		displayTextArea: false,
		title: "Heading",
		type: ControlType2.String,
	},
	B4pJURn2f: {
		defaultValue: true,
		title: "Show Text",
		type: ControlType2.Boolean,
	},
});
addFonts(
	FramerS8c33SYvF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/egt1PlFRCvsXw2zQxkoq/8VOlnAgVoC306oa2FlX7/SzRnwX2wF.js
var SmallHeadingWithLinesFonts = getFonts(stdin_default);
var BookFlipFonts = getFonts(BookFlip);
var cycleOrder2 = ["y3lJTdmqW", "qJwn7mn1e", "vm6P_s6xC", "XHtTc0LUO"];
var serializationHash2 = "framer-Bk1Dr";
var variantClassNames2 = {
	qJwn7mn1e: "framer-v-18r0f5c",
	vm6P_s6xC: "framer-v-1cp6mtq",
	XHtTc0LUO: "framer-v-zy3pbn",
	y3lJTdmqW: "framer-v-1a92xhf",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React3.Fragment);
var humanReadableVariantMap2 = {
	"Wide Screen": "y3lJTdmqW",
	Laptop: "qJwn7mn1e",
	Phone: "XHtTc0LUO",
	Tablet: "vm6P_s6xC",
};
var getProps2 = ({
	headingLine1,
	headingLine2,
	height,
	id,
	showTip,
	subHeading,
	textOnTip,
	width,
	...props
}) => {
	return {
		...props,
		bzO1HIDvx: subHeading ?? props.bzO1HIDvx ?? "TYPES OF BIAS",
		L9xrqinvs: showTip ?? props.L9xrqinvs ?? true,
		s_xP1aLMD: headingLine2 ?? props.s_xP1aLMD ?? "Catch",
		sc5qVIRJL: headingLine1 ?? props.sc5qVIRJL ?? "What We",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "y3lJTdmqW",
		wkje9vCwU: textOnTip ?? props.wkje9vCwU ?? "Drag for Flip Pages",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className9,
		layoutId,
		variant,
		sc5qVIRJL: sc5qVIRJL2,
		s_xP1aLMD: s_xP1aLMD2,
		bzO1HIDvx: bzO1HIDvx2,
		L9xrqinvs: L9xrqinvs2,
		wkje9vCwU: wkje9vCwU2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "y3lJTdmqW",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [
		className2,
		className,
		className4,
		className3,
		className7,
	];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1a92xhf",
							className9,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"y3lJTdmqW"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, rgb(0, 0, 0) 40%, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) 100%)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								qJwn7mn1e: {
									"data-framer-name": "Laptop",
								},
								vm6P_s6xC: {
									"data-framer-name": "Tablet",
								},
								XHtTc0LUO: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1tz02r8"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"vEupR9ARH"}
						>
							<motion2.div
								className={"framer-4pruwk"}
								data-framer-name={"Heading"}
								layoutDependency={layoutDependency}
								layoutId={"YkYiWAWlp"}
							>
								<motion2.div
									className={"framer-1r4rvwl"}
									layoutDependency={layoutDependency}
									layoutId={"CBXEtnyIc"}
								>
									<motion2.div
										className={"framer-9bdhfk"}
										layoutDependency={layoutDependency}
										layoutId={"K9KrgFhve"}
									>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-zszamf"}
											data-framer-name={"Line 1"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"eldFewon8"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={sc5qVIRJL2}
											variants={{
												vm6P_s6xC: {
													"--extracted-1k2zljd":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
												XHtTc0LUO: {
													"--extracted-1wi65aa":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides2(
												{
													vm6P_s6xC: {
														children: (
															<React3.Fragment>
																<motion2.h3
																	className={"framer-styles-preset-wvy7ez"}
																	data-styles-preset={"hdCs32bmG"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion2.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1k2zljd, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"Our generations"}
																	</motion2.span>
																</motion2.h3>
															</React3.Fragment>
														),
													},
													XHtTc0LUO: {
														children: (
															<React3.Fragment>
																<motion2.h4
																	className={"framer-styles-preset-19084qk"}
																	data-styles-preset={"D2Nj2b5ip"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion2.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1wi65aa, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"Our generations"}
																	</motion2.span>
																</motion2.h4>
															</React3.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React3.Fragment>
												<motion2.h2
													className={"framer-styles-preset-ep0jra"}
													data-styles-preset={"hZ8usl_26"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
													}}
												>
													{"Our generations"}
												</motion2.h2>
											</React3.Fragment>
										</RichText2>
									</motion2.div>
									<motion2.div
										className={"framer-1iu28c5"}
										layoutDependency={layoutDependency}
										layoutId={"Ch6XKanJs"}
									>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-15u5ai8"}
											data-framer-name={"Line 2"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"Ex5EwJcrE"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={s_xP1aLMD2}
											variants={{
												vm6P_s6xC: {
													"--extracted-1k2zljd":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
												XHtTc0LUO: {
													"--extracted-1wi65aa":
														"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides2(
												{
													vm6P_s6xC: {
														children: (
															<React3.Fragment>
																<motion2.h3
																	className={"framer-styles-preset-wvy7ez"}
																	data-styles-preset={"hdCs32bmG"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion2.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1k2zljd, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"with AI"}
																	</motion2.span>
																</motion2.h3>
															</React3.Fragment>
														),
													},
													XHtTc0LUO: {
														children: (
															<React3.Fragment>
																<motion2.h4
																	className={"framer-styles-preset-19084qk"}
																	data-styles-preset={"D2Nj2b5ip"}
																	style={{
																		"--framer-text-alignment": "left",
																	}}
																>
																	<motion2.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1wi65aa, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																		}}
																	>
																		{"with AI"}
																	</motion2.span>
																</motion2.h4>
															</React3.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React3.Fragment>
												<motion2.h2
													className={"framer-styles-preset-ep0jra"}
													data-styles-preset={"hZ8usl_26"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
													}}
												>
													{"with AI"}
												</motion2.h2>
											</React3.Fragment>
										</RichText2>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-1q2coik"}
											data-framer-name={"Dot"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"GizGLEStI"}
											style={{
												"--extracted-1of0zx5":
													"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
												"--framer-paragraph-spacing": "0px",
											}}
											variants={{
												vm6P_s6xC: {
													"--extracted-a0htzi":
														"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
												},
												XHtTc0LUO: {
													"--extracted-1eung3n":
														"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides2(
												{
													vm6P_s6xC: {
														children: (
															<React3.Fragment>
																<motion2.h3
																	className={"framer-styles-preset-wvy7ez"}
																	data-styles-preset={"hdCs32bmG"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-a0htzi, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																	}}
																>
																	{"."}
																</motion2.h3>
															</React3.Fragment>
														),
													},
													XHtTc0LUO: {
														children: (
															<React3.Fragment>
																<motion2.h4
																	className={"framer-styles-preset-19084qk"}
																	data-styles-preset={"D2Nj2b5ip"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-1eung3n, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																	}}
																>
																	{"."}
																</motion2.h4>
															</React3.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React3.Fragment>
												<motion2.h2
													className={"framer-styles-preset-ep0jra"}
													data-styles-preset={"hZ8usl_26"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-1of0zx5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
													}}
												>
													{"."}
												</motion2.h2>
											</React3.Fragment>
										</RichText2>
									</motion2.div>
								</motion2.div>
								<ComponentViewportProvider
									height={82}
									y={(componentViewport?.y || 0) + 0 + 0 + 250 + 0 + 0 + 88}
									{...addPropertyOverrides2(
										{
											qJwn7mn1e: {
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													150 +
													0 +
													0 +
													88,
											},
											vm6P_s6xC: {
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													100 +
													0 +
													0 +
													32,
											},
											XHtTc0LUO: {
												width: `calc(min(${componentViewport?.width || "100vw"}, 1600px) - 40px)`,
												y:
													(componentViewport?.y || 0) +
													0 +
													0 +
													80 +
													0 +
													0 +
													125,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-xy45vh-container"}
										layoutDependency={layoutDependency}
										layoutId={"OF3jGzRlr-container"}
										nodeId={"OF3jGzRlr"}
										rendersWithMotion={true}
										scopeId={"SzRnwX2wF"}
									>
										{_jsx3(stdin_default, {
											B4pJURn2f: true,
											height: "100%",
											id: "OF3jGzRlr",
											layoutId: "OF3jGzRlr",
											style: {
												width: "100%",
											},
											variant: "d3bH04UyF",
											width: "100%",
											zWunlxr_x: bzO1HIDvx2,
											...addPropertyOverrides2(
												{
													vm6P_s6xC: {
														variant: "LCJjm_9gq",
													},
													XHtTc0LUO: {
														variant: "TjckuJE3n",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
							<motion2.div
								className={"framer-euvoyh"}
								data-framer-name={"Spacer"}
								layoutDependency={layoutDependency}
								layoutId={"NdjMRu_Lt"}
							/>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1sw10rg-container"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"N0C4ftZ4T-container"}
									nodeId={"N0C4ftZ4T"}
									rendersWithMotion={true}
									scopeId={"SzRnwX2wF"}
								>
									<BookFlip
										follow={0.25}
										height={"100%"}
										id={"N0C4ftZ4T"}
										images={[
											"https://framerusercontent.com/images/JOOrxOegRU6lmIGqqdrIc41W8NA.jpg?width=1024&height=1024",
											"https://framerusercontent.com/images/24QQu3tO5enbxFfnCyIunHUPGcI.png?width=804&height=1174",
											"https://framerusercontent.com/images/qYb0YBaSiPsFMvWfXFCBm0ltHw.png?width=960&height=1404",
											"https://framerusercontent.com/images/LojrFdcsw46oWF5w7zsy1tEs.png?width=964&height=1412",
											"https://framerusercontent.com/images/pmvCfT8cd9uQYGM4Ki7xCsI.png?width=808&height=1188",
											"https://framerusercontent.com/images/K3mOvv5bUlD6aGcRPzMXnknwQaw.jpg?width=1040&height=1384",
											"https://framerusercontent.com/images/9KH9CetWeBCCAOZr0UCVuTCIGhU.jpg?width=1040&height=1384",
											"https://framerusercontent.com/images/HmSmAWnd5TWWz8ziekZZkT10OQ.jpg?width=1040&height=1384",
											"https://framerusercontent.com/images/VeeL22OSboQXlkYl4t5obo9GC1w.png?width=1040&height=1384",
										]}
										initialPeek={0.4}
										layoutId={"N0C4ftZ4T"}
										maxRotDeg={180}
										pageHeight={650}
										pageWidth={400}
										perspective={1300}
										pxPerPage={300}
										radius={14}
										snapBias={0.5}
										style={{
											height: "100%",
											width: "100%",
										}}
										tiltDeg={-3}
										width={"100%"}
										{...addPropertyOverrides2(
											{
												qJwn7mn1e: {
													pageHeight: 570,
													pageWidth: 350,
												},
												vm6P_s6xC: {
													pageHeight: 512,
													pageWidth: 315,
												},
												XHtTc0LUO: {
													pageHeight: 280,
													pageWidth: 170,
													perspective: 786,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							{L9xrqinvs2 !== false && (
								<motion2.div
									className={"framer-d8nygx"}
									data-framer-name={"Tip"}
									layoutDependency={layoutDependency}
									layoutId={"BaZH5yn5R"}
								>
									<SVG2
										className={"framer-cseopw"}
										data-framer-name={"Drag"}
										fill={
											'var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {"name":"White"} */'
										}
										intrinsicHeight={22}
										intrinsicWidth={25}
										layoutDependency={layoutDependency}
										layoutId={"FMwwSYMh2"}
										svg={
											'<svg width="25" height="22" viewBox="0 0 25 22" fill="none" xmlns="http://www.w3.org/2000/svg">\n<g clip-path="url(#clip0_50_56)">\n<path d="M11.0297 20.6582L14.2022 20.6582C19.5311 20.6582 23.8511 16.3382 23.8511 11.0093C23.8511 5.68032 19.5311 1.36035 14.2021 1.36035L11.0297 1.36035C5.70073 1.36035 1.38077 5.68032 1.38077 11.0093C1.38077 16.3382 5.70074 20.6582 11.0297 20.6582Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M15.7054 7.60449L19.0759 11.01L15.7054 14.4155" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M9.46997 7.60449L6.09943 11.01L9.46997 14.4155" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M19.0759 11.0112L6.09933 11.0112" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</g>\n<defs>\n<clipPath id="clip0_50_56">\n<rect width="22" height="25" fill="white" transform="translate(25 1.09278e-06) rotate(90)"/>\n</clipPath>\n</defs>\n</svg>\n'
										}
										withExternalLayout={true}
									/>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-v9670w"}
										data-framer-name={"Drag for flip pages."}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SjMZv5Owm"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={wkje9vCwU2}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												XHtTc0LUO: {
													children: (
														<React3.Fragment>
															<motion2.p
																className={"framer-styles-preset-2q46y2"}
																data-styles-preset={"TUHGD6dmV"}
																style={{
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																}}
															>
																{"Drag for Flip Pages"}
															</motion2.p>
														</React3.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React3.Fragment>
											<motion2.p
												className={"framer-styles-preset-1ud6gfb"}
												data-styles-preset={"LFTrb0jZU"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"Drag for flip pages."}
											</motion2.p>
										</React3.Fragment>
									</RichText2>
								</motion2.div>
							)}
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Bk1Dr.framer-1d188xl, .framer-Bk1Dr .framer-1d188xl { display: block; }",
	".framer-Bk1Dr.framer-1a92xhf { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1600px; }",
	".framer-Bk1Dr .framer-1tz02r8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; max-width: 1600px; overflow: visible; padding: 250px 100px 150px 100px; position: relative; width: 100%; z-index: 3; }",
	".framer-Bk1Dr .framer-4pruwk { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 5; }",
	".framer-Bk1Dr .framer-1r4rvwl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-9bdhfk { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-zszamf, .framer-Bk1Dr .framer-15u5ai8, .framer-Bk1Dr .framer-1q2coik, .framer-Bk1Dr .framer-v9670w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Bk1Dr .framer-1iu28c5 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-xy45vh-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-Bk1Dr .framer-euvoyh { flex: none; height: 95px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
	".framer-Bk1Dr .framer-1sw10rg-container { flex: none; height: 750px; position: relative; width: 100%; }",
	".framer-Bk1Dr .framer-d8nygx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-Bk1Dr .framer-cseopw { flex: none; height: 22px; position: relative; width: 25px; }",
	".framer-Bk1Dr.framer-v-18r0f5c.framer-1a92xhf { width: 1200px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-1tz02r8 { padding: 150px 100px 150px 100px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-4pruwk, .framer-Bk1Dr.framer-v-1cp6mtq .framer-4pruwk { gap: 10px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-euvoyh { height: 25px; }",
	".framer-Bk1Dr.framer-v-18r0f5c .framer-1sw10rg-container { height: 710px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq.framer-1a92xhf { width: 810px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq .framer-1tz02r8 { padding: 100px 30px 100px 30px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq .framer-euvoyh { height: 20px; }",
	".framer-Bk1Dr.framer-v-1cp6mtq .framer-1sw10rg-container { height: 625px; }",
	".framer-Bk1Dr.framer-v-zy3pbn.framer-1a92xhf { width: 390px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-1tz02r8 { gap: 14px; padding: 80px 20px 80px 20px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-4pruwk { align-content: flex-start; align-items: flex-start; flex-direction: column; gap: 35px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-xy45vh-container { flex: none; width: 100%; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-euvoyh { height: 21px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-1sw10rg-container { height: 344px; }",
	".framer-Bk1Dr.framer-v-zy3pbn .framer-cseopw { aspect-ratio: 1.1363636363636365 / 1; height: var(--framer-aspect-ratio-supported, 22px); }",
	...css2,
	...css,
	...css4,
	...css3,
	...css7,
];
var FramerSzRnwX2wF = withCSS2(Component2, css10, "framer-Bk1Dr");
var stdin_default2 = FramerSzRnwX2wF;
FramerSzRnwX2wF.displayName = "Generations \u2013 Images \u2013 Section";
FramerSzRnwX2wF.defaultProps = {
	height: 1532,
	width: 1600,
};
addPropertyControls3(FramerSzRnwX2wF, {
	variant: {
		options: ["y3lJTdmqW", "qJwn7mn1e", "vm6P_s6xC", "XHtTc0LUO"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	sc5qVIRJL: {
		defaultValue: "What We",
		displayTextArea: false,
		title: "Heading - Line 1",
		type: ControlType3.String,
	},
	s_xP1aLMD: {
		defaultValue: "Catch",
		displayTextArea: false,
		title: "Heading - Line 2",
		type: ControlType3.String,
	},
	bzO1HIDvx: {
		defaultValue: "TYPES OF BIAS",
		displayTextArea: false,
		title: "Sub Heading",
		type: ControlType3.String,
	},
	L9xrqinvs: {
		defaultValue: true,
		title: "Show Tip",
		type: ControlType3.Boolean,
	},
	wkje9vCwU: {
		defaultValue: "Drag for Flip Pages",
		displayTextArea: false,
		title: "Text on Tip",
		type: ControlType3.String,
	},
});
addFonts2(
	FramerSzRnwX2wF,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...SmallHeadingWithLinesFonts,
		...BookFlipFonts,
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts4),
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts7),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:generations-images-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "XHtTc0LUO",
	md: "vm6P_s6xC",
	xl: "qJwn7mn1e",
	"2xl": "y3lJTdmqW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GenerationsImagesSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var generations_images_section_default = ComponentWithRoot;
export { generations_images_section_default as default };
