// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * slogan?: string // Slogan
 * logo?: undefined // Logo
 * morphImage1?: {src: string, srcSet?: string, alt?: string} // Morph Image 1
 * morphImage2?: {src: string, srcSet?: string, alt?: string} // Morph Image 2
 * link1?: string // Link 1
 * link1URL?: string // Link 1 URL
 * link2?: string // Link 2
 * link2URL?: string // Link 2 URL
 * link3?: string // Link 3
 * link3URL?: string // Link 3 URL
 * link4?: string // Link 4
 * link4URL?: string // Link 4 URL
 * link5?: string // Link 5
 * link5URL?: string // Link 5 URL
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-WYS5NP55.js";
import { withHiTechFlash } from "./chunks/chunk-LCWP3OBU.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-LVJPX2QD.js";
import { className, css, fonts } from "./chunks/chunk-PNSODGZQ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-K7JSNEXQ.js";
import { MorphGPU } from "./chunks/chunk-JVIGOZPP.js";
import { stdin_default } from "./chunks/chunk-T32UZO2S.js";
import "./chunks/chunk-TIIIDNES.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-AJJW5VRX.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:hero-section
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/blaobUprRuRNudFlxytE/2oUGdtpbM7qjwPubECR1/TWoStnPJs.js
import { jsx as _jsx4, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Instance,
	RichText,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCodeBoundaryForOverrides,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion4,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/6ytY0wvjgOlpbVu2UHhn/CEs8wt9qihtqzogQIQZB/NWySovwm6.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Mozilla Text-500", "GF;Mozilla Text-700"]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Mozilla Text",
				source: "google",
				style: "normal",
				uiFamilyName: "Mozilla Text",
				url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB7ccPNVRVYmoOXo.woff2",
				weight: "500",
			},
			{
				cssFamilyName: "Mozilla Text",
				source: "google",
				style: "normal",
				uiFamilyName: "Mozilla Text",
				url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB2IbPNVRVYmoOXo.woff2",
				weight: "700",
			},
		],
	},
];
var css4 = [
	'.framer-90xDb .framer-styles-preset-gwdmae:not(.rich-text-wrapper), .framer-90xDb .framer-styles-preset-gwdmae.rich-text-wrapper h1 { --framer-font-family: "Mozilla Text", "Mozilla Text Placeholder", sans-serif; --framer-font-family-bold: "Mozilla Text", "Mozilla Text Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 102px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-letter-spacing: -3.25px; --framer-line-height: 100px; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className4 = "framer-90xDb";

// /:https://framerusercontent.com/modules/we51sIebI935hWkVpdE4/6Rrb5wGE3gNFEkCSbPRM/GjycoNqfh.js
import { jsx as _jsx } from "react/jsx-runtime";
import { cx, motion, withCSS } from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 75 78" xmlns="http://www.w3.org/2000/svg"><path d="M 37.575 78 C 30.507 78 24.091 76.334 18.336 73.002 C 12.678 69.569 8.183 64.924 4.849 59.068 C 1.619 53.111 0 46.447 0 39.076 C 0 31.604 1.619 24.94 4.849 19.084 C 8.183 13.126 12.678 8.482 18.336 5.15 C 24.091 1.717 30.507 0 37.575 0 C 44.747 0 51.11 1.717 56.668 5.15 C 62.322 8.482 66.768 13.126 69.998 19.084 C 73.333 24.94 75 31.604 75 39.076 C 75 46.447 73.333 53.111 69.998 59.068 C 66.768 64.924 62.322 69.569 56.668 73.002 C 51.11 76.334 44.747 78 37.575 78 Z M 43.486 59.22 L 36.817 41.196 L 46.515 39.985 L 54.545 59.22 Z M 37.575 70.73 C 46.567 70.73 53.736 67.953 59.088 62.4 C 64.545 56.746 67.272 49.223 67.272 39.833 L 67.272 38.016 C 67.272 28.625 64.545 21.153 59.088 15.6 C 53.736 10.047 46.567 7.27 37.575 7.27 C 28.586 7.27 21.365 10.047 15.912 15.6 C 10.555 21.153 7.881 28.625 7.881 38.016 L 7.881 39.833 C 7.881 49.223 10.555 56.746 15.912 62.4 C 21.365 67.953 28.586 70.73 37.575 70.73 Z M 22.577 59.22 L 22.577 18.781 L 39.242 18.781 C 43.889 18.781 47.474 19.942 49.999 22.264 C 52.625 24.485 53.937 27.666 53.937 31.806 C 53.937 35.744 52.677 38.824 50.152 41.045 C 47.627 43.165 44.091 44.225 39.544 44.225 L 32.879 44.225 L 32.879 59.22 Z M 32.73 37.258 L 38.94 37.258 C 42.069 37.258 43.636 35.794 43.636 32.866 L 43.636 31.049 C 43.636 28.019 42.069 26.505 38.94 26.505 L 32.73 26.505 Z" fill="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))" height="78px" id="P9ZAJl1Qq" width="75px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-X9Yd3", className5)}
			layoutId={layoutId}
			ref={ref}
			style={{
				...style,
			}}
		/>
	);
});
var css5 = [
	`.framer-X9Yd3 { -webkit-mask: ${mask}; aspect-ratio: 0.9615384615384616; background-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); mask: ${mask}; width: 75px; }`,
];
var Icon = withCSS(Component, css5, "framer-X9Yd3");
Icon.displayName = "(R)";
var stdin_default4 = Icon;

// /:https://framerusercontent.com/modules/l4tfa3wN5cqPeXN1q7ta/WeoxYdYioSjsrXjuwX5s/Fwuwh3EWM.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/8wVw8lP0JcVvbuAwmJFA/07zxay8zJ7CPzxM1CSwb/TextRandom.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import * as React2 from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { motion as motion2, useAnimationControls } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
function buildIndices(len) {
	const a = new Uint16Array(len);
	for (let i = 0; i < len; i++) a[i] = i;
	return a;
}
function shuffleIndices(indices) {
	for (let i = indices.length - 1; i > 0; i--) {
		const j = (Math.random() * (i + 1)) | 0;
		const t = indices[i];
		indices[i] = indices[j];
		indices[j] = t;
	}
}
function easePortion(t, mode) {
	if (mode === "linear") return t;
	if (mode === "out") return 1 - Math.pow(1 - t, 3);
	return t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
}
function readFamily(f, fb) {
	if (!f || typeof f !== "object") return fb;
	return f.fontFamily || f.family || fb;
}
function readWeight(f, fb) {
	if (!f || typeof f !== "object") return fb;
	const v = f.fontWeight ?? f.weight ?? f.variant;
	const n = Number(v);
	return Number.isFinite(n) ? n : fb;
}
function readAlign(f, fb) {
	if (!f || typeof f !== "object") return fb;
	const a = f.textAlign || f.align;
	return a === "center" || a === "right" ? a : "left";
}
function readStringOrFallback(f, key, fb) {
	if (!f || typeof f !== "object") return fb;
	const v = f[key];
	return typeof v === "string" || typeof v === "number" ? String(v) : fb;
}
function extractHref(link) {
	if (!link) return null;
	if (typeof link === "string") return link.trim() || null;
	if (typeof link === "object") {
		const url = link.url ?? link.href ?? link.target ?? "";
		return url || null;
	}
	return null;
}
function openLink(href, newTab) {
	if (!href || typeof __unframerWindow === "undefined") return;
	try {
		const abs = new URL(href, __unframerWindow.location.href).toString();
		newTab
			? __unframerWindow.open(abs, "_blank", "noopener,noreferrer")
			: __unframerWindow.location.assign(abs);
	} catch (e) {
		console.warn("Invalid link:", href, e);
	}
}
function TextRandom(props) {
	const {
		text = "Hover to decode",
		font,
		color = "#111",
		link,
		newTab = true,
		ariaLabel,
		durationMs = 900,
		fps = 30,
		revealEase = "out",
		intensity = 1,
		charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%*",
		hoverOnly = true,
		repeatOnHover = true,
		repeatOnEnter = false,
		repeatAfterMs = 0,
		style = {},
	} = props;
	const family = React2.useMemo(
		() =>
			readFamily(
				font,
				"Inter, system-ui, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
			),
		[font],
	);
	const weight = React2.useMemo(() => readWeight(font, 600), [font]);
	const fontSize = React2.useMemo(
		() => readStringOrFallback(font, "fontSize", "18px"),
		[font],
	);
	const lineHeight = React2.useMemo(
		() => readStringOrFallback(font, "lineHeight", "1.1"),
		[font],
	);
	const letterSpacing = React2.useMemo(
		() => readStringOrFallback(font, "letterSpacing", "0px"),
		[font],
	);
	const textAlign = React2.useMemo(() => readAlign(font, "left"), [font]);
	const href = React2.useMemo(() => extractHref(link), [link]);
	const [display, setDisplay] = React2.useState(text);
	const anim = useAnimationControls();
	const base = React2.useMemo(() => text, [text]);
	const maxLen = React2.useMemo(() => base.length, [base]);
	const indices = React2.useMemo(() => buildIndices(maxLen), [maxLen]);
	const chars = React2.useMemo(() => charset.split(""), [charset]);
	React2.useEffect(() => {
		if (!runningRef.current) setDisplay(base);
	}, [base]);
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const runningRef = React2.useRef(false);
	const frameRef = React2.useRef(null);
	const runScramble = React2.useCallback(() => {
		if (runningRef.current) return;
		runningRef.current = true;
		const total = Math.max(1, Math.round((durationMs / 1e3) * fps));
		const revealPerFrame = new Array(total);
		for (let f = 0; f < total; f++)
			revealPerFrame[f] = easePortion((f + 1) / total, revealEase);
		const baseChars = base.split("");
		const work = new Array(maxLen);
		const order = new Uint16Array(indices);
		shuffleIndices(order);
		let frame = 0;
		const tick = () => {
			const portion = revealPerFrame[Math.min(frame, total - 1)];
			const revealedCount = Math.floor(portion * maxLen);
			const revealed = new Uint8Array(maxLen);
			for (let k = 0; k < revealedCount; k++) revealed[order[k]] = 1;
			const pending = maxLen - revealedCount;
			const scrambleBudget = Math.max(0, Math.floor(intensity * pending));
			const tailStart = revealedCount;
			const take = Math.min(scrambleBudget, maxLen - tailStart);
			const activeMask = new Uint8Array(maxLen);
			for (let i = 0; i < take; i++) activeMask[order[tailStart + i]] = 1;
			for (let i = 0; i < maxLen; i++) {
				if (revealed[i]) {
					work[i] = baseChars[i];
				} else {
					const c = chars[(Math.random() * chars.length) | 0];
					work[i] = c;
					if (!activeMask[i] && ((i + frame) & 1) === 0) {
						work[i] = chars[(Math.random() * chars.length) | 0];
					}
				}
			}
			setDisplay(work.join(""));
			frame++;
			if (frame < total) {
				frameRef.current = requestAnimationFrame(tick);
			} else {
				setDisplay(base);
				runningRef.current = false;
				frameRef.current = null;
			}
		};
		frameRef.current = requestAnimationFrame(tick);
	}, [base, maxLen, indices, chars, durationMs, fps, revealEase, intensity]);
	const onHoverStart = React2.useCallback(() => {
		if (!hoverOnly) return;
		if (repeatOnHover || (!repeatOnHover && !runningRef.current)) runScramble();
		anim.start({
			opacity: 1,
		});
	}, [hoverOnly, repeatOnHover, runScramble, anim]);
	const onHoverEnd = React2.useCallback(() => {
		anim.start({
			opacity: 1,
		});
	}, [anim]);
	const rootRef = React2.useRef(null);
	const triggeredOnceRef = React2.useRef(false);
	React2.useEffect(() => {
		if (hoverOnly || isCanvas) return;
		if (typeof __unframerWindow === "undefined" || !rootRef.current) return;
		const node = rootRef.current;
		const obs = new IntersectionObserver(
			(entries) => {
				for (const e of entries) {
					const visible = e.isIntersecting && e.intersectionRatio >= 0.25;
					if (!visible) continue;
					if (!repeatOnEnter) {
						if (!triggeredOnceRef.current) {
							triggeredOnceRef.current = true;
							runScramble();
							obs.disconnect();
						}
						continue;
					}
					if (!runningRef.current) runScramble();
				}
			},
			{
				root: null,
				rootMargin: "0px",
				threshold: [0, 0.25, 0.5, 0.75, 1],
			},
		);
		obs.observe(node);
		return () => obs.disconnect();
	}, [hoverOnly, isCanvas, repeatOnEnter, runScramble]);
	React2.useEffect(() => {
		if (isCanvas) return;
		if (!Number.isFinite(repeatAfterMs) || repeatAfterMs <= 0) return;
		if (typeof __unframerWindow === "undefined") return;
		const interval = __unframerWindow.setInterval(
			() => {
				if (
					typeof document !== "undefined" &&
					document.visibilityState === "hidden"
				)
					return;
				if (!runningRef.current) runScramble();
			},
			Math.max(50, repeatAfterMs | 0),
		);
		return () => clearInterval(interval);
	}, [repeatAfterMs, isCanvas, runScramble]);
	React2.useEffect(() => {
		return () => {
			if (frameRef.current != null) cancelAnimationFrame(frameRef.current);
		};
	}, []);
	const role = href ? "link" : void 0;
	const tabIndex = href ? 0 : void 0;
	const aria = ariaLabel || (href ? `Open link: ${base}` : void 0);
	return (
		<motion2.div
			ref={rootRef}
			role={role}
			tabIndex={tabIndex}
			aria-label={aria}
			onKeyDown={(e) => {
				if (!href) return;
				if (e.key === "Enter" || e.key === " ") {
					e.preventDefault();
					openLink(href, newTab);
				}
			}}
			onClick={() => openLink(href, newTab)}
			onHoverStart={onHoverStart}
			onHoverEnd={onHoverEnd}
			animate={anim}
			style={{
				display: "flex",
				alignItems: "center",
				justifyContent:
					textAlign === "center"
						? "center"
						: textAlign === "right"
							? "flex-end"
							: "flex-start",
				width: "100%",
				height: "100%",
				overflow: "hidden",
				cursor: href ? "pointer" : "default",
				...style,
			}}
		>
			<div
				style={{
					width: "100%",
					textAlign,
					color,
					fontFamily: family,
					fontWeight: weight,
					fontSize,
					lineHeight,
					letterSpacing,
					whiteSpace: "pre-wrap",
					wordBreak: "break-word",
					willChange: "contents",
				}}
			>
				{display}
			</div>
		</motion2.div>
	);
}
addPropertyControls(TextRandom, {
	text: {
		type: ControlType.String,
		title: "Text",
		defaultValue: "Hover to decode",
		displayTextArea: true,
	},
	font: {
		type: ControlType.Font,
		title: "Typography",
		controls: "extended",
		defaultFontType: "sans-serif",
		displayTextAlignment: true,
		displayFontSize: true,
		defaultValue: {
			fontFamily: "Inter",
			fontWeight: 600,
			fontSize: "18px",
			lineHeight: "1.1",
			letterSpacing: "0px",
			textAlign: "left",
		},
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: "#111111",
	},
	link: {
		type: ControlType.Link ?? ControlType.String,
		title: "Link",
		defaultValue: "",
	},
	newTab: {
		type: ControlType.Boolean,
		title: "Open in new tab",
		defaultValue: true,
	},
	ariaLabel: {
		type: ControlType.String,
		title: "Aria Label",
		defaultValue: "",
	},
	durationMs: {
		type: ControlType.Number,
		title: "Duration",
		min: 120,
		max: 4e3,
		step: 10,
		defaultValue: 900,
		unit: "ms",
	},
	fps: {
		type: ControlType.Number,
		title: "FPS",
		min: 12,
		max: 60,
		step: 1,
		defaultValue: 30,
	},
	revealEase: {
		type: ControlType.Enum,
		title: "Ease",
		options: ["linear", "out", "inOut"],
		optionTitles: ["Linear", "Out", "InOut"],
		defaultValue: "out",
	},
	intensity: {
		type: ControlType.Number,
		title: "Intensity",
		min: 0,
		max: 1,
		step: 0.01,
		defaultValue: 1,
	},
	charset: {
		type: ControlType.String,
		title: "Charset",
		defaultValue: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%*",
	},
	hoverOnly: {
		type: ControlType.Boolean,
		title: "Hover only",
		defaultValue: true,
	},
	repeatOnHover: {
		type: ControlType.Boolean,
		title: "Restart on hover",
		defaultValue: true,
	},
	repeatOnEnter: {
		type: ControlType.Boolean,
		title: "Repeat on enter",
		defaultValue: false,
	},
	repeatAfterMs: {
		type: ControlType.Number,
		title: "Repeat After",
		min: 0,
		max: 1e4,
		step: 50,
		unit: "ms",
		defaultValue: 0,
	},
});

// /:https://framerusercontent.com/modules/l4tfa3wN5cqPeXN1q7ta/WeoxYdYioSjsrXjuwX5s/Fwuwh3EWM.js
var TextRandomFonts = getFonts(TextRandom);
var serializationHash = "framer-XDzlH";
var variantClassNames = {
	UAUebGCXg: "framer-v-1du244i",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React3.Fragment);
var getProps2 = ({
	color,
	height,
	hoverOnly,
	id,
	repeatAfter,
	repeatOnEnter,
	restartOnHover,
	text,
	width,
	...props
}) => {
	return {
		...props,
		aP52ysf_Q: text ?? props.aP52ysf_Q ?? "56123123",
		c1WtQM9IT:
			color ??
			props.c1WtQM9IT ??
			"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
		gUQ0oxGg4: restartOnHover ?? props.gUQ0oxGg4,
		lYN7YXbb1: repeatAfter ?? props.lYN7YXbb1 ?? 1e3,
		M8MzvGnSK: hoverOnly ?? props.M8MzvGnSK,
		Uq_JXwyjW: repeatOnEnter ?? props.Uq_JXwyjW ?? true,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		aP52ysf_Q,
		c1WtQM9IT,
		M8MzvGnSK,
		gUQ0oxGg4,
		Uq_JXwyjW,
		lYN7YXbb1,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "UAUebGCXg",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1du244i",
							className5,
							classNames,
						)}
						data-framer-name={"Vertical Text"}
						layoutDependency={layoutDependency}
						layoutId={"UAUebGCXg"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1r7z6pl-container"}
								isAuthoredByUser={true}
								layoutDependency={layoutDependency}
								layoutId={"VB_5ZysXI-container"}
								nodeId={"VB_5ZysXI"}
								rendersWithMotion={true}
								scopeId={"Fwuwh3EWM"}
								style={{
									rotate: -90,
								}}
							>
								<TextRandom
									ariaLabel={""}
									charset={"0123456789"}
									color={c1WtQM9IT}
									durationMs={2e3}
									font={{
										fontFamily: '"Inter", "Inter Placeholder", sans-serif',
										fontSize: "8px",
										fontStyle: "normal",
										fontWeight: 400,
										letterSpacing: "1px",
										lineHeight: "8px",
										textAlign: "center",
									}}
									fps={50}
									height={"100%"}
									hoverOnly={M8MzvGnSK}
									id={"VB_5ZysXI"}
									intensity={1}
									layoutId={"VB_5ZysXI"}
									newTab={true}
									repeatAfterMs={lYN7YXbb1}
									repeatOnEnter={Uq_JXwyjW}
									repeatOnHover={gUQ0oxGg4}
									revealEase={"out"}
									style={{
										height: "100%",
										width: "100%",
									}}
									text={aP52ysf_Q}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion3.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XDzlH.framer-vs6shq, .framer-XDzlH .framer-vs6shq { display: block; }",
	".framer-XDzlH.framer-1du244i { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 140px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 9px; }",
	".framer-XDzlH .framer-1r7z6pl-container { flex: none; height: 8px; position: relative; width: 138px; }",
];
var FramerFwuwh3EWM = withCSS2(Component2, css6, "framer-XDzlH");
var stdin_default5 = FramerFwuwh3EWM;
FramerFwuwh3EWM.displayName = "Random Text";
FramerFwuwh3EWM.defaultProps = {
	height: 140,
	width: 9,
};
addPropertyControls2(FramerFwuwh3EWM, {
	aP52ysf_Q: {
		defaultValue: "56123123",
		displayTextArea: true,
		title: "Text",
		type: ControlType2.String,
	},
	c1WtQM9IT: {
		defaultValue:
			'var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Color",
		type: ControlType2.Color,
	},
	M8MzvGnSK: {
		defaultValue: false,
		title: "Hover Only",
		type: ControlType2.Boolean,
	},
	gUQ0oxGg4: {
		defaultValue: false,
		title: "Restart On Hover",
		type: ControlType2.Boolean,
	},
	Uq_JXwyjW: {
		defaultValue: true,
		title: "Repeat On Enter",
		type: ControlType2.Boolean,
	},
	lYN7YXbb1: {
		defaultValue: 1e3,
		max: 1e4,
		min: 0,
		step: 500,
		title: "Repeat After",
		type: ControlType2.Number,
	},
});
addFonts(
	FramerFwuwh3EWM,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TextRandomFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/blaobUprRuRNudFlxytE/2oUGdtpbM7qjwPubECR1/TWoStnPJs.js
var LoadingFonts = getFonts2(stdin_default3);
var MorphGPUFonts = getFonts2(MorphGPU);
var RandomTextFonts = getFonts2(stdin_default5);
var MenuHeroLinksFonts = getFonts2(stdin_default);
var RichTextWithHiTechFlashvhjfcl = withCodeBoundaryForOverrides(RichText, {
	nodeId: "lZ8yTYF6i",
	override: withHiTechFlash,
	scopeId: "TWoStnPJs",
});
var ScrollDownAnimationFonts = getFonts2(stdin_default2);
var cycleOrder = ["zoMwDhuhm", "rvikxZtWL", "uEDJKoml5"];
var serializationHash2 = "framer-3LWK1";
var variantClassNames2 = {
	rvikxZtWL: "framer-v-tu8x1y",
	uEDJKoml5: "framer-v-1j6m0qo",
	zoMwDhuhm: "framer-v-jajp6h",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toImageSrc = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value.src;
	}
	return typeof value === "string" ? value : void 0;
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion4.create(React4.Fragment);
var humanReadableVariantMap = {
	Desktop: "zoMwDhuhm",
	Phone: "uEDJKoml5",
	Tablet: "rvikxZtWL",
};
var getProps3 = ({
	height,
	id,
	link1,
	link1URL,
	link2,
	link2URL,
	link3,
	link3URL,
	link4,
	link4URL,
	link5,
	link5URL,
	logo,
	morphImage1,
	morphImage2,
	slogan,
	width,
	...props
}) => {
	return {
		...props,
		bLu9TnxH4: link2 ?? props.bLu9TnxH4 ?? "Services",
		F3wEFrLg7: link1URL ?? props.F3wEFrLg7,
		JYUO86ucP: link4 ?? props.JYUO86ucP ?? "Cases",
		k3QcAoDID: slogan ?? props.k3QcAoDID ?? "Catch Bias Before it Ships",
		kVptXE5dN: link3URL ?? props.kVptXE5dN,
		mDSJnXF5t: link4URL ?? props.mDSJnXF5t,
		mRb3mP3Yg: link5URL ?? props.mRb3mP3Yg,
		pS5oa7lry: morphImage1 ??
			props.pS5oa7lry ?? {
				pixelHeight: 3935,
				pixelWidth: 5895,
				src: "https://framerusercontent.com/images/9QYgZcYCxCWdw0tZvZge3zJog.jpg?width=5895&height=3935",
				srcSet:
					"https://framerusercontent.com/images/9QYgZcYCxCWdw0tZvZge3zJog.jpg?scale-down-to=512&width=5895&height=3935 512w,https://framerusercontent.com/images/9QYgZcYCxCWdw0tZvZge3zJog.jpg?scale-down-to=1024&width=5895&height=3935 1024w,https://framerusercontent.com/images/9QYgZcYCxCWdw0tZvZge3zJog.jpg?scale-down-to=2048&width=5895&height=3935 2048w,https://framerusercontent.com/images/9QYgZcYCxCWdw0tZvZge3zJog.jpg?scale-down-to=4096&width=5895&height=3935 4096w,https://framerusercontent.com/images/9QYgZcYCxCWdw0tZvZge3zJog.jpg?width=5895&height=3935 5895w",
			},
		R1kaDpBq8: link3 ?? props.R1kaDpBq8 ?? "Process",
		taThGoI24: morphImage2 ??
			props.taThGoI24 ?? {
				pixelHeight: 1800,
				pixelWidth: 3200,
				src: "https://framerusercontent.com/images/0yeiJ9fLT9M5S8KWSrmy6IaGNSs.jpg?width=3200&height=1800",
				srcSet:
					"https://framerusercontent.com/images/0yeiJ9fLT9M5S8KWSrmy6IaGNSs.jpg?scale-down-to=512&width=3200&height=1800 512w,https://framerusercontent.com/images/0yeiJ9fLT9M5S8KWSrmy6IaGNSs.jpg?scale-down-to=1024&width=3200&height=1800 1024w,https://framerusercontent.com/images/0yeiJ9fLT9M5S8KWSrmy6IaGNSs.jpg?scale-down-to=2048&width=3200&height=1800 2048w,https://framerusercontent.com/images/0yeiJ9fLT9M5S8KWSrmy6IaGNSs.jpg?width=3200&height=1800 3200w",
			},
		tcqXAkE3f: link1 ?? props.tcqXAkE3f ?? "Home",
		UrY2rzAk2: link5 ?? props.UrY2rzAk2 ?? "Contact",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zoMwDhuhm",
		WJjdEU8qb: logo ?? props.WJjdEU8qb ?? stdin_default4,
		wkNO7DvZM: link2URL ?? props.wkNO7DvZM,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		k3QcAoDID: k3QcAoDID2,
		WJjdEU8qb: WJjdEU8qb2,
		pS5oa7lry: pS5oa7lry2,
		taThGoI24: taThGoI242,
		tcqXAkE3f: tcqXAkE3f2,
		F3wEFrLg7: F3wEFrLg72,
		bLu9TnxH4: bLu9TnxH42,
		wkNO7DvZM: wkNO7DvZM2,
		R1kaDpBq8: R1kaDpBq82,
		kVptXE5dN: kVptXE5dN2,
		JYUO86ucP: JYUO86ucP2,
		mDSJnXF5t: mDSJnXF5t2,
		UrY2rzAk2: UrY2rzAk22,
		mRb3mP3Yg: mRb3mP3Yg2,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "zoMwDhuhm",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1pfzlq4 = activeVariantCallback(async (...args) => {
		setVariant("zoMwDhuhm");
	});
	const sharedStyleClassNames = [className4, className2, className, className3];
	const scopingClassNames = cx3(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "uEDJKoml5") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "uEDJKoml5") return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion4.section
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-jajp6h",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"zoMwDhuhm"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								rvikxZtWL: {
									"data-framer-name": "Tablet",
								},
								uEDJKoml5: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2
							height={50}
							width={"50px"}
							y={
								(componentViewport?.y || 0) +
								((componentViewport?.height || 800) * 0.5000000000000002 - 25)
							}
							{...addPropertyOverrides(
								{
									uEDJKoml5: {
										y:
											(componentViewport?.y || 0) +
											((componentViewport?.height || 720) * 0.5000000000000002 -
												25),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer2
								className={"framer-b3q5nb-container"}
								layoutDependency={layoutDependency}
								layoutId={"hPtQHI0L8-container"}
								nodeId={"hPtQHI0L8"}
								rendersWithMotion={true}
								scopeId={"TWoStnPJs"}
							>
								{_jsx4(stdin_default3, {
									height: "100%",
									id: "hPtQHI0L8",
									layoutId: "hPtQHI0L8",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "IuzRA6V2q",
									width: "100%",
								})}
							</SmartComponentScopedContainer2>
						</ComponentViewportProvider2>
						{isDisplayed() && (
							<ComponentViewportProvider2>
								<SmartComponentScopedContainer2
									className={"framer-kgq5wu-container"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"sr7alaWUr-container"}
									nodeId={"sr7alaWUr"}
									rendersWithMotion={true}
									scopeId={"TWoStnPJs"}
									style={{
										rotate: 180,
										rotateY: 180,
									}}
								>
									<MorphGPU
										height={"100%"}
										id={"sr7alaWUr"}
										imgA={toImageSrc(pS5oa7lry2)}
										imgB={toImageSrc(taThGoI242)}
										layoutId={"sr7alaWUr"}
										morphMs={3e3}
										pauseMs={2e3}
										style={{
											height: "100%",
											width: "100%",
										}}
										underlayStart={0.1}
										width={"100%"}
									/>
								</SmartComponentScopedContainer2>
							</ComponentViewportProvider2>
						)}
						<motion4.div
							className={"framer-gz1329"}
							data-framer-name={"Lines"}
							layoutDependency={layoutDependency}
							layoutId={"jwEDqbkqZ"}
						>
							<motion4.div
								className={"framer-uh0g9j"}
								data-framer-name={"1"}
								layoutDependency={layoutDependency}
								layoutId={"SBewQTqRC"}
							>
								<motion4.div
									className={"framer-m1ahfg"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"DjuzA7ycy"}
									style={{
										backgroundColor:
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										opacity: 0.15,
									}}
								/>
								{isDisplayed() && (
									<motion4.div
										className={"framer-w2lwf8"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"UONismgBv"}
										style={{
											backgroundColor:
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											opacity: 0.15,
										}}
									/>
								)}
								<ComponentViewportProvider2
									height={57}
									width={"9px"}
									y={
										(componentViewport?.y || 0) +
										0 +
										(0 +
											((componentViewport?.height || 800) * 1 -
												0 -
												((componentViewport?.height || 800) * 1 - 0) * 1) /
												2) +
										10
									}
									{...addPropertyOverrides(
										{
											uEDJKoml5: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(0 +
														((componentViewport?.height || 720) * 1 -
															0 -
															((componentViewport?.height || 720) * 1 - 0) *
																1) /
															2) +
													10,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-w86n5f-container"}
										layoutDependency={layoutDependency}
										layoutId={"fx2eIguN5-container"}
										nodeId={"fx2eIguN5"}
										rendersWithMotion={true}
										scopeId={"TWoStnPJs"}
										style={{
											opacity: 0.7,
										}}
									>
										{_jsx4(stdin_default5, {
											aP52ysf_Q: "02145",
											c1WtQM9IT:
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											gUQ0oxGg4: false,
											height: "100%",
											id: "fx2eIguN5",
											layoutId: "fx2eIguN5",
											lYN7YXbb1: 4e3,
											M8MzvGnSK: false,
											style: {
												height: "100%",
												width: "100%",
											},
											Uq_JXwyjW: true,
											width: "100%",
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
								<ComponentViewportProvider2
									height={57}
									width={"9px"}
									y={
										(componentViewport?.y || 0) +
										0 +
										(0 +
											((componentViewport?.height || 800) * 1 -
												0 -
												((componentViewport?.height || 800) * 1 - 0) * 1) /
												2) +
										(((componentViewport?.height || 800) * 1 - 0) *
											1 *
											0.5000000000000002 -
											28.5)
									}
									{...addPropertyOverrides(
										{
											uEDJKoml5: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(0 +
														((componentViewport?.height || 720) * 1 -
															0 -
															((componentViewport?.height || 720) * 1 - 0) *
																1) /
															2) +
													(((componentViewport?.height || 720) * 1 - 0) *
														1 *
														0.5000000000000002 -
														28.5),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-4dyixw-container"}
										layoutDependency={layoutDependency}
										layoutId={"bc3VAKifz-container"}
										nodeId={"bc3VAKifz"}
										rendersWithMotion={true}
										scopeId={"TWoStnPJs"}
										style={{
											opacity: 0.7,
										}}
									>
										{_jsx4(stdin_default5, {
											aP52ysf_Q: "IUWEW652",
											c1WtQM9IT:
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											gUQ0oxGg4: false,
											height: "100%",
											id: "bc3VAKifz",
											layoutId: "bc3VAKifz",
											lYN7YXbb1: 4e3,
											M8MzvGnSK: false,
											style: {
												height: "100%",
												width: "100%",
											},
											Uq_JXwyjW: true,
											width: "100%",
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion4.div>
							<motion4.div
								className={"framer-1s1s0m1"}
								data-framer-name={"2"}
								layoutDependency={layoutDependency}
								layoutId={"uqqFVybx3"}
							>
								{isDisplayed() && (
									<motion4.div
										className={"framer-1csqn9m"}
										data-framer-name={"Line"}
										layoutDependency={layoutDependency}
										layoutId={"hlr5wFBQW"}
										style={{
											backgroundColor:
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											opacity: 0.15,
										}}
									/>
								)}
								{isDisplayed() && (
									<ComponentViewportProvider2
										height={64}
										width={"9px"}
										y={
											(componentViewport?.y || 0) +
											0 +
											(0 +
												((componentViewport?.height || 800) * 1 -
													0 -
													((componentViewport?.height || 800) * 1 - 0) * 1) /
													2) +
											25
										}
									>
										<SmartComponentScopedContainer2
											className={"framer-13yl4m3-container"}
											layoutDependency={layoutDependency}
											layoutId={"T2RLs6X21-container"}
											nodeId={"T2RLs6X21"}
											rendersWithMotion={true}
											scopeId={"TWoStnPJs"}
											style={{
												opacity: 0.7,
											}}
										>
											{_jsx4(stdin_default5, {
												aP52ysf_Q: "984654564",
												c1WtQM9IT:
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												gUQ0oxGg4: false,
												height: "100%",
												id: "T2RLs6X21",
												layoutId: "T2RLs6X21",
												lYN7YXbb1: 4e3,
												M8MzvGnSK: false,
												style: {
													height: "100%",
													width: "100%",
												},
												Uq_JXwyjW: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								)}
								{isDisplayed() && (
									<ComponentViewportProvider2
										height={77}
										width={"9px"}
										y={
											(componentViewport?.y || 0) +
											0 +
											(0 +
												((componentViewport?.height || 800) * 1 -
													0 -
													((componentViewport?.height || 800) * 1 - 0) * 1) /
													2) +
											(((componentViewport?.height || 800) * 1 - 0) *
												1 *
												0.5337500000000002 -
												38.5)
										}
									>
										<SmartComponentScopedContainer2
											className={"framer-kzx4u5-container"}
											layoutDependency={layoutDependency}
											layoutId={"ixD1bla3Z-container"}
											nodeId={"ixD1bla3Z"}
											rendersWithMotion={true}
											scopeId={"TWoStnPJs"}
											style={{
												opacity: 0.7,
											}}
										>
											{_jsx4(stdin_default5, {
												aP52ysf_Q: "WUIY12381273",
												c1WtQM9IT:
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												gUQ0oxGg4: false,
												height: "100%",
												id: "ixD1bla3Z",
												layoutId: "ixD1bla3Z",
												lYN7YXbb1: 2e3,
												M8MzvGnSK: false,
												style: {
													height: "100%",
													width: "100%",
												},
												Uq_JXwyjW: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								)}
							</motion4.div>
							<motion4.div
								className={"framer-1d4tulg"}
								data-framer-name={"3"}
								layoutDependency={layoutDependency}
								layoutId={"GzD8_pL6K"}
							>
								<motion4.div
									className={"framer-9ohmkz"}
									data-framer-name={"Line"}
									layoutDependency={layoutDependency}
									layoutId={"OSK32qnEi"}
									style={{
										backgroundColor:
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										opacity: 0.15,
									}}
								/>
								{isDisplayed() && (
									<ComponentViewportProvider2
										height={77}
										width={"9px"}
										y={
											(componentViewport?.y || 0) +
											0 +
											(0 +
												((componentViewport?.height || 800) * 1 -
													0 -
													((componentViewport?.height || 800) * 1 - 0) * 1) /
													2) +
											313.5
										}
									>
										<SmartComponentScopedContainer2
											className={"framer-15iqvo1-container"}
											layoutDependency={layoutDependency}
											layoutId={"Y9u38w922-container"}
											nodeId={"Y9u38w922"}
											rendersWithMotion={true}
											scopeId={"TWoStnPJs"}
											style={{
												opacity: 0.7,
											}}
										>
											{_jsx4(stdin_default5, {
												aP52ysf_Q: "MBDS945654",
												c1WtQM9IT:
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												gUQ0oxGg4: false,
												height: "100%",
												id: "Y9u38w922",
												layoutId: "Y9u38w922",
												lYN7YXbb1: 2e3,
												M8MzvGnSK: false,
												style: {
													height: "100%",
													width: "100%",
												},
												Uq_JXwyjW: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								)}
								{isDisplayed() && (
									<ComponentViewportProvider2
										height={116}
										width={"9px"}
										y={
											(componentViewport?.y || 0) +
											0 +
											(0 +
												((componentViewport?.height || 800) * 1 -
													0 -
													((componentViewport?.height || 800) * 1 - 0) * 1) /
													2) +
											(((componentViewport?.height || 800) * 1 - 0) *
												1 *
												0.5000000000000002 -
												58)
										}
									>
										<SmartComponentScopedContainer2
											className={"framer-87e3ys-container"}
											layoutDependency={layoutDependency}
											layoutId={"sF62s4jOz-container"}
											nodeId={"sF62s4jOz"}
											rendersWithMotion={true}
											scopeId={"TWoStnPJs"}
											style={{
												opacity: 0.7,
											}}
										>
											{_jsx4(stdin_default5, {
												aP52ysf_Q: "NMNSD651654564689",
												c1WtQM9IT:
													"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
												gUQ0oxGg4: false,
												height: "100%",
												id: "sF62s4jOz",
												layoutId: "sF62s4jOz",
												lYN7YXbb1: 4e3,
												M8MzvGnSK: false,
												style: {
													height: "100%",
													width: "100%",
												},
												Uq_JXwyjW: true,
												width: "100%",
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								)}
							</motion4.div>
						</motion4.div>
						<motion4.div
							className={"framer-kiz7hu"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"t8XPDtoNN"}
						>
							<motion4.div
								className={"framer-1a774hc"}
								data-framer-name={"Recent Case & Menu"}
								layoutDependency={layoutDependency}
								layoutId={"PfwRt6dwb"}
							>
								<ComponentViewportProvider2
									height={180}
									y={(componentViewport?.y || 0) + 0 + 0 + 100 + 0 + 0}
									{...addPropertyOverrides(
										{
											rvikxZtWL: {
												y: (componentViewport?.y || 0) + 0 + 0 + 50 + 0 + 0,
											},
											uEDJKoml5: {
												y: (componentViewport?.y || 0) + 0 + 0 + 30 + 0 + 0 + 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer2
										className={"framer-1vmextz-container"}
										layoutDependency={layoutDependency}
										layoutId={"dSCyOLpbT-container"}
										nodeId={"dSCyOLpbT"}
										rendersWithMotion={true}
										scopeId={"TWoStnPJs"}
									>
										{_jsx4(stdin_default, {
											dfS2LDEpS: mRb3mP3Yg2,
											DysJC_1cj: kVptXE5dN2,
											ecxWw6VhB: wkNO7DvZM2,
											height: "100%",
											id: "dSCyOLpbT",
											k3lRB2Eb3: mDSJnXF5t2,
											Kss1S8FBU: R1kaDpBq82,
											layoutId: "dSCyOLpbT",
											Lhv1vNzgf: bLu9TnxH42,
											s9VsuJvXT: UrY2rzAk22,
											tfQntUoHI: 5,
											trkldUXRj: tcqXAkE3f2,
											WeXuJH6m6: JYUO86ucP2,
											width: "100%",
											x7r_43pIr: F3wEFrLg72,
											...addPropertyOverrides(
												{
													rvikxZtWL: {
														tfQntUoHI: 6,
													},
													uEDJKoml5: {
														tfQntUoHI: 10,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer2>
								</ComponentViewportProvider2>
							</motion4.div>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-yt8n6m"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"l1OilmzGS"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										uEDJKoml5: {
											children: (
												<React4.Fragment>
													<motion4.h3
														className={"framer-styles-preset-wvy7ez"}
														data-styles-preset={"hdCs32bmG"}
													>
														{"SENTINEL"}
													</motion4.h3>
												</React4.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React4.Fragment>
									<motion4.h1
										className={"framer-styles-preset-gwdmae"}
										data-styles-preset={"NWySovwm6"}
									>
										{"SENTINEL"}
									</motion4.h1>
								</React4.Fragment>
							</RichText>
							<Instance
								animated={true}
								className={"framer-1u7tdud"}
								Component={WJjdEU8qb2}
								data-framer-name={"Logotype"}
								layoutDependency={layoutDependency}
								layoutId={"bEDhCx3Ic"}
							/>
							<motion4.div
								className={"framer-1wbuzj0"}
								layoutDependency={layoutDependency}
								layoutId={"QpZxoyca3"}
							>
								<RichTextWithHiTechFlashvhjfcl
									__fromCanvasComponent={true}
									className={"framer-vhjfcl"}
									data-framer-name={"FUTURE\u2028CREATIVE AI AGENCY"}
									data-highlight={true}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"lZ8yTYF6i"}
									onTap={onTap1pfzlq4}
									style={{
										"--extracted-1ke0nse":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										"--extracted-1sp2osd":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={k3QcAoDID2}
									variants={{
										uEDJKoml5: {
											"--extracted-1vqrutl":
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											uEDJKoml5: {
												children: (
													<React4.Fragment>
														<motion4.h6
															className={"framer-styles-preset-92mpg9"}
															data-styles-preset={"pLAsvwM58"}
														>
															<motion4.span
																style={{
																	"--framer-text-color":
																		"var(--extracted-1vqrutl, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
																}}
															>
																{"Future Creative"}
																<motion4.br />
																{"AI Agency"}
															</motion4.span>
														</motion4.h6>
													</React4.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React4.Fragment>
										<motion4.h1
											className={"framer-styles-preset-4995rr"}
											data-styles-preset={"eGWmhLuo2"}
										>
											<motion4.span
												style={{
													"--framer-text-color":
														"var(--extracted-1sp2osd, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"FUTURE"}
											</motion4.span>
											<motion4.br />
											<motion4.span
												style={{
													"--framer-text-color":
														"var(--extracted-1ke0nse, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"CREATIVE AI AGENCY"}
											</motion4.span>
										</motion4.h1>
									</React4.Fragment>
								</RichTextWithHiTechFlashvhjfcl>
								<motion4.div
									className={"framer-15g6onf"}
									data-framer-name={"Scroll Down"}
									layoutDependency={layoutDependency}
									layoutId={"kssZcvtb6"}
								>
									<ComponentViewportProvider2
										height={34}
										y={
											(componentViewport?.y || 0) +
											0 +
											0 +
											100 +
											782 +
											0 +
											49 +
											0
										}
										{...addPropertyOverrides(
											{
												rvikxZtWL: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														50 +
														832 +
														0 +
														49 +
														0,
												},
												uEDJKoml5: {
													y:
														(componentViewport?.y || 0) +
														0 +
														0 +
														30 +
														788 +
														0 +
														28 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer2
											className={"framer-y3gomo-container"}
											layoutDependency={layoutDependency}
											layoutId={"HDtA_ikwj-container"}
											nodeId={"HDtA_ikwj"}
											rendersWithMotion={true}
											scopeId={"TWoStnPJs"}
										>
											{_jsx4(stdin_default2, {
												BzApZ2LCO: "SCROLL DOWN",
												height: "100%",
												id: "HDtA_ikwj",
												layoutId: "HDtA_ikwj",
												style: {
													height: "100%",
												},
												width: "100%",
											})}
										</SmartComponentScopedContainer2>
									</ComponentViewportProvider2>
								</motion4.div>
							</motion4.div>
						</motion4.div>
						{isDisplayed1() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 3935,
									pixelWidth: 5895,
									...toResponsiveImage(pS5oa7lry2),
								}}
								className={"framer-1g64h4r"}
								data-framer-name={"Morph Image 1"}
								layoutDependency={layoutDependency}
								layoutId={"JHch5Yl5e"}
								{...addPropertyOverrides(
									{
										uEDJKoml5: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														((componentViewport?.height || 720) *
															0.5000000000000002 -
															((componentViewport?.height || 720) * 1) / 2),
												),
												pixelHeight: 3935,
												pixelWidth: 5895,
												sizes: componentViewport?.width || "100vw",
												...toResponsiveImage(pS5oa7lry2),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
					</motion4.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3LWK1.framer-1pw8qlz, .framer-3LWK1 .framer-1pw8qlz { display: block; }",
	".framer-3LWK1.framer-jajp6h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-3LWK1 .framer-b3q5nb-container { flex: none; height: 50px; left: calc(50.00000000000002% - 50px / 2); position: absolute; top: calc(50.00000000000002% - 50px / 2); width: 50px; z-index: 1; }",
	".framer-3LWK1 .framer-kgq5wu-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: 0px; width: 100%; z-index: 2; }",
	".framer-3LWK1 .framer-gz1329 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; left: calc(50.00000000000002% - min(1600px, 100%) / 2); max-width: 1600px; overflow: var(--overflow-clip-fallback, clip); padding: 0px 50px 0px 50px; position: absolute; top: 0px; width: 100%; z-index: 3; }",
	".framer-3LWK1 .framer-uh0g9j { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: 100%; justify-content: space-between; padding: 0px; position: relative; width: 1px; }",
	".framer-3LWK1 .framer-m1ahfg, .framer-3LWK1 .framer-w2lwf8, .framer-3LWK1 .framer-1csqn9m, .framer-3LWK1 .framer-9ohmkz { flex: none; height: 100%; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1px; }",
	".framer-3LWK1 .framer-w86n5f-container { flex: none; height: 57px; position: absolute; right: 6px; top: 10px; width: 9px; z-index: 1; }",
	".framer-3LWK1 .framer-4dyixw-container { flex: none; height: 57px; left: 7px; position: absolute; top: calc(50.00000000000002% - 57px / 2); width: 9px; z-index: 1; }",
	".framer-3LWK1 .framer-1s1s0m1, .framer-3LWK1 .framer-1d4tulg { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: flex-end; padding: 0px; position: relative; width: 1px; }",
	".framer-3LWK1 .framer-13yl4m3-container { flex: none; height: 64px; position: absolute; right: 8px; top: 25px; width: 9px; z-index: 1; }",
	".framer-3LWK1 .framer-kzx4u5-container { flex: none; height: 77px; left: 7px; position: absolute; top: calc(53.375000000000014% - 77px / 2); width: 9px; z-index: 1; }",
	".framer-3LWK1 .framer-15iqvo1-container { flex: none; height: 77px; left: 8px; position: absolute; top: 314px; width: 9px; z-index: 1; }",
	".framer-3LWK1 .framer-87e3ys-container { flex: none; height: 116px; position: absolute; right: 8px; top: calc(50.00000000000002% - 116px / 2); width: 9px; z-index: 1; }",
	".framer-3LWK1 .framer-kiz7hu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: calc(var(--framer-viewport-height, 100vh) * 1); justify-content: space-between; max-width: 1600px; overflow: visible; padding: 100px 100px 35px 100px; position: relative; width: 100%; z-index: 3; }",
	".framer-3LWK1 .framer-1a774hc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 5; }",
	".framer-3LWK1 .framer-1vmextz-container { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; width: auto; }",
	".framer-3LWK1 .framer-yt8n6m { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-3LWK1 .framer-1u7tdud { bottom: 275px; flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: absolute; right: 333px; width: 23px; z-index: 1; }",
	".framer-3LWK1 .framer-1wbuzj0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; z-index: 5; }",
	".framer-3LWK1 .framer-vhjfcl { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 257px; word-break: break-word; word-wrap: break-word; }",
	".framer-3LWK1 .framer-15g6onf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-3LWK1 .framer-y3gomo-container { flex: none; height: 34px; position: relative; width: auto; }",
	".framer-3LWK1 .framer-1g64h4r { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: var(--overflow-clip-fallback, clip); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-filter-override, filter); z-index: 1; }",
	".framer-3LWK1.framer-v-tu8x1y.framer-jajp6h { width: 810px; }",
	".framer-3LWK1.framer-v-tu8x1y .framer-kiz7hu { padding: 50px 30px 35px 30px; }",
	".framer-3LWK1.framer-v-tu8x1y .framer-1a774hc, .framer-3LWK1.framer-v-1j6m0qo .framer-b3q5nb-container, .framer-3LWK1.framer-v-1j6m0qo .framer-1vmextz-container { order: 0; }",
	".framer-3LWK1.framer-v-tu8x1y .framer-yt8n6m, .framer-3LWK1.framer-v-1j6m0qo .framer-1u7tdud, .framer-3LWK1.framer-v-1j6m0qo .framer-1g64h4r { order: 2; }",
	".framer-3LWK1.framer-v-tu8x1y .framer-1u7tdud { bottom: 288px; order: 1; right: 140px; }",
	".framer-3LWK1.framer-v-tu8x1y .framer-1wbuzj0, .framer-3LWK1.framer-v-1j6m0qo .framer-gz1329 { order: 3; }",
	".framer-3LWK1.framer-v-1j6m0qo.framer-jajp6h { width: 390px; }",
	".framer-3LWK1.framer-v-1j6m0qo .framer-kiz7hu { align-content: flex-end; align-items: flex-end; gap: 10px; height: calc(var(--framer-viewport-height, 100vh) * 0.9); justify-content: flex-end; order: 4; padding: 30px 20px 20px 20px; }",
	".framer-3LWK1.framer-v-1j6m0qo .framer-1a774hc { align-content: flex-end; align-items: flex-end; flex: 1 0 0px; flex-direction: column; gap: unset; height: 1px; justify-content: space-between; order: 0; }",
	".framer-3LWK1.framer-v-1j6m0qo .framer-yt8n6m { order: 1; }",
	".framer-3LWK1.framer-v-1j6m0qo .framer-1wbuzj0 { gap: 10px; order: 3; }",
	...css4,
	...css2,
	...css,
	...css3,
];
var FramerTWoStnPJs = withCSS3(Component3, css7, "framer-3LWK1");
var stdin_default6 = FramerTWoStnPJs;
FramerTWoStnPJs.displayName = "Hero \u2013 Section";
FramerTWoStnPJs.defaultProps = {
	height: 800,
	width: 1200,
};
addPropertyControls3(FramerTWoStnPJs, {
	variant: {
		options: ["zoMwDhuhm", "rvikxZtWL", "uEDJKoml5"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	k3QcAoDID: {
		defaultValue: "Catch Bias Before it Ships",
		displayTextArea: true,
		title: "Slogan",
		type: ControlType3.String,
	},
	WJjdEU8qb: {
		defaultValue: {
			identifier: "local-module:vector/GjycoNqfh:default",
			moduleId: "we51sIebI935hWkVpdE4",
		},
		setModuleId: "GbASARqm6mg9hg6v1NpG",
		title: "Logo",
		type: ControlType3.VectorSetItem,
	},
	pS5oa7lry: {
		__defaultAssetReference:
			"data:framer/asset-reference,9QYgZcYCxCWdw0tZvZge3zJog.jpg?originalFilename=High-rise+Buildings+Night+Sea.jpg&width=5895&height=3935",
		title: "Morph Image 1",
		type: ControlType3.ResponsiveImage,
	},
	taThGoI24: {
		__defaultAssetReference:
			"data:framer/asset-reference,0yeiJ9fLT9M5S8KWSrmy6IaGNSs.jpg?originalFilename=Hero_2.jpg&width=3200&height=1800",
		title: "Morph Image 2",
		type: ControlType3.ResponsiveImage,
	},
	tcqXAkE3f: {
		defaultValue: "Home",
		displayTextArea: false,
		title: "Link 1",
		type: ControlType3.String,
	},
	F3wEFrLg7: {
		title: "Link 1 URL",
		type: ControlType3.Link,
	},
	bLu9TnxH4: {
		defaultValue: "Services",
		displayTextArea: false,
		title: "Link 2",
		type: ControlType3.String,
	},
	wkNO7DvZM: {
		title: "Link 2 URL",
		type: ControlType3.Link,
	},
	R1kaDpBq8: {
		defaultValue: "Process",
		displayTextArea: false,
		title: "Link 3",
		type: ControlType3.String,
	},
	kVptXE5dN: {
		title: "Link 3 URL",
		type: ControlType3.Link,
	},
	JYUO86ucP: {
		defaultValue: "Cases",
		displayTextArea: false,
		title: "Link 4",
		type: ControlType3.String,
	},
	mDSJnXF5t: {
		title: "Link 4 URL",
		type: ControlType3.Link,
	},
	UrY2rzAk2: {
		defaultValue: "Contact",
		displayTextArea: false,
		title: "Link 5",
		type: ControlType3.String,
	},
	mRb3mP3Yg: {
		title: "Link 5 URL",
		type: ControlType3.Link,
	},
});
addFonts2(
	FramerTWoStnPJs,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...LoadingFonts,
		...MorphGPUFonts,
		...RandomTextFonts,
		...MenuHeroLinksFonts,
		...ScrollDownAnimationFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "uEDJKoml5",
	md: "rvikxZtWL",
	"2xl": "zoMwDhuhm",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default6, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default6}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default6);
var hero_section_default = ComponentWithRoot;
export { hero_section_default as default };
