// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:icon-down-animation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bQays0ds2rR8gDfWyf7z/qyaEU8BTWUaAdNr7KXbo/KWp2cbgmt.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-tDsEd";
var variantClassNames = {
	PEjBfjICg: "framer-v-l4yrwp",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 1.3,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: -360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 0.5,
	ease: [0.41, -0.01, 0.49, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 3,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "PEjBfjICg",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-l4yrwp",
							className,
							classNames,
						)}
						data-framer-name={"Start"}
						layoutDependency={layoutDependency}
						layoutId={"PEjBfjICg"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<MotionDivWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={0.5}
							className={"framer-y2zknw"}
							data-framer-name={"Circle 2"}
							layoutDependency={layoutDependency}
							layoutId={"rmUnH2nr6"}
							style={{
								opacity: 0.5,
							}}
						>
							<SVG
								className={"framer-ez7k83"}
								data-framer-name={"Circle 2"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"YrmFH1X9a"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 34"><path d="M 29.262 11.447 C 30.126 13.37 30.526 15.47 30.43 17.576 C 30.335 19.682 29.747 21.736 28.714 23.573 C 27.68 25.411 26.23 26.98 24.48 28.156 C 22.73 29.331 20.728 30.079 18.637 30.34 C 16.544 30.602 14.421 30.368 12.435 29.66 C 10.45 28.951 8.658 27.786 7.205 26.259 C 5.751 24.732 4.676 22.885 4.066 20.867 C 3.456 18.849 3.327 16.717 3.691 14.64" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={9787142281}
								withExternalLayout={true}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__loop={animation1}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={0.5}
							className={"framer-79ve78"}
							data-framer-name={"Circle 1"}
							layoutDependency={layoutDependency}
							layoutId={"J5HVtqKdg"}
							style={{
								opacity: 0.5,
							}}
						>
							<SVG
								className={"framer-mwou4x"}
								data-framer-name={"Circle 1"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"VpYPPX4Aq"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 34"><path d="M 12.998 27.54 C 11.342 26.918 9.854 25.916 8.656 24.614 C 7.458 23.311 6.583 21.746 6.101 20.044 C 5.619 18.341 5.543 16.549 5.881 14.812 C 6.219 13.075 6.96 11.442 8.044 10.044 C 9.129 8.646 10.527 7.522 12.126 6.764 C 13.724 6.005 15.479 5.633 17.248 5.677 C 19.017 5.721 20.75 6.179 22.309 7.016 C 23.868 7.853 25.209 9.045 26.223 10.495" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={8983245099}
								withExternalLayout={true}
							/>
						</MotionDivWithFX>
						<MotionDivWithFX
							__framer__loop={animation2}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"mirror"}
							__framer__loopTransition={transition3}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-18tk9c9"}
							data-framer-name={"Icon Down"}
							layoutDependency={layoutDependency}
							layoutId={"woKYhjESx"}
						>
							<SVG
								className={"framer-41m11v"}
								data-framer-name={"Icon Down"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"XCNA74NVh"}
								opacity={1}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 34 34"><path d="M 12.96 13.96 L 16.96 17.96 L 20.96 13.96" fill="transparent" stroke="var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
								}
								svgContentId={10513274321}
								withExternalLayout={true}
							/>
						</MotionDivWithFX>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-tDsEd.framer-68fhg3, .framer-tDsEd .framer-68fhg3 { display: block; }",
	".framer-tDsEd.framer-l4yrwp { height: 34px; overflow: visible; position: relative; width: 34px; }",
	".framer-tDsEd .framer-y2zknw, .framer-tDsEd .framer-79ve78, .framer-tDsEd .framer-18tk9c9 { flex: none; height: 34px; left: calc(50.00000000000002% - 34px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 34px / 2); width: 34px; }",
	".framer-tDsEd .framer-ez7k83, .framer-tDsEd .framer-mwou4x, .framer-tDsEd .framer-41m11v { flex: none; height: 34px; left: calc(50.00000000000002% - 34px / 2); position: absolute; top: calc(50.00000000000002% - 34px / 2); width: 34px; }",
];
var FramerKWp2cbgmt = withCSS(Component, css, "framer-tDsEd");
var stdin_default = FramerKWp2cbgmt;
FramerKWp2cbgmt.displayName = "Icon Down - Animation";
FramerKWp2cbgmt.defaultProps = {
	height: 34,
	width: 34,
};
addFonts(
	FramerKWp2cbgmt,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:icon-down-animation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IconDownAnimationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var icon_down_animation_default = ComponentWithRoot;
export { icon_down_animation_default as default };
