// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Wide Screen' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * heading?: string // Heading
}} Props

 */
import { TextFrontCarousel } from "./chunks/chunk-VYEDRMNM.js";
import { stdin_default } from "./chunks/chunk-QV6YFK4Z.js";
import "./chunks/chunk-A5VIV4BG.js";
import "./chunks/chunk-W3MGGPGV.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:our-stack-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lv9bqSZljQGgfdBElbiN/nd9X34mxVHnVZgGfvwqT/W4y0PBcjK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var SmallHeadingWithLinesFonts = getFonts(stdin_default);
var TextFrontCarouselFonts = getFonts(TextFrontCarousel);
var cycleOrder = ["BNbMJxkaL", "KBFIsG_Pm", "h4UoONpV0", "uXykAYwLl"];
var serializationHash = "framer-z8b56";
var variantClassNames = {
	BNbMJxkaL: "framer-v-14jv1nc",
	h4UoONpV0: "framer-v-4dlmqp",
	KBFIsG_Pm: "framer-v-1e0553s",
	uXykAYwLl: "framer-v-1dybsqk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.5,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Wide Screen": "BNbMJxkaL",
	Laptop: "KBFIsG_Pm",
	Phone: "uXykAYwLl",
	Tablet: "h4UoONpV0",
};
var getProps = ({ heading, height, id, width, parentSize, providedWindow, ...props }) => {
	return {
		...props,
		Udvf2bKUQ: heading ?? props.Udvf2bKUQ ?? "OUR STACK",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "BNbMJxkaL",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		Udvf2bKUQ: Udvf2bKUQ2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "BNbMJxkaL",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14jv1nc",
							className,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"BNbMJxkaL"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) 0%, var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0)) 39%)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								h4UoONpV0: {
									"data-framer-name": "Tablet",
								},
								KBFIsG_Pm: {
									"data-framer-name": "Laptop",
								},
								uXykAYwLl: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.section
							className={"framer-1p16oje"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"CehE0Q2tZ"}
						>
							<motion.div
								className={"framer-1adev2r"}
								data-framer-name={"Heading"}
								layoutDependency={layoutDependency}
								layoutId={"rYPsUE9sg"}
							>
								<ComponentViewportProvider
									height={82}
									width={`calc(min(${componentViewport?.width || "100vw"}, 1600px) - 200px)`}
									y={(componentViewport?.y || 0) + 0 + 0 + 150 + 0 + 0 + 0}
									{...addPropertyOverrides(
										{
											h4UoONpV0: {
												width: `calc(min(${componentViewport?.width || "100vw"}, 1600px) - 60px)`,
												y:
													(componentViewport?.y || 0) + 0 + 0 + 100 + 0 + 0 + 0,
											},
											uXykAYwLl: {
												width: `calc(min(${componentViewport?.width || "100vw"}, 1600px) - 40px)`,
												y: (componentViewport?.y || 0) + 0 + 0 + 80 + 0 + 0 + 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1jglvww-container"}
										layoutDependency={layoutDependency}
										layoutId={"oTVhISMEG-container"}
										nodeId={"oTVhISMEG"}
										rendersWithMotion={true}
										scopeId={"W4y0PBcjK"}
									>
										{_jsx(stdin_default, {
											B4pJURn2f: true,
											height: "100%",
											id: "oTVhISMEG",
											layoutId: "oTVhISMEG",
											style: {
												width: "100%",
											},
											variant: "xXrD9u5iR",
											width: "100%",
											zWunlxr_x: Udvf2bKUQ2,
											...addPropertyOverrides(
												{
													h4UoONpV0: {
														variant: "Cbjf6HBG2",
													},
													uXykAYwLl: {
														variant: "TjckuJE3n",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1vzk6k2-container"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"bDYwp2_LY-container"}
									nodeId={"bDYwp2_LY"}
									rendersWithMotion={true}
									scopeId={"W4y0PBcjK"}
								>
									<TextFrontCarousel
										afterPaddingPx={160}
										backOpacityMax={0.22}
										bgColor={"rgba(0, 0, 0, 0)"}
										centerOpacityMax={0.9}
										crossFadeWidth={0.24}
										fadeExp={1.2}
										fgColor={"rgb(255, 255, 255)"}
										font={{
											fontFamily:
												'"Mozilla Text", "Mozilla Text Placeholder", sans-serif',
											fontStyle: "normal",
											fontWeight: 600,
										}}
										fontBackFarVW={3}
										fontBackNearVW={12}
										fontCenterVW={13}
										fontExitVW={100}
										frontFadeScale={0.2}
										height={"100%"}
										id={"bDYwp2_LY"}
										layoutId={"bDYwp2_LY"}
										letterSpacingEm={-0.04}
										phrases={[
											"Fairness",
											"Accuracy",
											"Trust",
											"Compliance",
										]}
										smoothDamping={26}
										smoothStiffness={120}
										spacing={1.4}
										stepYvh={12}
										stopMotionInEditor={false}
										style={{
											height: "100%",
											width: "100%",
										}}
										trail={3}
										vhPerStep={100}
										width={"100%"}
										windowFwd={2}
										{...addPropertyOverrides(
											{
												h4UoONpV0: {
													afterPaddingPx: 100,
													fontBackFarVW: 4,
													fontBackNearVW: 5.1,
													fontCenterVW: 9.5,
												},
												KBFIsG_Pm: {
													afterPaddingPx: 100,
													fontBackNearVW: 8.4,
													fontCenterVW: 10,
												},
												uXykAYwLl: {
													fontBackNearVW: 5,
													fontCenterVW: 12,
													fontExitVW: 50,
													vhPerStep: 90,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.section>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-z8b56.framer-1jf3jow, .framer-z8b56 .framer-1jf3jow { display: block; }",
	".framer-z8b56.framer-14jv1nc { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1600px; }",
	".framer-z8b56 .framer-1p16oje { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; max-width: 1600px; overflow: visible; padding: 150px 100px 250px 100px; position: relative; width: 100%; z-index: 3; }",
	".framer-z8b56 .framer-1adev2r { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: sticky; top: 150px; width: 100%; z-index: 5; }",
	".framer-z8b56 .framer-1jglvww-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-z8b56 .framer-1vzk6k2-container { flex: none; height: 8000px; position: relative; width: 100%; }",
	".framer-z8b56.framer-v-1e0553s.framer-14jv1nc { width: 1200px; }",
	".framer-z8b56.framer-v-1e0553s .framer-1p16oje { padding: 150px 100px 150px 100px; }",
	".framer-z8b56.framer-v-1e0553s .framer-1adev2r { top: 120px; }",
	".framer-z8b56.framer-v-1e0553s .framer-1vzk6k2-container, .framer-z8b56.framer-v-4dlmqp .framer-1vzk6k2-container { height: 6000px; }",
	".framer-z8b56.framer-v-4dlmqp.framer-14jv1nc { width: 810px; }",
	".framer-z8b56.framer-v-4dlmqp .framer-1p16oje { padding: 100px 30px 100px 30px; }",
	".framer-z8b56.framer-v-4dlmqp .framer-1adev2r { top: 100px; }",
	".framer-z8b56.framer-v-1dybsqk.framer-14jv1nc { width: 390px; }",
	".framer-z8b56.framer-v-1dybsqk .framer-1p16oje { padding: 80px 20px 80px 20px; }",
	".framer-z8b56.framer-v-1dybsqk .framer-1adev2r { top: 80px; }",
	".framer-z8b56.framer-v-1dybsqk .framer-1vzk6k2-container { height: 4000px; }",
];
var FramerW4y0PBcjK = withCSS(Component, css, "framer-z8b56");
var stdin_default2 = FramerW4y0PBcjK;
FramerW4y0PBcjK.displayName = "Our Stack \u2013 Section";
FramerW4y0PBcjK.defaultProps = {
	height: 8522,
	width: 1600,
};
addPropertyControls(FramerW4y0PBcjK, {
	variant: {
		options: ["BNbMJxkaL", "KBFIsG_Pm", "h4UoONpV0", "uXykAYwLl"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Udvf2bKUQ: {
		defaultValue: "OUR STACK",
		displayTextArea: false,
		title: "Heading",
		type: ControlType.String,
	},
});
addFonts(
	FramerW4y0PBcjK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Mozilla Text",
					source: "google",
					style: "normal",
					uiFamilyName: "Mozilla Text",
					url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB1sbPNVRVYmoOXo.woff2",
					weight: "600",
				},
			],
		},
		...SmallHeadingWithLinesFonts,
		...TextFrontCarouselFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:our-stack-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "uXykAYwLl",
	md: "h4UoONpV0",
	xl: "KBFIsG_Pm",
	"2xl": "BNbMJxkaL",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders OurStackSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var our_stack_section_default = ComponentWithRoot;
export { our_stack_section_default as default };
