// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Wide Screen' | 'Laptop' | 'Tablet' | 'Phone' // Variant
 * heading?: string // Heading
 * linkToSectionOrPage?: string // Link to Section or Page
}} Props

 */
import { HorizontalTextTube } from "./chunks/chunk-2XILGZSZ.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-YC4JS6HC.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KDPSGK4W.js";
import { className, css, fonts } from "./chunks/chunk-K7JSNEXQ.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:services-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/9p74qDuLEfjvaMsQ2Nve/YSwa3s4GlgUiljsb8gDk/QZVUmUP9B.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var HorizontalTextTubeFonts = getFonts(HorizontalTextTube);
var cycleOrder = ["OBRJPyPcR", "kNX5ijjKJ", "k3Uw2mLUG", "pfBuwzsD2"];
var serializationHash = "framer-EzW10";
var variantClassNames = {
	k3Uw2mLUG: "framer-v-78gsh8",
	kNX5ijjKJ: "framer-v-1mlphww",
	OBRJPyPcR: "framer-v-1ljj4z7",
	pfBuwzsD2: "framer-v-jeys9j",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Wide Screen": "OBRJPyPcR",
	Laptop: "kNX5ijjKJ",
	Phone: "pfBuwzsD2",
	Tablet: "k3Uw2mLUG",
};
var getProps = ({
	heading,
	height,
	id,
	linkToSectionOrPage,
	width,
	...props
}) => {
	return {
		...props,
		eEHxCQRfs: linkToSectionOrPage ?? props.eEHxCQRfs,
		orI9Q0xAd: heading ?? props.orI9Q0xAd ?? "Services",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "OBRJPyPcR",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		orI9Q0xAd: orI9Q0xAd2,
		eEHxCQRfs: eEHxCQRfs2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "OBRJPyPcR",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ljj4z7",
							className4,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"OBRJPyPcR"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, rgb(242, 242, 242) 65%, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) 100%)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								k3Uw2mLUG: {
									"data-framer-name": "Tablet",
								},
								kNX5ijjKJ: {
									"data-framer-name": "Laptop",
								},
								pfBuwzsD2: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Link
							href={eEHxCQRfs2}
							motionChild={true}
							nodeId={"yamkUXthA"}
							openInNewTab={false}
							scopeId={"QZVUmUP9B"}
							smoothScroll={true}
							{...addPropertyOverrides(
								{
									k3Uw2mLUG: {
										href: void 0,
									},
									pfBuwzsD2: {
										href: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.a
								className={"framer-zfcclr framer-jf0b27"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"yamkUXthA"}
							>
								<motion.div
									className={"framer-zc26t0"}
									data-framer-name={"Heading"}
									layoutDependency={layoutDependency}
									layoutId={"LTgU7J545"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-2q1b7n"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"YCCNUJuY7"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={orI9Q0xAd2}
										variants={{
											k3Uw2mLUG: {
												"--extracted-a0htzi":
													"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
											},
											pfBuwzsD2: {
												"--extracted-1eung3n":
													"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
											},
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												k3Uw2mLUG: {
													children: (
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-wvy7ez"}
																data-styles-preset={"hdCs32bmG"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																}}
															>
																{"Services"}
															</motion.h3>
														</React.Fragment>
													),
												},
												pfBuwzsD2: {
													children: (
														<React.Fragment>
															<motion.h4
																className={"framer-styles-preset-19084qk"}
																data-styles-preset={"D2Nj2b5ip"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1eung3n, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
																}}
															>
																{"Services"}
															</motion.h4>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h2
												className={"framer-styles-preset-ep0jra"}
												data-styles-preset={"hZ8usl_26"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
												}}
											>
												{"Services"}
											</motion.h2>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-mrc7gh"}
										data-framer-name={"Dot"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"sutsBEYr0"}
										style={{
											"--extracted-1of0zx5":
												"var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0))",
											"--framer-paragraph-spacing": "0px",
										}}
										variants={{
											k3Uw2mLUG: {
												"--extracted-a0htzi":
													"var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0))",
											},
											pfBuwzsD2: {
												"--extracted-1eung3n":
													"var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0))",
											},
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												k3Uw2mLUG: {
													children: (
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-wvy7ez"}
																data-styles-preset={"hdCs32bmG"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0)))",
																}}
															>
																{"."}
															</motion.h3>
														</React.Fragment>
													),
												},
												pfBuwzsD2: {
													children: (
														<React.Fragment>
															<motion.h4
																className={"framer-styles-preset-19084qk"}
																data-styles-preset={"D2Nj2b5ip"}
																style={{
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1eung3n, var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0)))",
																}}
															>
																{"."}
															</motion.h4>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h2
												className={"framer-styles-preset-ep0jra"}
												data-styles-preset={"hZ8usl_26"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0)))",
												}}
											>
												{"."}
											</motion.h2>
										</React.Fragment>
									</RichText>
								</motion.div>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-ljc3kb-container"}
										isAuthoredByUser={true}
										layoutDependency={layoutDependency}
										layoutId={"NF7vEno7t-container"}
										nodeId={"NF7vEno7t"}
										rendersWithMotion={true}
										scopeId={"QZVUmUP9B"}
									>
										<HorizontalTextTube
											animateOnMobile={false}
											backOpacity={0.03}
											font={{
												fontFamily:
													'"Mozilla Text", "Mozilla Text Placeholder", sans-serif',
												fontStyle: "normal",
												fontWeight: 700,
											}}
											gap={-0.5}
											height={"100%"}
											id={"NF7vEno7t"}
											inertia={0.13}
											layoutId={"NF7vEno7t"}
											letterSpacingEm={-0.045}
											padTopPct={55}
											radius={1.2}
											span={1}
											speed={1}
											style={{
												height: "100%",
												width: "100%",
											}}
											texDpr={1.5}
											textColor={"rgb(0, 0, 0)"}
											width={"100%"}
											widthScale={0.5}
											words={[
												"Real-Time Detection",
												"Smart Rewrites",
												"Audit Trails",
												"Policy Management",
												"Team Collaboration",
												"Analytics Dashboard",
												"API Integration",
											]}
											{...addPropertyOverrides(
												{
													k3Uw2mLUG: {
														gap: -0.37,
														span: 0.76,
													},
													kNX5ijjKJ: {
														gap: -0.45,
													},
													pfBuwzsD2: {
														animateOnMobile: true,
														gap: -0.13,
														letterSpacingEm: -0.04,
														radius: 0.88,
														span: 0.49,
														widthScale: 0.52,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.a>
						</Link>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EzW10.framer-jf0b27, .framer-EzW10 .framer-jf0b27 { display: block; }",
	".framer-EzW10.framer-1ljj4z7 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1600px; }",
	".framer-EzW10 .framer-zfcclr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; max-width: 1600px; overflow: visible; padding: 250px 100px 0px 100px; position: relative; text-decoration: none; width: 100%; z-index: 3; }",
	".framer-EzW10 .framer-zc26t0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: sticky; top: 150px; width: 100%; z-index: 5; }",
	".framer-EzW10 .framer-2q1b7n { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-EzW10 .framer-mrc7gh { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-EzW10 .framer-ljc3kb-container { flex: none; height: 6200px; position: relative; width: 100%; }",
	".framer-EzW10.framer-v-1mlphww.framer-1ljj4z7 { width: 1200px; }",
	".framer-EzW10.framer-v-1mlphww .framer-zfcclr { padding: 150px 100px 0px 100px; }",
	".framer-EzW10.framer-v-1mlphww .framer-ljc3kb-container { height: 4300px; }",
	".framer-EzW10.framer-v-78gsh8.framer-1ljj4z7 { width: 810px; }",
	".framer-EzW10.framer-v-78gsh8 .framer-zfcclr { padding: 100px 30px 0px 30px; }",
	".framer-EzW10.framer-v-78gsh8 .framer-zc26t0 { top: 100px; }",
	".framer-EzW10.framer-v-78gsh8 .framer-ljc3kb-container, .framer-EzW10.framer-v-jeys9j .framer-ljc3kb-container { height: 4000px; }",
	".framer-EzW10.framer-v-jeys9j.framer-1ljj4z7 { width: 390px; }",
	".framer-EzW10.framer-v-jeys9j .framer-zfcclr { padding: 80px 0px 0px 0px; }",
	".framer-EzW10.framer-v-jeys9j .framer-zc26t0 { top: 80px; }",
	...css2,
	...css,
	...css3,
];
var FramerQZVUmUP9B = withCSS(Component, css4, "framer-EzW10");
var stdin_default = FramerQZVUmUP9B;
FramerQZVUmUP9B.displayName = "Services \u2013 Section";
FramerQZVUmUP9B.defaultProps = {
	height: 6570,
	width: 1600,
};
addPropertyControls(FramerQZVUmUP9B, {
	variant: {
		options: ["OBRJPyPcR", "kNX5ijjKJ", "k3Uw2mLUG", "pfBuwzsD2"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	orI9Q0xAd: {
		defaultValue: "Services",
		displayTextArea: false,
		title: "Heading",
		type: ControlType.String,
	},
	eEHxCQRfs: {
		title: "Link to Section or Page",
		type: ControlType.Link,
	},
});
addFonts(
	FramerQZVUmUP9B,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Mozilla Text",
					source: "google",
					style: "normal",
					uiFamilyName: "Mozilla Text",
					url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB2IbPNVRVYmoOXo.woff2",
					weight: "700",
				},
			],
		},
		...HorizontalTextTubeFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:services-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "pfBuwzsD2",
	md: "k3Uw2mLUG",
	xl: "kNX5ijjKJ",
	"2xl": "OBRJPyPcR",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicesSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var services_section_default = ComponentWithRoot;
export { services_section_default as default };
