// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Wide Screen' | 'Laptop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-63EPPTBA.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:testimonials-section
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lKnCYGrh7ZUgRwL0ANe0/GVLUNonHGbbXt7yPE6OM/HwdSExb6a.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx2,
	getFonts,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/EGJwfh8Oa88HRANdFQ0l/DVAX0b0um4ft8t0haGKS/PhotoTunnel.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useEffect, useMemo, useRef } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import * as THREE from "three";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var WALL_X_MIN = 7.6;
var WALL_X_MAX = 12.2;
var Y_MIN = -2.4;
var Y_MAX = 2.4;
var Z_SPACING = 5;
var SECTIONS = 40;
var Z_MAX = SECTIONS * Z_SPACING;
var Z_MIN_GAP = 4.5;
var Z_EXTRA = 4.5;
var Z_WOBBLE = 5.25;
var EDGE_GAP_BOOST = 0.8;
var BASE_W = 7;
var CAMERA_FOV = 60;
var START_Z = 1;
var FAR_PAD = 80;
var LOOK_PARALLAX = -0.55;
var CORNER_RADIUS_UV = 0;
function PhotoTunnel(props) {
	const sectionRef = useRef(null);
	const viewRef = useRef(null);
	const images = useMemo(() => {
		const takeUrl = (v) =>
			typeof v === "string"
				? v
				: v?.src || v?.url || v?.image?.src || v?.image?.url || "";
		const arr = (props.images || []).map(takeUrl).filter(Boolean).slice(0, 20);
		for (let i = arr.length - 1; i > 0; i--) {
			const j = Math.floor(Math.random() * (i + 1));
			[arr[i], arr[j]] = [arr[j], arr[i]];
		}
		return arr;
	}, [props.images]);
	useEffect(() => {
		const section = sectionRef.current;
		const view = viewRef.current;
		if (!section || !view) return;
		view.innerHTML = "";
		if (images.length === 0) return;
		const inEditor =
			RenderTarget.current() === RenderTarget.canvas ||
			RenderTarget.current() === RenderTarget.thumbnail;
		const canvasEl = document.createElement("canvas");
		canvasEl.style.width = "100%";
		canvasEl.style.height = "100%";
		canvasEl.style.display = "block";
		view.appendChild(canvasEl);
		const getSize = () => {
			const w = view.clientWidth || 1;
			const h = view.clientHeight || 1;
			const dpr = Math.min(__unframerWindow.devicePixelRatio || 1, 2);
			return {
				w,
				h,
				dpr,
			};
		};
		if (inEditor || !supportsOffscreen()) {
			const { dispose } = renderOneFrameMainThread({
				canvasEl,
				view,
				images,
			});
			return () => {
				dispose();
				if (canvasEl.parentElement === view) view.removeChild(canvasEl);
			};
		}
		let worker = null;
		let rafId = 0;
		try {
			const off = canvasEl.transferControlToOffscreen();
			const workerURL = makeWorkerURL();
			worker = new Worker(workerURL, {
				type: "classic",
			});
			const sendResize = () => {
				const { w: w2, h: h2, dpr: dpr2 } = getSize();
				worker?.postMessage({
					type: "resize",
					width: w2,
					height: h2,
					dpr: dpr2,
				});
			};
			const { w, h, dpr } = getSize();
			worker.postMessage(
				{
					type: "init",
					canvas: off,
					width: w,
					height: h,
					dpr,
					smooth: clamp(props.smooth ?? 0.08, 0.02, 0.2),
					images,
					constants: {
						WALL_X_MIN,
						WALL_X_MAX,
						Y_MIN,
						Y_MAX,
						Z_MAX,
						Z_MIN_GAP,
						Z_EXTRA,
						Z_WOBBLE,
						EDGE_GAP_BOOST,
						BASE_W,
						CAMERA_FOV,
						START_Z,
						FAR_PAD,
						LOOK_PARALLAX,
						CORNER_RADIUS_UV,
					},
				},
				[off],
			);
			const ro = new ResizeObserver(sendResize);
			ro.observe(view);
			const onPointer = (e) => {
				const r = view.getBoundingClientRect();
				const x = ((e.clientX - r.left) / r.width) * 2 - 1;
				const y = ((e.clientY - r.top) / r.height) * 2 - 1;
				worker?.postMessage({
					type: "pointer",
					x,
					y,
				});
			};
			view.addEventListener("pointermove", onPointer, {
				passive: true,
			});
			const pathLen = Z_MAX + FAR_PAD;
			const loop = () => {
				const rect = section.getBoundingClientRect();
				const vh = __unframerWindow.innerHeight || 1;
				const t = clamp((vh - rect.top) / (rect.height + vh), 0, 1);
				const targetZ = t * pathLen;
				worker?.postMessage({
					type: "progress",
					targetZ,
				});
				rafId = requestAnimationFrame(loop);
			};
			rafId = requestAnimationFrame(loop);
			return () => {
				cancelAnimationFrame(rafId);
				view.removeEventListener("pointermove", onPointer);
				ro.disconnect();
				if (worker) {
					try {
						worker.postMessage({
							type: "dispose",
						});
						worker.terminate();
					} catch {}
				}
				URL.revokeObjectURL(workerURL);
				if (canvasEl.parentElement === view) view.removeChild(canvasEl);
			};
		} catch {
			const { dispose } = renderOneFrameMainThread({
				canvasEl,
				view,
				images,
			});
			return () => {
				dispose();
				if (canvasEl.parentElement === view) view.removeChild(canvasEl);
			};
		}
	}, [images, props.smooth]);
	return (
		<div
			ref={sectionRef}
			style={{
				width: "100%",
				height: "100%",
				position: "relative",
				background: "transparent",
				overflow: "visible",
			}}
		>
			<div
				ref={viewRef}
				style={{
					position: "sticky",
					top: 0,
					width: "100%",
					height: "100vh",
					display: "grid",
					placeItems: "center",
					overflow: "hidden",
					background: "transparent",
				}}
			/>
		</div>
	);
}
function clamp(v, lo, hi) {
	return Math.max(lo, Math.min(hi, v));
}
function supportsOffscreen() {
	return (
		typeof HTMLCanvasElement?.prototype?.transferControlToOffscreen ===
			"function" && typeof Worker !== "undefined"
	);
}
function renderOneFrameMainThread(args) {
	const { canvasEl, view, images } = args;
	const renderer = new THREE.WebGLRenderer({
		canvas: canvasEl,
		antialias: true,
		alpha: true,
		premultipliedAlpha: true,
		powerPreference: "high-performance",
	});
	const setSize = () => {
		const w = view.clientWidth || 1;
		const h = view.clientHeight || 1;
		const dpr = Math.min(__unframerWindow.devicePixelRatio || 1, 2);
		renderer.setPixelRatio(dpr);
		renderer.setSize(w, h, false);
	};
	setSize();
	renderer.outputColorSpace = THREE.SRGBColorSpace;
	renderer.setClearColor(0, 0);
	const scene = new THREE.Scene();
	scene.fog = new THREE.FogExp2(0, 0.025);
	const camera = new THREE.PerspectiveCamera(
		CAMERA_FOV,
		(view.clientWidth || 1) / (view.clientHeight || 1),
		0.1,
		FAR_PAD + Z_MAX + 100,
	);
	camera.position.set(0, 0, START_Z);
	camera.lookAt(0, 0, START_Z + 10);
	scene.add(new THREE.AmbientLight(16777215, 0.85));
	const dir = new THREE.DirectionalLight(16777215, 0.55);
	dir.position.set(1, 2, 1);
	scene.add(dir);
	const planeGeo = new THREE.PlaneGeometry(1, 1);
	const maskTex = roundedAlphaTextureMain(CORNER_RADIUS_UV, 256);
	const leftZ = buildZTrack(
		Z_MAX,
		Z_MIN_GAP,
		Z_EXTRA,
		Math.random() * Z_MIN_GAP,
	);
	const rightZ = buildZTrack(
		Z_MAX,
		Z_MIN_GAP,
		Z_EXTRA,
		Math.random() * Z_MIN_GAP * 0.6,
	);
	let idx = 0;
	const nextImg = () => images[idx++ % images.length];
	const loader = new THREE.TextureLoader();
	loader.crossOrigin = "anonymous";
	const meshes = [];
	const placeSide = (side, zs) => {
		for (const z of zs) {
			const maybePair = Math.random() < 0.2 ? 2 : 1;
			for (let k = 0; k < maybePair; k++) {
				const url = nextImg();
				const map = loader.load(
					url,
					(tex) => {
						tex.colorSpace = THREE.SRGBColorSpace;
						tex.wrapS = tex.wrapT = THREE.ClampToEdgeWrapping;
						tex.generateMipmaps = true;
						const caps = renderer.capabilities;
						const aniso =
							(typeof caps.getMaxAnisotropy === "function"
								? caps.getMaxAnisotropy()
								: caps.maxAnisotropy) || 4;
						tex.anisotropy = aniso;
						fitPlaneToTextureMain(mesh, BASE_W);
						renderer.render(scene, camera);
					},
					void 0,
					() => {},
				);
				const mat = new THREE.MeshBasicMaterial({
					map,
					alphaMap: maskTex,
					transparent: true,
					alphaTest: 1e-3,
					depthWrite: false,
					fog: true,
					side: THREE.DoubleSide,
				});
				const mesh = new THREE.Mesh(planeGeo, mat);
				const x =
					side * (WALL_X_MIN + Math.random() * (WALL_X_MAX - WALL_X_MIN));
				const y = Y_MIN + Math.random() * (Y_MAX - Y_MIN);
				const u = z / Z_MAX;
				const edgeFactor =
					1 + EDGE_GAP_BOOST * Math.pow(Math.abs(2 * u - 1), 1.5);
				const pairOffset =
					k > 0
						? randRange(Z_MIN_GAP * 0.35, Z_MIN_GAP * 0.6) *
							edgeFactor *
							(Math.random() < 0.5 ? -1 : 1)
						: 0;
				const zLocal = z + pairOffset;
				mesh.position.set(x, y, zLocal);
				mesh.lookAt(0, y, zLocal);
				scene.add(mesh);
				meshes.push(mesh);
			}
		}
	};
	placeSide(-1, leftZ);
	placeSide(1, rightZ);
	renderer.render(scene, camera);
	const ro = new ResizeObserver(() => {
		setSize();
		camera.aspect = (view.clientWidth || 1) / (view.clientHeight || 1);
		camera.updateProjectionMatrix();
		renderer.render(scene, camera);
	});
	ro.observe(view);
	const dispose = () => {
		try {
			ro.disconnect();
			meshes.forEach((m) => {
				const mat = m.material;
				mat.map?.dispose();
				mat.alphaMap?.dispose();
				mat.dispose();
				m.geometry.dispose();
				scene.remove(m);
			});
			planeGeo.dispose();
			maskTex.dispose();
			renderer.dispose();
		} catch {}
	};
	return {
		dispose,
	};
}
function randRange(a, b) {
	return a + Math.random() * (b - a);
}
function buildZTrack(maxZ, minGap, extra, phase = 0) {
	const zs = [];
	let z = randRange(0, minGap) + phase;
	while (z < maxZ) {
		const u = z / maxZ;
		const edgeFactor = 1 + EDGE_GAP_BOOST * Math.pow(Math.abs(2 * u - 1), 1.5);
		zs.push(z + randRange(-Z_WOBBLE, Z_WOBBLE));
		z += minGap * edgeFactor + Math.random() * (extra * edgeFactor);
	}
	return zs;
}
function fitPlaneToTextureMain(mesh, baseW = BASE_W) {
	const img = mesh.material?.map?.image;
	if (!img || !img.width || !img.height) return;
	const aspect = img.width / img.height;
	const w = baseW;
	const h = w / aspect;
	mesh.scale.set(w, h, 1);
}
function roundedAlphaTextureMain(radiusUV = CORNER_RADIUS_UV, size = 256) {
	const c = document.createElement("canvas");
	c.width = c.height = size;
	const ctx = c.getContext("2d");
	ctx.clearRect(0, 0, size, size);
	ctx.fillStyle = "#000";
	ctx.fillRect(0, 0, size, size);
	ctx.fillStyle = "#fff";
	const r = Math.max(0, Math.min(0.5, radiusUV)) * size;
	roundRect(ctx, 0, 0, size, size, r);
	ctx.fill();
	const tex = new THREE.CanvasTexture(c);
	tex.generateMipmaps = false;
	tex.minFilter = THREE.LinearFilter;
	tex.magFilter = THREE.LinearFilter;
	tex.colorSpace = THREE.NoColorSpace;
	tex.wrapS = tex.wrapT = THREE.ClampToEdgeWrapping;
	return tex;
}
function roundRect(ctx, x, y, w, h, r) {
	const rr = Math.min(r, w / 2, h / 2);
	ctx.beginPath();
	ctx.moveTo(x + rr, y);
	ctx.arcTo(x + w, y, x + w, y + h, rr);
	ctx.arcTo(x + w, y + h, x, y + h, rr);
	ctx.arcTo(x, y + h, x, y, rr);
	ctx.arcTo(x, y, x + w, y, rr);
	ctx.closePath();
}
function makeWorkerURL() {
	const src = `
    /* Worker: PhotoTunnel */
    self.importScripts('https://unpkg.com/three@0.160.0/build/three.min.js');

    let renderer, scene, camera, canvas;
    let width = 1, height = 1, dpr = 1;
    let SMOOTH = 0.08;
    let zCurrent = ${START_Z};
    let targetZ = 0;
    let mouseX = 0, mouseY = 0;
    let running = false;

    let CONST = ${JSON.stringify({
			WALL_X_MIN,
			WALL_X_MAX,
			Y_MIN,
			Y_MAX,
			Z_MAX,
			Z_MIN_GAP,
			Z_EXTRA,
			Z_WOBBLE,
			EDGE_GAP_BOOST,
			BASE_W,
			CAMERA_FOV,
			START_Z,
			FAR_PAD,
			LOOK_PARALLAX,
			CORNER_RADIUS_UV,
		})};

    const meshes = [];
    let planeGeo = null;
    let maskTex = null;

    // Helpers
    const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
    const rand = (a, b) => a + Math.random() * (b - a);

    function buildZTrack(maxZ, minGap, extra, phase = 0){
        const zs = [];
        let z = rand(0, minGap) + phase;
        while (z < maxZ) {
            const u = z / maxZ;
            const edgeFactor = 1 + CONST.EDGE_GAP_BOOST * Math.pow(Math.abs(2*u - 1), 1.5);
            zs.push(z + rand(-CONST.Z_WOBBLE, CONST.Z_WOBBLE));
            z += minGap * edgeFactor + Math.random() * (extra * edgeFactor);
        }
        return zs;
    }

    function roundedAlphaTexture(radiusUV = CONST.CORNER_RADIUS_UV, size = 256){
        const c = new OffscreenCanvas(size, size);
        const ctx = c.getContext('2d');
        ctx.clearRect(0,0,size,size);
        ctx.fillStyle = '#000';
        ctx.fillRect(0,0,size,size);
        ctx.fillStyle = '#fff';
        const r = Math.max(0, Math.min(0.5, radiusUV)) * size;
        // round rect
        const rr = Math.min(r, size/2, size/2);
        ctx.beginPath();
        ctx.moveTo(rr, 0);
        ctx.arcTo(size, 0, size, size, rr);
        ctx.arcTo(size, size, 0, size, rr);
        ctx.arcTo(0, size, 0, 0, rr);
        ctx.arcTo(0, 0, size, 0, rr);
        ctx.closePath();
        ctx.fill();

        const tex = new self.THREE.CanvasTexture(c);
        tex.generateMipmaps = false;
        tex.minFilter = self.THREE.LinearFilter;
        tex.magFilter = self.THREE.LinearFilter;
        tex.colorSpace = self.THREE.NoColorSpace;
        tex.wrapS = tex.wrapT = self.THREE.ClampToEdgeWrapping;
        return tex;
    }

    async function loadTexture(url){
        try{
            const res = await fetch(url, { mode: 'cors' });
            const blob = await res.blob();
            const bmp = await createImageBitmap(blob, { premultiplyAlpha: 'none' });
            const tex = new self.THREE.Texture(bmp);
            tex.needsUpdate = true;
            tex.colorSpace = self.THREE.SRGBColorSpace;
            tex.wrapS = tex.wrapT = self.THREE.ClampToEdgeWrapping;
            return { tex, w: bmp.width, h: bmp.height };
        }catch(e){
            const oc = new OffscreenCanvas(1,1);
            const ctx = oc.getContext('2d');
            ctx.fillStyle = '#000'; ctx.fillRect(0,0,1,1);
            const tex = new self.THREE.CanvasTexture(oc);
            tex.needsUpdate = true;
            tex.colorSpace = self.THREE.NoColorSpace;
            return { tex, w: 1, h: 1 };
        }
    }

    function fitPlane(mesh, imgW, imgH, baseW){
        if(!imgW || !imgH) return;
        const aspect = imgW / imgH;
        const w = baseW;
        const h = w / aspect;
        mesh.scale.set(w, h, 1);
    }

    async function placeSide(side, zs, next){
        for(const z of zs){
            const maybePair = Math.random() < 0.2 ? 2 : 1;
            for(let k=0;k<maybePair;k++){
                const url = next();
                // placeholder 1x1 to avoid missing material
                const ph = new OffscreenCanvas(1,1);
                const phTex = new self.THREE.CanvasTexture(ph);
                const mat = new self.THREE.MeshBasicMaterial({
                    map: phTex,
                    alphaMap: maskTex,
                    transparent: true,
                    alphaTest: 0.001,
                    depthWrite: false,
                    fog: true,
                    side: self.THREE.DoubleSide
                });
                const mesh = new self.THREE.Mesh(planeGeo, mat);

                const x = side * rand(CONST.WALL_X_MIN, CONST.WALL_X_MAX);
                const y = rand(CONST.Y_MIN, CONST.Y_MAX);

                const u = z / CONST.Z_MAX;
                const edgeFactor = 1 + CONST.EDGE_GAP_BOOST * Math.pow(Math.abs(2*u - 1), 1.5);
                const pairOffset = k>0
                    ? rand(CONST.Z_MIN_GAP*0.35, CONST.Z_MIN_GAP*0.6)*edgeFactor*(Math.random()<0.5?-1:1)
                    : 0;
                const zLocal = z + pairOffset;

                mesh.position.set(x, y, zLocal);
                mesh.lookAt(0, y, zLocal);
                scene.add(mesh);
                meshes.push(mesh);

                // Load real texture async and update
                loadTexture(url).then(({tex, w, h})=>{
                    mat.map?.dispose();
                    mat.map = tex;
                    fitPlane(mesh, w, h, CONST.BASE_W);
                    mat.needsUpdate = true;
                }).catch(()=>{});
            }
        }
    }

    function resize({width: W, height: H, dpr: DPR}){
        width = Math.max(1, W|0); height = Math.max(1, H|0); dpr = Math.max(1, Math.min(2, DPR||1));
        renderer.setPixelRatio(dpr);
        renderer.setSize(width, height, false);
        camera.aspect = width/height;
        camera.updateProjectionMatrix();
    }

    function tick(){
        if(!running) return;
        // simple ~60fps loop
        zCurrent += (targetZ - zCurrent) * SMOOTH;
        camera.position.set(0, 0, zCurrent + CONST.START_Z);
        const lookX = mouseX * CONST.LOOK_PARALLAX;
        const lookY = mouseY * CONST.LOOK_PARALLAX * 0.4;
        camera.lookAt(lookX, lookY, zCurrent + 10);
        renderer.render(scene, camera);
        setTimeout(tick, 16);
    }

    self.onmessage = async (e) => {
        const msg = e.data || {};
        if(msg.type === 'init'){
            CONST = Object.assign({}, CONST, msg.constants || {});
            SMOOTH = Math.max(0.02, Math.min(0.2, msg.smooth || 0.08));

            canvas = msg.canvas;
            width = msg.width; height = msg.height; dpr = msg.dpr;

            // Prefer explicit context to hint desynchronized
            const gl = canvas.getContext('webgl2', {
                alpha: true,
                antialias: true,
                desynchronized: true,
                premultipliedAlpha: true,
                preserveDrawingBuffer: false
            }) || canvas.getContext('webgl', {
                alpha: true,
                antialias: true,
                desynchronized: true
            });

            renderer = new self.THREE.WebGLRenderer({
                canvas: canvas,
                context: gl,
                alpha: true,
                antialias: true,
                premultipliedAlpha: true,
                powerPreference: 'high-performance'
            });
            renderer.outputColorSpace = self.THREE.SRGBColorSpace;
            renderer.setClearColor(0x000000, 0);

            scene = new self.THREE.Scene();
            scene.fog = new self.THREE.FogExp2(0x000000, 0.025);

            camera = new self.THREE.PerspectiveCamera(
                CONST.CAMERA_FOV,
                width/height,
                0.1,
                CONST.FAR_PAD + CONST.Z_MAX + 100
            );
            camera.position.set(0, 0, CONST.START_Z);
            camera.lookAt(0, 0, CONST.START_Z + 10);

            scene.add(new self.THREE.AmbientLight(0xffffff, 0.85));
            const dir = new self.THREE.DirectionalLight(0xffffff, 0.55);
            dir.position.set(1, 2, 1);
            scene.add(dir);

            planeGeo = new self.THREE.PlaneGeometry(1, 1);
            {
  // Flip UV.y \u0432 \u0432\u043E\u0440\u043A\u0435\u0440\u0435
  const uv = planeGeo.attributes.uv;
  for (let i = 0; i < uv.count; i++) uv.setY(i, 1 - uv.getY(i));
  uv.needsUpdate = true;
}
            maskTex = roundedAlphaTexture(CONST.CORNER_RADIUS_UV, 256);
            

            const leftZ = buildZTrack(CONST.Z_MAX, CONST.Z_MIN_GAP, CONST.Z_EXTRA, Math.random()*CONST.Z_MIN_GAP);
            const rightZ = buildZTrack(CONST.Z_MAX, CONST.Z_MIN_GAP, CONST.Z_EXTRA, Math.random()*CONST.Z_MIN_GAP*0.6);

            const imgs = (msg.images || []).slice();
            // already shuffled by main; still ok if not
            let idx = 0; const next = () => imgs[(idx++) % Math.max(1, imgs.length)];

            await Promise.all([
                placeSide(-1, leftZ, next),
                placeSide(+1, rightZ, next)
            ]);

            resize({width, height, dpr});
            running = true;
            tick();
        }
        else if(msg.type === 'resize'){
            resize(msg);
        }
        else if(msg.type === 'pointer'){
            mouseX = msg.x || 0;
            mouseY = msg.y || 0;
        }
        else if(msg.type === 'progress'){
            targetZ = msg.targetZ || 0;
        }
        else if(msg.type === 'dispose'){
            running = false;
            try {
                meshes.forEach((m)=>{
                    const mat = m.material;
                    if(mat && mat.map) mat.map.dispose && mat.map.dispose();
                    if(mat && mat.alphaMap) mat.alphaMap.dispose && mat.alphaMap.dispose();
                    mat && mat.dispose && mat.dispose();
                    m.geometry && m.geometry.dispose && m.geometry.dispose();
                    scene.remove(m);
                });
                planeGeo && planeGeo.dispose && planeGeo.dispose();
                maskTex && maskTex.dispose && maskTex.dispose();
                renderer && renderer.dispose && renderer.dispose();
            } catch(e){}
        }
    };
    `;
	const blob = new Blob([src], {
		type: "application/javascript",
	});
	return URL.createObjectURL(blob);
}
addPropertyControls(PhotoTunnel, {
	images: {
		type: ControlType.Array,
		title: "Images",
		maxCount: 20,
		control: {
			type: ControlType.Image,
		},
	},
	smooth: {
		type: ControlType.Number,
		title: "Smoothing",
		min: 0.02,
		max: 0.2,
		step: 5e-3,
		defaultValue: 0.08,
	},
});
PhotoTunnel.defaultProps = {
	width: 1200,
	height: 3e3,
	images: [],
	smooth: 0.08,
};

// /:https://framerusercontent.com/modules/Xhfeu75wvKAI84k0dLY1/7OqmRY5ixQiKgn1Qm3VD/APARTlsSv.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/bK2Wc0mC5aOxTq2pWZ63/ZVn17M9krKFjiITQsYki/LFTrb0jZU.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FR;InterDisplay-Light",
	"FR;InterDisplay",
	"FR;InterDisplay-Italic",
	"FR;InterDisplay-LightItalic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/MaMAn5Jp5gJg1z3VaLH65QwWPLc.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/fEqgEChcTaneQFxeugexHq7Bk.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/nL7d8Ph0ViwUQorApF89PoAagQI.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/YOHXUQlY1iC2t7qT4HeLSoBDtn4.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/TfzHIi6ZmZDuhnIFGcgM6Ipuim4.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/CnMzVKZxLPB68RITfNGUfLe65m4.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/ub5XwqqEAMrXQz31ej6fNqbxnBc.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/2uIBiALfCHVpWbHqRMZutfT7giU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Zwfz6xbVe5pmcWRJRgBDHnMkOkI.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/U9LaDDmbRhzX3sB8g8glTy5feTE.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tVew2LzXJ1t7QfxP1gdTIdj2o0g.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DF7bjCRmStYPqSb945lAlMfCCVQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/bHYNJqzTyl2lqvmMiRRS6Y16Es.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/vebZUMjGyKkYsfcY73iwWTzLNag.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/THWAFHoAcmqLMy81E8hCSdziVKA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/sQxGYWDlRkDr0eOKqiNRl6g5rs.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NNTAT1XAm8ZRkr824inYPkjNeL4.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/P2qr9PAWBt905929rHfxmneMUG0.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/2BmSa4TZZvFKAZg2DydxTbvKlTU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/P0JCAnd2N1Q6qwTQohre3XmQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/KMFW46iYsEZaUBwXbwPc9nQm71o.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/JVGAsgKKXCCsDQ3MCrxIs5u1U.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/GeFYhvsobZhw8u0Xza2zCmC8Cw.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/8dxmIktsyEgZt0OloSu5gz6TgLI.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/f2kclCrwmFV8YeznrosrT3kcjE.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/HTPyW5jOpXfwIja9CrgNJUDriY4.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/raPlI8zqlyoXu4yBGiiecGg2dI.woff2",
				weight: "300",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/xFtzow8wtMpaEQuIGgCbt25Qorg.woff2",
				weight: "300",
			},
		],
	},
];
var css2 = [
	'.framer-jXiCk .framer-styles-preset-1ud6gfb:not(.rich-text-wrapper), .framer-jXiCk .framer-styles-preset-1ud6gfb.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: 0.85px; --framer-line-height: 27px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1599px) and (min-width: 1200px) { .framer-jXiCk .framer-styles-preset-1ud6gfb:not(.rich-text-wrapper), .framer-jXiCk .framer-styles-preset-1ud6gfb.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: 0.85px; --framer-line-height: 27px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-jXiCk .framer-styles-preset-1ud6gfb:not(.rich-text-wrapper), .framer-jXiCk .framer-styles-preset-1ud6gfb.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: 0.85px; --framer-line-height: 23px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-jXiCk .framer-styles-preset-1ud6gfb:not(.rich-text-wrapper), .framer-jXiCk .framer-styles-preset-1ud6gfb.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-font-weight-bold-italic: 400; --framer-font-weight-italic: 300; --framer-letter-spacing: 0.75px; --framer-line-height: 23px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className2 = "framer-jXiCk";

// /:https://framerusercontent.com/modules/nTgfTWSUCMLpJKwNSj99/j24FVVqyJTolaga6Xa1q/TUHGD6dmV.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"FR;InterDisplay",
	"FR;InterDisplay-Bold",
	"FR;InterDisplay-BoldItalic",
	"FR;InterDisplay-Italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/2uIBiALfCHVpWbHqRMZutfT7giU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Zwfz6xbVe5pmcWRJRgBDHnMkOkI.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/U9LaDDmbRhzX3sB8g8glTy5feTE.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tVew2LzXJ1t7QfxP1gdTIdj2o0g.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DF7bjCRmStYPqSb945lAlMfCCVQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/bHYNJqzTyl2lqvmMiRRS6Y16Es.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/vebZUMjGyKkYsfcY73iwWTzLNag.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/I11LrmuBDQZweplJ62KkVsklU5Y.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/UjFZPDy3qGuDktQM4q9CxhKfIa8.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/8exwVHJy2DhJ4N5prYlVMrEKmQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/UTeedEK21hO5jDxEUldzdScUqpg.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/Ig8B8nzy11hzIWEIYnkg91sofjo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/qITWJ2WdG0wrgQPDb8lvnYnTXDg.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/qctQFoJqJ9aIbRSIp0AhCQpFxn8.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/fXvVh2JeZlehNcEhKHpHH0frSl0.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/7pScaNeb6M7n2HF2jKemDqzCIr4.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/qS4UjQYyATcVV9rODk0Zx9KhkY8.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/VfD2n20yM7v0hrUEBHEyafsmMBY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/4oIO9fB59bn3cKFWz7piCj28z9s.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/MzumQQZJQBC6KM1omtmwOtsogtI.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/F5Lmfd3fCAu7TwiYbI4DLWw4ks.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/THWAFHoAcmqLMy81E8hCSdziVKA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/sQxGYWDlRkDr0eOKqiNRl6g5rs.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NNTAT1XAm8ZRkr824inYPkjNeL4.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/P2qr9PAWBt905929rHfxmneMUG0.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/2BmSa4TZZvFKAZg2DydxTbvKlTU.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/P0JCAnd2N1Q6qwTQohre3XmQ.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter Display",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter Display",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/KMFW46iYsEZaUBwXbwPc9nQm71o.woff2",
				weight: "400",
			},
		],
	},
];
var css3 = [
	'.framer-qYUgB .framer-styles-preset-2q46y2:not(.rich-text-wrapper), .framer-qYUgB .framer-styles-preset-2q46y2.rich-text-wrapper p { --framer-font-family: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-family-italic: "Inter Display", "Inter Display Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0.5px; --framer-line-height: 18px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className3 = "framer-qYUgB";

// /:https://framerusercontent.com/modules/Xhfeu75wvKAI84k0dLY1/7OqmRY5ixQiKgn1Qm3VD/APARTlsSv.js
var cycleOrder = ["fsFHuIjbU", "XxaEe4aKd"];
var serializationHash = "framer-yWLJG";
var variantClassNames = {
	fsFHuIjbU: "framer-v-1ag5q86",
	XxaEe4aKd: "framer-v-1d7avrq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Tablet & Phone": "XxaEe4aKd",
	Desktop: "fsFHuIjbU",
};
var getProps = ({
	avatar,
	companyName,
	height,
	id,
	name1,
	position,
	text,
	width,
	...props
}) => {
	return {
		...props,
		K_LT0c23P: avatar ??
			props.K_LT0c23P ?? {
				alt: "",
				pixelHeight: 240,
				pixelWidth: 240,
				src: "https://framerusercontent.com/images/56mB69E6fUVzDUEjh6zebhpnT4U.png?width=240&height=240",
			},
		kdbrajH9b: companyName ?? props.kdbrajH9b ?? "Alder Home",
		OBzr6k67y:
			text ??
			props.OBzr6k67y ??
			"Their AI rounds gave us dozens of on-brand hero and card options in two days. The team cut noise, tightened copy, and aligned the catalog around decision paths. Checkout friction dropped after they simplified shipping and wallet pay. ",
		oopV75N6n: position ?? props.oopV75N6n ?? "CMO",
		u_BFHMT2e: name1 ?? props.u_BFHMT2e ?? "Kate Wellington",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fsFHuIjbU",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		K_LT0c23P,
		u_BFHMT2e,
		oopV75N6n,
		kdbrajH9b,
		OBzr6k67y,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fsFHuIjbU",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className3, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ag5q86",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fsFHuIjbU"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								XxaEe4aKd: {
									"data-framer-name": "Tablet & Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1s7028l"}
							data-framer-name={"Avatar & Name"}
							layoutDependency={layoutDependency}
							layoutId={"LFw5JoOd7"}
						>
							<motion.div
								className={"framer-1hrs938"}
								data-framer-name={"Avatar"}
								layoutDependency={layoutDependency}
								layoutId={"dmxiAKPX7"}
							>
								<Image
									background={{
										alt: "",
										fit: "stretch",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 0 + 0,
										),
										pixelHeight: 240,
										pixelWidth: 240,
										sizes: "60px",
										...toResponsiveImage(K_LT0c23P),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1x1i6uy"}
									data-framer-name={"Avatar"}
									layoutDependency={layoutDependency}
									layoutId={"HxHYctOlt"}
								/>
								<motion.div
									className={"framer-19d2fpw"}
									data-framer-name={"Lines"}
									layoutDependency={layoutDependency}
									layoutId={"FZS988AAi"}
								>
									<SVG
										className={"framer-rucadx"}
										data-framer-name={"Lines"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"q6MKcBaNq"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 8 8"><path d="M 1 9 L 1 3.737 L 1.526 3.211" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 9 1 L 3.737 1 L 3.21 1.526" fill="transparent" stroke="var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)) /* {&quot;name&quot;:&quot;Orange&quot;} */" stroke-miterlimit="10" stroke-dasharray=""></path></svg>'
										}
										svgContentId={8869803245}
										withExternalLayout={true}
									/>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-nsx8zn"}
								data-framer-name={"Name & Position"}
								layoutDependency={layoutDependency}
								layoutId={"VvRxxsSAB"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-9sip6d"}
									data-framer-name={"Kate Wellington"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"iwO4ZtHlC"}
									style={{
										"--extracted-1w1cjl5":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={u_BFHMT2e}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h6
											className={"framer-styles-preset-92mpg9"}
											data-styles-preset={"pLAsvwM58"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-1w1cjl5, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
											}}
										>
											{"Kate Wellington"}
										</motion.h6>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1p4hvp3"}
									data-framer-name={"Position & Company"}
									layoutDependency={layoutDependency}
									layoutId={"WEUTghPWw"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-rmhq3"}
										data-framer-name={"CMO"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"SQhgiuCRi"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={oopV75N6n}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-2q46y2"}
												data-styles-preset={"TUHGD6dmV"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"CMO"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										className={"framer-1bi02em"}
										data-framer-name={"Divider"}
										layoutDependency={layoutDependency}
										layoutId={"Xb1sWjGEo"}
										style={{
											backgroundColor:
												"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
										}}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-cm9vba"}
										data-framer-name={"Alder Home"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Tugt4NMkp"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={kdbrajH9b}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-2q46y2"}
												data-styles-preset={"TUHGD6dmV"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
												}}
											>
												{"Alder Home"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-no5yea"}
							data-framer-name={
								"Their AI rounds gave us dozens of on-brand hero and card options in two days. The team cut noise, tightened copy, and aligned the catalog around decision paths. Checkout friction dropped after they simplified shipping and wallet pay."
							}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"NvAn88Jhy"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-01059a39-a761-426d-acce-d63b217ea6c2, rgba(255, 255, 255, 0.8))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={OBzr6k67y}
							verticalAlignment={"center"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1ud6gfb"}
									data-styles-preset={"LFTrb0jZU"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-01059a39-a761-426d-acce-d63b217ea6c2, rgba(255, 255, 255, 0.8)))",
									}}
								>
									{
										"Their AI rounds gave us dozens of on-brand hero and card options in two days. The team cut noise, tightened copy, and aligned the catalog around decision paths. Checkout friction dropped after they simplified shipping and wallet pay. "
									}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-yWLJG.framer-vjpvy, .framer-yWLJG .framer-vjpvy { display: block; }",
	".framer-yWLJG.framer-1ag5q86 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 33px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 380px; }",
	".framer-yWLJG .framer-1s7028l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 45px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-yWLJG .framer-1hrs938 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 60px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 60px; }",
	".framer-yWLJG .framer-1x1i6uy { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 60px); position: relative; width: 60px; }",
	".framer-yWLJG .framer-19d2fpw { flex: none; height: 8px; left: -10px; overflow: var(--overflow-clip-fallback, clip); position: absolute; top: -10px; width: 8px; z-index: 1; }",
	".framer-yWLJG .framer-rucadx { flex: none; height: 8px; left: calc(50.00000000000002% - 8px / 2); position: absolute; top: calc(50.00000000000002% - 8px / 2); width: 8px; }",
	".framer-yWLJG .framer-nsx8zn { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; }",
	".framer-yWLJG .framer-9sip6d, .framer-yWLJG .framer-rmhq3, .framer-yWLJG .framer-cm9vba { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-yWLJG .framer-1p4hvp3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-yWLJG .framer-1bi02em { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 2px; }",
	".framer-yWLJG .framer-no5yea { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	...css,
	...css3,
	...css2,
];
var FramerAPARTlsSv = withCSS(Component, css4, "framer-yWLJG");
var stdin_default = FramerAPARTlsSv;
FramerAPARTlsSv.displayName = "Testimonial - Card";
FramerAPARTlsSv.defaultProps = {
	height: 255,
	width: 380,
};
addPropertyControls2(FramerAPARTlsSv, {
	variant: {
		options: ["fsFHuIjbU", "XxaEe4aKd"],
		optionTitles: ["Desktop", "Tablet & Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	K_LT0c23P: {
		__defaultAssetReference:
			"data:framer/asset-reference,56mB69E6fUVzDUEjh6zebhpnT4U.png?width=240&height=240",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,56mB69E6fUVzDUEjh6zebhpnT4U.png?width=240&height=240",
		},
		description: "120x120 px",
		title: "Avatar",
		type: ControlType2.ResponsiveImage,
	},
	u_BFHMT2e: {
		defaultValue: "Kate Wellington",
		displayTextArea: true,
		title: "Name",
		type: ControlType2.String,
	},
	oopV75N6n: {
		defaultValue: "CMO",
		displayTextArea: false,
		title: "Position",
		type: ControlType2.String,
	},
	kdbrajH9b: {
		defaultValue: "Alder Home",
		displayTextArea: false,
		title: "Company Name",
		type: ControlType2.String,
	},
	OBzr6k67y: {
		defaultValue:
			"Their AI rounds gave us dozens of on-brand hero and card options in two days. The team cut noise, tightened copy, and aligned the catalog around decision paths. Checkout friction dropped after they simplified shipping and wallet pay. ",
		displayTextArea: true,
		title: "Text",
		type: ControlType2.String,
	},
});
addFonts(
	FramerAPARTlsSv,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/lKnCYGrh7ZUgRwL0ANe0/GVLUNonHGbbXt7yPE6OM/HwdSExb6a.js
var TestimonialCardFonts = getFonts(stdin_default);
var PhotoTunnelFonts = getFonts(PhotoTunnel);
var cycleOrder2 = ["iDJp8oyP1", "OtUfQlZw1", "mKpd5zGPC", "zRMDxssex"];
var serializationHash2 = "framer-QpipL";
var variantClassNames2 = {
	iDJp8oyP1: "framer-v-u028yh",
	mKpd5zGPC: "framer-v-1v5xuxd",
	OtUfQlZw1: "framer-v-m1d37l",
	zRMDxssex: "framer-v-3c5lhe",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Wide Screen": "iDJp8oyP1",
	Laptop: "OtUfQlZw1",
	Phone: "zRMDxssex",
	Tablet: "mKpd5zGPC",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "iDJp8oyP1",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "iDJp8oyP1",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.section
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-u028yh",
							className4,
							classNames,
						)}
						data-framer-name={"Wide Screen"}
						layoutDependency={layoutDependency}
						layoutId={"iDJp8oyP1"}
						ref={refBinding}
						style={{
							background:
								"linear-gradient(180deg, var(--token-7aee89be-f7d7-4b0b-b618-6062693d065d, rgb(0, 0, 0)) 75%, var(--token-c2bd673c-721e-4e0b-8423-cd96f32a961f, rgb(31, 31, 31)) 100%)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								mKpd5zGPC: {
									"data-framer-name": "Tablet",
								},
								OtUfQlZw1: {
									"data-framer-name": "Laptop",
								},
								zRMDxssex: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-vg1kpn"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"mrd8m1JJg"}
						>
							<motion2.div
								className={"framer-x191cg"}
								data-framer-name={"Heading FIt"}
								layoutDependency={layoutDependency}
								layoutId={"Ts_Y8NKdP"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-5mlzyn"}
									fonts={["GF;Mozilla Text-500"]}
									layoutDependency={layoutDependency}
									layoutId={"Pj1IHjVtn"}
									style={{
										"--extracted-1w3ko1f":
											"var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48))",
										"--extracted-r6o4lv":
											"var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									viewBox={"0 0 1344.4895363151415 276"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											style={{
												"--font-selector": "R0Y7TW96aWxsYSBUZXh0LTUwMA==",
												"--framer-font-family":
													'"Mozilla Text", "Mozilla Text Placeholder", sans-serif',
												"--framer-font-size": "229.79072630283133px",
												"--framer-font-weight": "500",
												"--framer-letter-spacing": "-0.05em",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-cabcd209-02ce-41bf-9dfa-3682975d9176, rgb(255, 255, 255)))",
											}}
										>
											{"Testimonials"}
											<motion2.span
												style={{
													"--framer-text-color":
														"var(--extracted-1w3ko1f, var(--token-f7eb9440-9c7c-4693-9d23-740211c4f1b2, rgb(251, 73, 48)))",
												}}
											>
												{"."}
											</motion2.span>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
							<motion2.div
								className={"framer-1lytv5o"}
								data-framer-name={"Spacer"}
								layoutDependency={layoutDependency}
								layoutId={"DrLa4uaCU"}
							/>
							<motion2.div
								className={"framer-inuyb9"}
								data-framer-name={"List"}
								layoutDependency={layoutDependency}
								layoutId={"k1JDFtgMt"}
								transformTemplate={transformTemplate1}
								{...addPropertyOverrides2(
									{
										zRMDxssex: {
											transformTemplate: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<ComponentViewportProvider
									height={255}
									width={"380px"}
									{...addPropertyOverrides2(
										{
											zRMDxssex: {
												width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-4ye35r-container"}
										layoutDependency={layoutDependency}
										layoutId={"QOZXZob6q-container"}
										nodeId={"QOZXZob6q"}
										rendersWithMotion={true}
										scopeId={"HwdSExb6a"}
									>
										{_jsx3(stdin_default, {
											height: "100%",
											id: "QOZXZob6q",
											kdbrajH9b: "Alder Home",
											layoutId: "QOZXZob6q",
											OBzr6k67y:
												"Their AI rounds gave us dozens of on-brand hero and card options in two days. The team cut noise, tightened copy, and aligned the catalog around decision paths. Checkout friction dropped after they simplified shipping and wallet pay. ",
											oopV75N6n: "CMO",
											style: {
												width: "100%",
											},
											u_BFHMT2e: "Kate Wellington",
											variant: "fsFHuIjbU",
											width: "100%",
											...addPropertyOverrides2(
												{
													mKpd5zGPC: {
														variant: "XxaEe4aKd",
													},
													zRMDxssex: {
														variant: "XxaEe4aKd",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={255}
									width={"380px"}
									{...addPropertyOverrides2(
										{
											zRMDxssex: {
												width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-jmvtl2-container"}
										layoutDependency={layoutDependency}
										layoutId={"zIxKigSHi-container"}
										nodeId={"zIxKigSHi"}
										rendersWithMotion={true}
										scopeId={"HwdSExb6a"}
									>
										{_jsx3(stdin_default, {
											height: "100%",
											id: "zIxKigSHi",
											K_LT0c23P: addImageAlt(
												{
													pixelHeight: 120,
													pixelWidth: 120,
													src: "https://framerusercontent.com/images/93txGn4b5ZCk7XyI5tSqf71uJi8.jpg?width=120&height=120",
												},
												"",
											),
											kdbrajH9b: "Neon Bank",
											layoutId: "zIxKigSHi",
											OBzr6k67y:
												"They mapped our onboarding leaks, generated variant copy with constraints, and kept only what reduced cognitive load. A guided pricing step and clearer error states cut drop-offs by 22%. Sign-ups rose 27% without adding features. ",
											oopV75N6n: "Head of Product",
											style: {
												width: "100%",
											},
											u_BFHMT2e: "Paul Davidson",
											variant: "fsFHuIjbU",
											width: "100%",
											...addPropertyOverrides2(
												{
													mKpd5zGPC: {
														variant: "XxaEe4aKd",
													},
													zRMDxssex: {
														variant: "XxaEe4aKd",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={255}
									width={"380px"}
									{...addPropertyOverrides2(
										{
											zRMDxssex: {
												width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-t1bgjr-container"}
										layoutDependency={layoutDependency}
										layoutId={"Dr0e68azf-container"}
										nodeId={"Dr0e68azf"}
										rendersWithMotion={true}
										scopeId={"HwdSExb6a"}
									>
										{_jsx3(stdin_default, {
											height: "100%",
											id: "Dr0e68azf",
											K_LT0c23P: addImageAlt(
												{
													pixelHeight: 120,
													pixelWidth: 120,
													src: "https://framerusercontent.com/images/0ipdJnAf9WHG98xC5fwAf05K0EQ.jpg?width=120&height=120",
												},
												"",
											),
											kdbrajH9b: "Vello Bikes",
											layoutId: "Dr0e68azf",
											OBzr6k67y:
												"We came for a facelift and left with a content system that sells. AI helped produce ad and landing variants; the team curated three strong directions and proved one in tests. Average order value increased 12% after bundles and clearer upsell copy. ",
											oopV75N6n: "Founder",
											style: {
												width: "100%",
											},
											u_BFHMT2e: "Maya Ronan",
											variant: "fsFHuIjbU",
											width: "100%",
											...addPropertyOverrides2(
												{
													mKpd5zGPC: {
														variant: "XxaEe4aKd",
													},
													zRMDxssex: {
														variant: "XxaEe4aKd",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={255}
									width={"380px"}
									{...addPropertyOverrides2(
										{
											zRMDxssex: {
												width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-vrkrk7-container"}
										layoutDependency={layoutDependency}
										layoutId={"CsOnTpg9r-container"}
										nodeId={"CsOnTpg9r"}
										rendersWithMotion={true}
										scopeId={"HwdSExb6a"}
									>
										{_jsx3(stdin_default, {
											height: "100%",
											id: "CsOnTpg9r",
											K_LT0c23P: addImageAlt(
												{
													pixelHeight: 120,
													pixelWidth: 120,
													src: "https://framerusercontent.com/images/tliNbXXPRH3g9l2k8Je65mjKOSI.jpg?width=120&height=120",
												},
												"",
											),
											kdbrajH9b: "FMP Group",
											layoutId: "CsOnTpg9r",
											OBzr6k67y:
												"Calm design, measurable results. They explored 40+ on-brand variants in two days, cut the noise, and aligned copy with our funnel. We moved from \u2018pretty pages\u2019 to a clear story with one primary action per screen. ",
											oopV75N6n: "CEO",
											style: {
												width: "100%",
											},
											u_BFHMT2e: "William G.",
											variant: "fsFHuIjbU",
											width: "100%",
											...addPropertyOverrides2(
												{
													mKpd5zGPC: {
														variant: "XxaEe4aKd",
													},
													zRMDxssex: {
														variant: "XxaEe4aKd",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1op2flb-container"}
									isAuthoredByUser={true}
									layoutDependency={layoutDependency}
									layoutId={"s6yik97sf-container"}
									nodeId={"s6yik97sf"}
									rendersWithMotion={true}
									scopeId={"HwdSExb6a"}
								>
									<PhotoTunnel
										height={"100%"}
										id={"s6yik97sf"}
										images={[
											"https://framerusercontent.com/images/XDssn4asIgrxPvUojWfiUIdyWY.jpg?width=800&height=600",
											"https://framerusercontent.com/images/2qlp9DK1LBGoV85lpuNytB4VQ.jpg?width=800&height=600",
											"https://framerusercontent.com/images/FAp7vZ1u8Z4Ie4hhK6cHESW5RU.jpg?width=800&height=600",
											"https://framerusercontent.com/images/f1bbe4YvmxtlujhhHmJAmgSgQE.jpg?width=800&height=600",
											"https://framerusercontent.com/images/mg2bCxuNxp1jmtAhnDMVqYthTss.jpg?width=800&height=600",
											"https://framerusercontent.com/images/LzCRUVuSY6YYJ1FRPAE5YjwSs.jpg?width=800&height=600",
											"https://framerusercontent.com/images/Wc4qHZodEjy4qtHRIbhyUBfRmg.jpg?width=800&height=600",
											"https://framerusercontent.com/images/wDwj2ZhdNhroaq1oqCdeXfkuhQ4.jpg?width=800&height=600",
											"https://framerusercontent.com/images/mjcZJz7EGbCvG9CWWxat1GamME.jpg?width=800&height=600",
											"https://framerusercontent.com/images/kH0CJYPjrnUIZGjFvFmMIeCUQM.jpg?width=800&height=600",
											"https://framerusercontent.com/images/SUBCbqMVJBPAGbM32zvdDA5RsXk.jpg?width=800&height=600",
											"https://framerusercontent.com/images/tIGpbRwIB8wBF8EtDdrjjmO3zRk.jpg?width=800&height=600",
										]}
										layoutId={"s6yik97sf"}
										smooth={0.11}
										style={{
											height: "100%",
											width: "100%",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.div>
					</motion2.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QpipL.framer-1s1y45p, .framer-QpipL .framer-1s1y45p { display: block; }",
	".framer-QpipL.framer-u028yh { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1600px; }",
	".framer-QpipL .framer-vg1kpn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 150px 0px 250px 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-QpipL .framer-x191cg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 1600px; overflow: visible; padding: 0px 100px 0px 100px; position: relative; width: 100%; }",
	".framer-QpipL .framer-5mlzyn { flex: none; height: auto; position: relative; white-space: pre; width: 100%; }",
	".framer-QpipL .framer-1lytv5o { flex: none; height: 150px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; }",
	".framer-QpipL .framer-inuyb9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 150px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 600px; width: 100%; z-index: 5; }",
	".framer-QpipL .framer-4ye35r-container, .framer-QpipL .framer-jmvtl2-container, .framer-QpipL .framer-t1bgjr-container, .framer-QpipL .framer-vrkrk7-container { flex: none; height: auto; position: relative; width: 380px; z-index: 3; }",
	".framer-QpipL .framer-1op2flb-container { flex: none; height: 2500px; position: relative; width: 100%; z-index: 1; }",
	".framer-QpipL.framer-v-m1d37l.framer-u028yh { min-height: 1500px; width: 1200px; }",
	".framer-QpipL.framer-v-m1d37l .framer-vg1kpn { padding: 150px 0px 150px 0px; }",
	".framer-QpipL.framer-v-m1d37l .framer-inuyb9 { gap: 100px; top: 470px; }",
	".framer-QpipL.framer-v-1v5xuxd.framer-u028yh { gap: 0px; min-height: 1500px; width: 810px; }",
	".framer-QpipL.framer-v-1v5xuxd .framer-vg1kpn { padding: 100px 0px 100px 0px; }",
	".framer-QpipL.framer-v-1v5xuxd .framer-x191cg { padding: 0px 30px 0px 30px; }",
	".framer-QpipL.framer-v-1v5xuxd .framer-1lytv5o { height: 100px; }",
	".framer-QpipL.framer-v-1v5xuxd .framer-inuyb9 { gap: 80px; top: 340px; }",
	".framer-QpipL.framer-v-1v5xuxd .framer-1op2flb-container { height: 2000px; }",
	".framer-QpipL.framer-v-3c5lhe.framer-u028yh { gap: 0px; min-height: 1000px; width: 390px; }",
	".framer-QpipL.framer-v-3c5lhe .framer-vg1kpn { padding: 80px 0px 80px 0px; }",
	".framer-QpipL.framer-v-3c5lhe .framer-x191cg { padding: 0px 20px 0px 20px; }",
	".framer-QpipL.framer-v-3c5lhe .framer-1lytv5o { height: 80px; }",
	".framer-QpipL.framer-v-3c5lhe .framer-inuyb9 { gap: 60px; left: unset; padding: 0px 20px 0px 20px; position: sticky; top: 150px; }",
	".framer-QpipL.framer-v-3c5lhe .framer-4ye35r-container, .framer-QpipL.framer-v-3c5lhe .framer-jmvtl2-container, .framer-QpipL.framer-v-3c5lhe .framer-t1bgjr-container, .framer-QpipL.framer-v-3c5lhe .framer-vrkrk7-container { width: 100%; }",
	".framer-QpipL.framer-v-3c5lhe .framer-1op2flb-container { height: 1500px; }",
];
var FramerHwdSExb6a = withCSS2(Component2, css5, "framer-QpipL");
var stdin_default2 = FramerHwdSExb6a;
FramerHwdSExb6a.displayName = "Testimonials \u2013 Section";
FramerHwdSExb6a.defaultProps = {
	height: 3337.5,
	width: 1600,
};
addPropertyControls3(FramerHwdSExb6a, {
	variant: {
		options: ["iDJp8oyP1", "OtUfQlZw1", "mKpd5zGPC", "zRMDxssex"],
		optionTitles: ["Wide Screen", "Laptop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType3.Enum,
	},
});
addFonts2(
	FramerHwdSExb6a,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Mozilla Text",
					source: "google",
					style: "normal",
					uiFamilyName: "Mozilla Text",
					url: "https://fonts.gstatic.com/s/mozillatext/v1/SZcr3FrnJ7S7WZIff2mJ7Tbp4zu7ULu3HkPOB7ccPNVRVYmoOXo.woff2",
					weight: "500",
				},
			],
		},
		...TestimonialCardFonts,
		...PhotoTunnelFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonials-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialsSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var testimonials_section_default = ComponentWithRoot;
export { testimonials_section_default as default };
