// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1bd92cedbbf431b3 "Sentinel AI", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * timezone?: boolean // Timezone
 * selectTimezone?: 'GMT-12:00 (Etc/GMT+12)' | 'GMT-11:00 (Midway)' | 'GMT-10:00 (Honolulu)' | 'GMT-9:00 (Anchorage)' | 'GMT-8:00 (Pacific Time)' | 'GMT-7:00 (Mountain Time)' | 'GMT-6:00 (Central Time)' | 'GMT-5:00 (Eastern Time)' | 'GMT-4:30 (Caracas)' | 'GMT-4:00 (Santiago)' | 'GMT-3:00 (São Paulo)' | 'GMT-2:00 (South Georgia)' | 'GMT-1:00 (Azores)' | 'GMT+0:00 (London)' | 'GMT+1:00 (Paris)' | 'GMT+1:00 (Berlin)' | 'GMT+2:00 (Athens)' | 'GMT+3:00 (Moscow)' | 'GMT+4:00 (Dubai)' | 'GMT+5:00 (Karachi)' | 'GMT+5:30 (Kolkata)' | 'GMT+7:00 (Bangkok)' | 'GMT+8:00 (Shanghai)' | 'GMT+9:00 (Tokyo)' | 'GMT+10:00 (Sydney)' | 'GMT+12:00 (Auckland)' | 'GMT+14:00 (Kiritimati)' // Select Timezone
 * format?: '12 Hour' | '24 Hour' // Format
 * seconds?: boolean // Seconds
 * timezoneLabel?: boolean // Timezone Label
 * textColor?: string // Text Color
 * font?: undefined // Font
}} Props

 */
import { TimeZoneDisplay } from "./chunks/chunk-UOGVRX2R.js";
import { routes } from "./chunks/chunk-32AWGGTF.js";

// virtual:time-zone
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<TimeZoneDisplay {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TimeZoneFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1bd92cedbbf431b3411a7ddd12ea507e929f85a97d28da8179a9646480dcde76"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={TimeZoneDisplay}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, TimeZoneDisplay);
var time_zone_default = ComponentWithRoot;
export { time_zone_default as default };
